### ISSUE TITLE
Immobilising pod leader on scamper prevents the rest of the pod from scampering

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#1008]
Here's the scenario:

1. XCOM is in concealment
2. One of the soldiers targets a pod leader with an immobilising ability (Maim, Crippling Strike from LWOTC, or whatever)
3. The ability breaks concealment, triggering the "scamper"
4. The pod leader can't move, so doesn't scamper
5. None of the rest of the pod scampers, typically leaving them all flanked for an easy clean up

The problem is in the `XGAIBehavior.SkipTurn()` function, which has this bit of code:
```
// If unrevealed, the entire group skips its turn.  Fixes assert with group movement, after group leader skips its move.
if( StartedTurnUnrevealed() )
{
	SkipGroupTurn();
}
```
When a pod needs to scamper, this condition is always true. That means the rest of the pod will skip their turns too.

In fact, I suspect this isn't just a problem for immobilising abilities that force the pod leader to skip their turn. It may also happen if the pod leader is by some cover and just stays where they are. Not sure if this is also the cause of pod members failing to scamper if the pod leader dies on overwatch. Less likely I think.

Proposed fix is to add an additional condition to the above `if` statement:
```
if( StartedTurnUnrevealed( && !m_kPlayer.IsScampering(UnitState.ObjectID) )
{
	SkipGroupTurn();
}
```
I tested it briefly and it fixed the immediate issue. I'm fairly sure the comment about fixing an assert is most likely connected with green or yellow alert actions rather than scampering, but it's hard to be 100% sure.

**Comment by Iridar** [comment]
Could it be the case that oneshotting the pod leader fails to scamper a pod?

**Comment by pledbrook** [comment]
Possibly. I've definitely seen it happen with the pod leader dying to overwatch, but that should not correspond to the pod leader skipping their turn, since they need to move in order to trigger the overwatch.

You have reminded me that flamethrowers with Napalm-X often run into this problem if they panic the pod leader. Killing the pod leader may not trigger this behaviour, since they may not technically be skipping their turn.
