### ISSUE TITLE
Finalize introduction of the DLC2 component

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#1014]
Follow up to #999:

* [x] Expand the troubleshooting wiki page (mention DLC2HL)
* [x] Expand the workshop description to link the DLC2HL
* [x] Prepare the workshop description for DLC2HL
* [ ] Fill in `ReadMe.txt` (https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/999#discussion_r646670260). Perhaps same as previous?

cc @Iridar @robojumper

**Comment by Iridar** [comment]
I can handle the wiki, but this probably needs to be done after the DLC2 CHL is actually released.

**Comment by Xymanek** [comment]
I think all the documentation needs to be prepared before we do the beta release. People will inevitably have questions/troubles and the lack of easily accessible information can hurt the feature rollout significantly

**Comment by Iridar** [comment]
Here's a mockup of the workshop description for the DLC2CHL:
```
[WOTC] Alien Hunters Community Highlander

This mod is a plugin for [b]Community Highlander[/b] of versions 1.22 and higher, which is the current version of the [url=https://steamcommunity.com/sharedfiles/filedetails/?id=1796402257][b][BETA] X2WOTCCommunityHighlander[/b][/url].

This plugin is [b][i]REQUIRED[/i][/b] if you have the [b]Alien Hunters DLC[/b]. 

If you do [b][i]NOT[/i][/b] have the Alien Hunters DLC, then you should [b][i]NOT[/i][/b] use this plugin, as it may cause gamebreaking issues.

Similar to the Highlander itself, this plugin replaces script packages of the Alien Hunters DLC in order to make the it more moddable and mod-compatible, as well as fixing some bugs.

[h1]How do I use this plugin?[/h1]

Install and enable this mod as usual. You do not have to do anything else. Make sure to use it [b][i]ONLY[/i][/b] if you have Alien Hunters DLC installed and enabled.

If you require help or wish to contribute to this project, please follow the links in the [b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=1134256495]main Highlander description[/url][/b].
```

**Comment by Iridar** [comment]
Mockup for the mod troubleshooting wiki page:

# Alien Hunters and Highlander

If you have the **Alien Hunters DLC**, and you are using Highlander of version 1.22 or higher, then you should also install the [**[WOTC] Alien Hunters Community Highlander**](https://steamcommunity.com/sharedfiles/filedetails/?id=1796402257) plugin.

Do not install this plugin if you do not have the Alien Hunters DLC, otherwise you may experience game breaking issues. You may also see an empty popup window from time to time.

**Comment by Iridar** [comment]
Mockup for the addendum to the Highlander description:
```
[h1] Alien Hunters DLC Plugin[/h1]

If you have [b]Alien Hunters DLC[/b] installed and enabled, and you are using this version of the Highlander, then you also should install the [b][WOTC] Alien Hunters Community Highlander[/b] plugin as well.

Do [b][i]NOT[/i][/b] install that plugin if you do [b][i]NOT[/i][/b] have the Alien Hunters DLC.
```

**Comment by Iridar** [comment]
I don't think we need a separate ReadMet.txt, it can just mirror the workshop description.

**Comment by Xymanek** [comment]
> 
> 
> I don't think we need a separate ReadMet.txt, it can just mirror the workshop description.

Agreed

**Comment by Xymanek** [comment]
Can't see anything wrong with the proposed text
