### ISSUE TITLE
Script targeting style detection is too overzealous

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#1019]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/84ae0e3b34458d45b968f0893d0c3d3ae238907f/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTemplate.uc#L257-L283

I've added a bit of logging:

```uc
`log("Instantiating XComGameState_Ability_CH for" @ DataName,, 'CH_ScriptTargetStyle');
Ability = XComGameState_Ability(NewGameState.CreateNewStateObject(class'XComGameState_Ability_CH', self));
```

Result is a bit more than one would expect: https://gist.github.com/Xymanek/7d568340cb4811e8e64e5ccd50cd72d5

cc @robojumper as the author of the latest implementation (#918)

**Comment by Xymanek** [comment]
Marking this for v1.22.0 since the feature has not been yet released - not yet covered by BC policy

**Comment by Iridar** [comment]
Most likely because of the `AbilityMultiTargetStyle != none` check

**Comment by robojumper** [comment]
Massive facepalm on my side, sorry. Will fix.
