### ISSUE TITLE
WotC bug + Solution : Problems Editing Covert Action Soldier Loadouts with a Controller

### ISSUE THREAD

**Issue by kdm2k6** [X2CommunityCore/X2WOTCCommunityHighlander#1035]
**General problem**: The issue is that, while using a controller, you can edit the loadout of the 1st soldier slot for any given Covert action; however, you can not edit the loadout of the 2nd, 3rd ... soldier slot. I have come across this problem while testing LWotC; however, I believe it is a WotC bug. Additionally, I have confirmed the solution by using a modified highlander.

In order to replicate this bug do the following :

1. Go to the Covert Actions screen.
2. Choose a Covert Action which requires at least 2 soldiers.
3. Using the A button, add a soldier to each soldier slot.
4. Press the Y button while the 1st soldier slot is active; notice that the loadout screen for that soldier is brought up. This is working as intended.
5. Go back and press the Y button while the 2nd soldier slot is active; notice that the loadout screen for the 1st soldier is brought up. This is a problem.

**Why this occurs** : Within the `UIScreen`, `UICovertActions`, the code : `SlotContainer.Navigator.SelectedIndex` is used to determine which particular slot within the slot container is currently selected. This can be seen within `OnUnrealCommand`, where the A button :

1. Determines which `UICovertActionStaffSlot` is selected via the call : `SlotContainer.Navigator.SelectedIndex`
2. Calls `HandleClick `on this slot, sending in the parameter "theButton" via : `SlotContainer.ActionSlots[SlotContainer.Navigator.SelectedIndex].HandleClick("theButton")`.
3. `UICovertActionStaffSlot.HandleClick` then determines if this slot should be filled with a soldier, or emptied, depending upon its current state.

Unfortunately in several locations, including the `EditSoldierLoadout` function, the selected slot is determined via `Navigator.SelectedIndex` rather than `SlotContainer.Navigator.SelectedIndex`. This results in the index value 0 always being returned and the 1st soldier slot being "dealt with". I never tested exactly what `Navigator.SelectedIndex` referenced, but I would guess the screen's navigator is pointing to the slot container itself.

**Solution** : There are 3 problematic lines of code within `UICovertActions`.

1.] Within the function : `RefreshNavigation`.
`if( SlotContainer.ActionSlots[Navigator.SelectedIndex].CanEditLoadout() )` should become
`if( SlotContainer.ActionSlots[SlotContainer.Navigator.SelectedIndex].CanEditLoadout() )`

2.] Within the function : `EditSoldierLoadout`
`if( SlotContainer.ActionSlots[Navigator.SelectedIndex].CanEditLoadout() )` should become 
`if( SlotContainer.ActionSlots[SlotContainer.Navigator.SelectedIndex].CanEditLoadout() )`

`SlotContainer.ActionSlots[Navigator.SelectedIndex].HandleClick("theButton2");` should become
`SlotContainer.ActionSlots[SlotContainer.Navigator.SelectedIndex].HandleClick("theButton2");`

**Comment by Xymanek** [comment]
It looks like there is a working solution already - please provide it as a PR

**Comment by araujorm** [comment]
Hello.

This is still a problem in the latest release.

I thought I could help turning the proposed solution in a PR, however I never worked with Xcom mod sources.

I cloned this repo and searched for the aforementioned functions RefreshNavigation and EditSoldierLoadout, however nothing like that exists. Nor it seems to exist any source for the UICovertActions class. Therefore I'm assuming one should get the original UICovertActions.uc file (from where? the SDK?), edit it with the proposed changes and place it along the other .uc files with the classes inside this mod Src/XComGame/Classes. Am I thinking correctly?

**Comment by robojumper** [comment]
It seems this process isn't documented in the HL repo -- we should fix that. Yes, you're correct, get the original file from SDK/Development/SrcOrig, add it **unmodified** to the project, do a commit, then make and commit your changes separately.

**Comment by araujorm** [comment]
> It seems this process isn't documented in the HL repo -- we should fix that. Yes, you're correct, get the original file from SDK/Development/SrcOrig, add it **unmodified** to the project, do a commit, then make and commit your changes separately.

Thanks.

I did that, and after hours of despair with modbuddy and all that stuff (first time with it...) I was finally able to make a modified build based on this, and I confirm that it in fact works. I made a pull request: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/1170 that therefore solves this issue.

**Comment by kdm2k6** [comment]
Great job and thanks.

**Comment by Iridar** [comment]
This issue was resolved in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/1170, closing.
