### ISSUE TITLE
Allow mods to override which alerts Can be triggered outside of player vision

### ISSUE THREAD

**Issue by Grobobobo** [X2CommunityCore/X2WOTCCommunityHighlander#1036]
Use Cases are various types of AI to AI activations. Currently mods like Yellow alert 2.0 and AI to AI use an MCO for that purpose.

**Comment by Iridar** [comment]
This issue was resolved in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/1037, closing.
