### ISSUE TITLE
Crashing at AML Startup

### ISSUE THREAD

**Issue by ProjectKaizen** [X2CommunityCore/X2WOTCCommunityHighlander#1045]
I tried the steam version, beta, and the latest release here and the mod seems to crash my game even when activated alone without my other mods. Any fix or recommendations you can give?

**Comment by robojumper** [comment]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting

**Comment by ProjectKaizen** [comment]
It seems to me that I missed a crucial plugin to make the mod work.
I installed the Alien DLC Plugin and moved Highlander mods in WOTC XcomGame Directory for good measure.
Thanks for the help.
