### ISSUE TITLE
Evaluate what to do with VERSION.ps1

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#1049]
Context: https://x2communitycore.github.io/X2WOTCCommunityHighlander/misc/ComponentVersions/

Currently, `*_Version.uc` files in the source tree (i.e. in the repository) have a more or less arbitrary version that's ignored and *always* replaced with the version in `VERSION.ps1` before compiling. This is easy to miss and a source of confusion, especially since `VERSION.ps1` is not included in the ModBuddy project (it should be!).

The general approach needs to stay because we use it to embed the commit hash into non-final releases. The version part should be discussed.

Ideas to consider:

* Replace in-tree defaultproperties version numbers with -1 to make errors obvious
* Replace them with something that triggers a hard compiler error.
* Get rid of `VERSION.ps1`, instead check that they all say the same thing in the build script.

**Comment by Iridar** [comment]
> Replace in-tree defaultproperties version numbers with -1 to make errors obvious

This seems to be the most sound approach to me, accompanied by a comment near every one of them that the actual version is specified in `VERSION.ps1` and updated automatically while building the mod, as well as including `VERSION.ps1` into modbuddy project.

Despite hitting a bump with this system, I do see the upside of convenience. 

One thing to note that both current and suggested implementations prohibit us from having separate versions in each of the Highlander's script packages, arguably making them pointless, other than for checking that the user somehow has script packages from different Highlander builds.
