### ISSUE TITLE
Enhance RandomAbilityDecks to respect Ability Prerequisites.

### ISSUE THREAD

**Issue by kyuubicle** [X2CommunityCore/X2WOTCCommunityHighlander#105]
If an ability with prerequisites (ex: Annihilate) and its prerequisite (ex: Banish) are put into a RandomAbilityDeck, it is possible for the ability with prerequisites to be placed into a soldier's ability tree before its prerequisite or even without the prerequisites anywhere in the tree at all.

Obviously, this isn't how the Random Ability Decks were intended to be used, but I think this could be a useful feature for randomly selecting a set of complete lines of statically ordered abilities instead of just a randomly ordered collection of random abilities.

**Comment by Iridar** [comment]
It's an interesting feature to develop, but we have to figure out how it should work first. 

Soldier's ability tree is progressively generated, rank by rank, ability by ability. 

So let's say the game randomly picks a random ability for a certain slot in a certain rank.

Let's say that ability has prerequisite abilities. How should the game proceed?

The simplest implementation would be to check the ability tree generated so far. If it contains all the prerequisite abilities, then the random ability is added to the tree.

But what if the ability tree does not contain all of the prerequisite abilities? Should the random ability for this slot just come blank this time around?

Should the random ability be then excluded from this RandomAbilityDeck so it should not come up again in the future?

It seems reasonable to me that the random ability that was missing a prerequisite should be replaced by its own prerequisite, as long as that prerequisite is in the same RandomAbilityDeck. 

But what if it isn't? What if the random ability requires a prerequisite perk that comes in later in the soldier's regular ability tree?

Using OP's example, what if we put Banish as a Colonel perk, and Annihilate (that requires Banish) into Random Ability Deck. 

And what if Annihilate is randomly drawn for one of the earlier random perks? Should it be removed from the Random Ability Deck for this soldier? Should it be kept there, and potentially rolled again later? But then should it be replaced right away by another random ability? Then we risk getting stuck in an infinite re-rolling loop...
 
Lots of questions overall.

**Comment by Iridar** [comment]
All in all, this issue is probably best to be left to soak in its own juices until somebody has an actual use case for this functionality, since it will not do anything by itself. And tbh if I needed something like this for my own use, I'd rather just rebuild soldier's ability tree manually the moment they rank up to squaddie.

**Comment by Iridar** [comment]
I'm gonna close this issue so it doesn't clog the issue list, feel free to reopen if you have a use case for it.
