### ISSUE TITLE
`X2SoldierClassTemplate::IsWeaponAllowedByClass()` is inflexible

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1057]
`UIArmory_Loadout::GetDisabledReason()` runs `X2SoldierClassTemplate::IsWeaponAllowedByClass()` to check if the weapon is allowed by unit's soldier class, which is a very simple check:
```
function bool IsWeaponAllowedByClass(X2WeaponTemplate WeaponTemplate)
{
	local int i;

	switch(WeaponTemplate.InventorySlot)
	{
	case eInvSlot_PrimaryWeapon: break;
	case eInvSlot_SecondaryWeapon: break;
	default:
		return true;
	}

	for (i = 0; i < AllowedWeapons.Length; ++i)
	{
		if (WeaponTemplate.InventorySlot == AllowedWeapons[i].SlotType &&
			WeaponTemplate.WeaponCat == AllowedWeapons[i].WeaponType)
			return true;
	}
	return false;
}
```
As you can see, for primary and secondary weapons, the function checks the category and slot specified in the weapon template. However, many mods like True Primary Secondaries or Dedicated Pistol Slot allow equipping secondary weapons into slots other than specified in their weapon templates. 

However, `GetDisabledReason()` will forbid equipping the item through armory loadout UI for certain soldier classes under the premise that their soldier class template does not allow equipping the weapon in question into primary/secondary inventory slot, even though the inventory slot might have absolutely nothing to do with primary or secondary weapon slot.

This creates the requirement of using `CanAddItemToInventory_CH_Improved`, potentially causing the duplicate items bug described in #1056 if handled improperly, not to mention just having to use a function to bypass unnecessarily inflexible piece of code.

I think the optimal solution to this problem is to  create a wrapper for `IsWeaponAllowedByClass()` that would also pass the desired inventory slot as an argument, allowing the logic to be more accurate, and apply primary/secondary weapon restrictions only when the weapon is actually being equipped into these slots. Other places in code calling `IsWeaponAllowedByClass()` would have to be adjusted to use the wrapper when relevant, which is around ~7 places.

**Comment by Iridar** [comment]
While we're at it, `GetAllowedClassForWeapon()` and `GetAllowedClassForArmor()` in `UIUtilities_Strategy` do not always have a return value.

**Comment by Iridar** [comment]
Would it be okay for me to fix that in the context of this PR, or do I need to file a separate issue?

**Comment by Xymanek** [comment]
> 
> 
> While we're at it, `GetAllowedClassForWeapon()` and `GetAllowedClassForArmor()` in `UIUtilities_Strategy` do not always have a return value.

This sounds like a warning fix, while this issue is about a new feature/non-trivial change - IMO those 2 shouldn't be done in the same PR
