### ISSUE TITLE
Allow mods to change class icons and class display names dynamicly

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#106]
In order to allow mods to change class name, summary and icon dynamcly i propose to add two functions in `XComGameState_Unit`

```
GetSoldierClassIcon()
GetSoldierClassDisplayName()
GetSoldierClassSummary()
```

and change all old references to the the soldier class template to the new functions.

The new functions trigger events that allow to override the default.

**Comment by Musashi1584** [comment]
Whats better  DLCInfo hook or event for this one?

**Comment by pledbrook** [comment]
Could this solution be extended to displayed ranks? The Long War 2 officer changes mean that soldiers can have two ranks and LW2 prefers to display the officer rank. The LW2 solution involved changing a lot of places in XComBase that fetched the soldier rank and replaced those with its own method.
