### ISSUE TITLE
The game consistently fails to load pointless `XComWeapon:UITextures`

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1062]
As far as I can tell, these textures on weapon archetypes are completely pointless, yet the game stubbornly tries to load them, complaining in the logs. It annoys me. 

The dev comment is:
```
var() array<Texture2D> UITextures<Tooltip="Any required UI textures, this makes a reference so the cooker will bring them in">;
```

The identical field exists in `XComUnitPawn.uc`. 

There are no references to `UITextures` anywhere in the code, besides declaration. Can something principal be done about them? Like setting the array to zero length right after an `XComWeapon` is `Spawn()`'ed. Or would it be too late at that point?

**Comment by Xymanek** [comment]
The entire point of that variable is to force the referenced textures to be loaded. By the time any script code gets access to the outer object (`XComWeapon` in this case), the loading would be already completed

**Comment by Iridar** [comment]
> The entire point of that variable is to force the referenced textures to be loaded. By the time any script code gets access to the outer object (`XComWeapon` in this case), the loading would be already completed

I was afraid of this. Thanks.
