### ISSUE TITLE
If Ranger class is disabled, no units can equip PCS

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1073]
**`XCGS_Unit::GetPCSRanks()`** is hardcoded to check for the Ranger soldier class template, so if it doesn't exist for whatever reason, the function will fail to work.

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/9b4109b85bea06fce95a2cc239f490807a1603ab/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc#L13595-L13623

Off the top of my head this should be fixed by making the function grab the soldier class template of the unit itself, but I haven't actually looked at what the function does just yet.

**Comment by robojumper** [comment]
This appears to be a holdover from a time where the PCS system was intended to be more comprehensive (like allowing multiple PCS to be equipped). See also Shadow Ops, which has a class that gets access to multiple PCS and provides a custom UI screen: https://github.com/RossM/ShadowOpsPerkPack/blob/master/ShadowOpsPerkPack/Src/ShadowOpsPerkPack/Classes/UIArmory_Implants_BO.uc

**Comment by Iridar** [comment]
Adding this to 1.23 so it's not forgotten about.

**Comment by Xymanek** [comment]
> this should be fixed by making the function grab the soldier class template of the unit itself

This will be technically a BC break, since the other class templates might've been "misconfigured" while working correctly in-game (since they were never checked/used).

Postponing for now until we can investigate this more

**Comment by Iridar** [comment]
> This will be technically a BC break, since the other class templates might've been "misconfigured" while working correctly in-game (since they were never checked/used).

Well, in the same vein it can be seen as a bug, as a soldier class that intentionally forbids use of PCS with its XComClassData.ini is not possible currently. 

I suppose without an actual use case for a soldier class like that in the pipeline, fixing this issue could cause more harm than good. I suggest leaving the issue open until such a use case is presented.
