### ISSUE TITLE
No "gained positive trait" UI

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#1081]
#85 enabled the positive traits functionality, but the UI still reports them as negative:

![image](https://user-images.githubusercontent.com/2865341/137698942-b2587684-60ad-4c30-bb3a-4063cc3d2c39.png)

![image](https://user-images.githubusercontent.com/2865341/137698952-4b71c90b-b167-46ec-8e09-3a3ea674dffd.png)

**Comment by BlackDog86** [comment]
XCOMGame.int has no quotes around m_strPositiveTrairAcquiredTitle - This may be a simple localisation issue.

**Comment by BlackDog86** [comment]
Preliminary code has now been written to support this PR - previews below. Code still needs to be sanitised & commented before release but I believe this looks much more consistent:
![Screenshot 2023-06-26 025932](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/assets/122568778/9bd967ac-9a9e-480e-b905-659d86db54ae)

![Screenshot 2023-06-26 025857](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/assets/122568778/1341e095-07b2-4728-abc6-fd5c73ee9b2b)

![Screenshot 2023-06-26 025820](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/assets/122568778/9248f034-05cf-4e9a-9742-abba9f91abe9)
