### ISSUE TITLE
Map plots for Avenger Defence missions not random

### ISSUE THREAD

**Issue by Dragon-32** [X2CommunityCore/X2WOTCCommunityHighlander#1082]
In my current campaign I have had 2 Avenger Defence missions, both were on the same plot ("plot_WLD_AvDef_Mount_EMM_01"). 

In my previous campaign I _think_ the single Avenger Defence mission I had was on the same plot (the Photobooth poster seems to back it up) but that mission was in August 2020.

The base game has four Avenger Defence plots:
Plot_WLD_AvDef_LgObj_Ravine
Plot_WLD_AvDef_LgObj_Stream
Plot_WLD_AvDef_MdObj_Ravine
Plot_WLD_AvDef_MdObj_Stream

I'm running two mods that add to that list, [Maps by Vozati [WotC Edition]](https://steamcommunity.com/sharedfiles/filedetails/?id=1132904326):
Plot_WLD_AvDef_Ravine_Voz_1C
Plot_WLD_AvDef_Large_Voz_1C

And [Even More Maps! [WOTC]](https://steamcommunity.com/sharedfiles/filedetails/?id=1139192059):
plot_WLD_AvDef_Suffer_EMM_01
plot_WLD_AvDef_Suffer_EMM_02
plot_WLD_AvDef_Flood_EMM_01
plot_WLD_AvDef_Mount_EMM_01

Assuming I'm right about my previous campaign then that's a 1 in 1000 chance of the same plot being used three times in a row, isn't it? Even if I'm wrong then it's a 1 in 100 for the same plot to be used for two missions, I think?

_I know. Someone complaining about RNG in an XCOM game..._

I posted the plot names in the order they appear in their respective XComPlots.ini (mod or base game)

My local EMM folder was created 7th August 2019, Vozati's 23rd October 2017.

So, I know [XCOM 2 load order](https://robojumper.github.io/too-real/load-order/) is weird but I think it's a bit too much of a coincidence that in all cases the plot chosen is the last in the list if the list is assembled in either Workshop ID or Subscription Date order.

I think there's enough here for someone to take a look at how plots are chosen for this mission type? See if it really is random.

Apologies if this is out of scope for the Highlander but I don't know enough about the game's innards to know.

It always seem to be the Xenoform biome too, maybe that's related...

**Comment by h4ilst0rm** [comment]
I was intrigued and can cofirm this seems to be the case.
Ran without highlander with just the 2 map mods listed here and their dependencies. Debug start campaign into `SpawnUfo true` to force the missions, each and every one of them on the `Plot_WLD_AvDef_MdObj_Stream` plot. Interestingly each of them in a different biome, also tried to trigger a second one on campaign 3 and got the same plot in a different biome once again.

**Comment by h4ilst0rm** [comment]
I did some more digging now with some additional logs here https://github.com/h4ilst0rm/X2WOTCCommunityHighlander/commit/b8097872921d2630020d3d6ca97f064b212a99dc#

It seems the plots used for avenger defense missions are not marked as used in the `plots` deck as their use count never changes. As a sanity check I first spawned a couple of ufo raids which do cycle their valid plots as expected with increasing use counts. Search for `LOGGERS` in the attached log. [Launch.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/7713657/Launch.log)
 
I believe problem stems from the `MarkPlotUsed()` being called only when the loading happens inside the skyranger `bShowDropshipInteriorWhileGeneratingMap`. Loading into avenger defence does not us the skyranger. 
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/097fff0ca20eaa9e5c1ec430fc1bec06f03edb43/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc#L2964-L2980

**Comment by Xymanek** [comment]
There is another place where plots and plot types are marked used:

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/553562b20fbee9e6b2de4dad1e6f33a45d60bb41/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComParcelManager.uc#L1779-L1787

**Comment by Tedster59** [comment]
Looking at the code on this, `MarkPlotUsed` uses CachedHistory to mark the plot as used, while `NativeGenerateMapPhase1` uses something directly stored in `BattleDataState`.  This appears to be set in `NativeGenerateMap` where it uses `History.GetSingleGameStateObjectForClass` to populate it instead.  The map itself appears set by 

`MAPS.AddStreamingMap(BattleDataState.MapData.PlotMapName);

For CAD/UFOs, do we know what generates these missions? and if it uses the same map picking code as normal missions?

**Comment by Tedster59** [comment]
Testing with an uncooked highlander, after adding logging to both locations, neither code path is being called when an Avenger Defense mission is created.

As confirmation, I added logging to the `BuildMission` in `XComGameState_MissionSite` to ensure I was doing things properly, and that logging is showing up in my logs.  Now to figure what code path is being called to generate the map.

**Comment by Tedster59** [comment]
More testing results:

When a Chosen Avenger Defense is created, the `GenerateMap` function in X2TacticalGameRulset's CreateTacticalGame state is being used and bSeamlessTravel is set to false, which means that `NativeGenerateMap` is not being called and the function calls `ParcelManager.GenerateMap` which comes after the native mark plot used calls in the native flow.

`[0050.02] TedHighlanderLog: GenerateMap in TacticalGameRuleset called
[0050.02] TedHighlanderLog: bSeamlessTraveled:  False`
