### ISSUE TITLE
MEC trooper move by itself after enemy turn

### ISSUE THREAD

**Issue by RaditzVisnar** [X2CommunityCore/X2WOTCCommunityHighlander#1088]
the mec trooper will move by itself after enemy turn, they move without any click, sometimes spent all the action point and sometimes just one.

**Comment by Iridar** [comment]
Why do you think this problem has anything to do with the Highlander?

**Comment by RaditzVisnar** [comment]
the previous version was fine...1.22.5 if i recall

**Comment by Iridar** [comment]
Changes between 1.22.5 and 1.22.7 were all centered around the projectile system. Absolutely nothing was done to units or anything that could even remotely cause such a problem. 

You have to demonstrate reproduction steps for this problem, and show that the problem can be reproduced with 1.22.7, but not with 1.22.5. 

You can download previous Highlander releases **[here](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/releases)**.

**Comment by RaditzVisnar** [comment]
thanx Iridar.
https://steamcommunity.com/sharedfiles/filedetails/?id=1452700934 << this the mod.
okay i will install the previous Highlander.
thanx for your reply.

**Comment by RaditzVisnar** [comment]
Hi Iridar,
SOLVED....it's not about highlander. i still using 1.22.7, dismissed the 2 of my mec troopers, unsubscribed, cleaned the config, and subscribed again, still playing till now and no problem.
thanx again
