### ISSUE TITLE
Pass Chosen abilities descriptions through XEXPAND

### ISSUE THREAD

**Issue by GafrieGithub** [X2CommunityCore/X2WOTCCommunityHighlander#1096]
Similar to what was done in #566 for sitreps description, can Chosen strengths/weakness descriptions get the same change? Namely, changing using AbilityTemplate.LocLongDescription to its expanded version. 
I believe it is needed in the following places:
UIChosenInfo - lines 150, 168;
UIChosenLevelUp - line 59;
UIChosenReveal - lines 55, 68.

**Comment by Iridar** [comment]
You are correct. Currently only the `UIChosenInfo` is handled. Reopening.

**Comment by BlackDog86** [comment]
What does this actually 'do' / allow in real terms?
