### ISSUE TITLE
Change default weapon mesh attachment point from `Root` bone

### ISSUE THREAD

**Issue by E3245** [X2CommunityCore/X2WOTCCommunityHighlander#1113]
By default, the game attaches weapon meshes to the Unit Pawn, specified by the `DefaultSocket` field in the `XComWeapon` archetype, when equipping any non-cosmetic weapons. We cannot however change the attachment point on the weapon mesh itself; it will always use the 'Root' bone by default.

To be clear, this changes which socket to use when the unit grips the weapon when equipping it instead of using the weapon meshes' `Root` bone, not where the weapon will attach to on the pawn (This is covered by `XComWeapon::DefaultSocket`).

**Comment by Iridar** [comment]
Are you sure it's the root bone, not just zero coordinates?

**Comment by E3245** [comment]
I thought I wanted this but I found other ways of doing this scenario without having to break the UnitPawn when building the visualizer.
