### ISSUE TITLE
XComGameStateUnit.GetUISummary_UnitStatusIcons returns blank image links

### ISSUE THREAD

**Issue by FearTheBunnies** [X2CommunityCore/X2WOTCCommunityHighlander#1120]
When rendering status icons onto the UIUnitFlag it calls against XComGameStateUnit.GetUISummary_UnitStatusIcons to pull the image links for the status to be displayed.  There is an issue with the call, though, and it returns blank strings for static effects such as Sustain which have the bDisplayInUI flag set to true but do NOT have a status icon to display.  The display for the flag literally just takes the first string it finds from the list, which means if a blank string is returned first it stops a valid icon from being displayed.

Original method:

```
simulated function array<string> GetUISummary_UnitStatusIcons()
{
...
	foreach AffectedByEffects(EffectRef)
	{
		EffectState = XComGameState_Effect(History.GetGameStateForObjectID(EffectRef.ObjectID));
		Persist = EffectState.GetX2Effect();
		if( Persist.bDisplayInUI && Persist.IsEffectCurrentlyRelevant(EffectState, self) )
		{
			List.AddItem(Persist.StatusIcon);
		}
	}
...
}
```

Suggested change:

```
simulated function array<string> GetUISummary_UnitStatusIcons()
{
...
	foreach AffectedByEffects(EffectRef)
	{
		EffectState = XComGameState_Effect(History.GetGameStateForObjectID(EffectRef.ObjectID));
		Persist = EffectState.GetX2Effect();
		if( Persist.bDisplayInUI && Persist.IsEffectCurrentlyRelevant(EffectState, self) && Persist.StatusIcon != "" )
		{
			List.AddItem(Persist.StatusIcon);
		}
	}
...
}
```

**Comment by Iridar** [comment]
Oh, so that's why status icons don't work sometimes. Good find.
