### ISSUE TITLE
Regression: reinforcement flares (and other effects) disappearing again

### ISSUE THREAD

**Issue by rcd47** [X2CommunityCore/X2WOTCCommunityHighlander#1123]
Reinforcement flares and similar effects (e.g. psi bomb bubble) are disappearing again. You can see an example of this about 28 minutes in [here](https://www.youtube.com/watch?v=JXiFxgx71ic). Looks like the hotfix-1.22 branch was never merged into master, so the last couple fixes aren't in 1.23.1.

**Comment by Iridar** [comment]
The fix was merged by this PR: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1076

**Comment by Iridar** [comment]
You're right, it appears this change was forgotten. We'll take it from here, thanks.
