### ISSUE TITLE
Allow Mods to disable Popups of New Resistance Order Cards being available

### ISSUE THREAD

**Issue by Grobobobo** [X2CommunityCore/X2WOTCCommunityHighlander#1126]
We Already have an option to disable opening the monthly resistance order screen, but when you for example finish a covert action that increases faction influence, you still get a pop-up regarding new resistance cards being available. This is annyoying because I'd rather not get reminded of a garbage mechanic like that existing.
Together with #368 It should be possible to make resistance orders completely disappear from the game.

**Comment by Iridar** [comment]
@Grobobobo closed the associated PR, but not the issue. Closing the issue now.
