### ISSUE TITLE
Skirmisher Interrupt bug gives reinforcements their turn too early

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1130]
> So I got a Major Skirmisher and wanted to try intercepting a reinforcement flare by standing him right on top of it and using this ability. When the enemies dropped in, he got a Retribution strike on each target as they Scamper.
> 
> Interrupt then activated and I shot the Overwatching Heavy MEC in the face. But then they all got another turn right afterwards! 2 flank shots later and my Skirmisher was bleeding out.
> 
> So apparently, Interrupt can cause enemy units to act right away when they arrive. I didn't see that coming. Battlelord might cause the same thing to happen now that I think about it.
> 
> Anyone else encounter something similar with this skill? I think it would be better as a cool down skill rather than a once-per-mission charge.

https://www.reddit.com/r/Xcom/comments/s7054t/interesting_find_using_interrupt/

**Comment by Xymanek** [comment]
Related: #36

**Comment by Xymanek** [comment]
Current code: 

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/69d40c887e4b69504c1783c71de62c1f80cbf70b/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2TacticalGameRuleset.uc#L4749-L4762

**Comment by Iridar** [comment]
Thank you. Looks like the bug is already fixed, and the person has reported it confirmed they were not using Highlander at the time - they were on XBOX. Closing the issue.
