### ISSUE TITLE
Claymore / Homing Mine environmental damage is inconsistent

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1131]
As I was doing some research for #989, I've noticed something weird.

Regular Claymore deals 10 env. damage, as specified in its destructible archetype, and it takes two to detonate a car. This is consistent with Frag Grenades, which also deal 10 env. damage and it also takes two frags to detonate a car.

Shrapnel Claymore deals 20 env. damage, and it takes just one to detonate a car. 

[Some code](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/69d40c887e4b69504c1783c71de62c1f80cbf70b/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Ability.uc#L1289-L1292) for getting environmental damage for targeting method preview uses a dev hack - instead of getting environmental damage from the destructible archetype, the code just grabs environmental damage for the Homing Mine, since it's supposedly the same as for Claymores anyway.

However, the configured env. damage for both shrapnel and regular Homing Mines is 10. 

So okay, I thought, apparently env. damage preview for the Shrapnel Claymore is incorrect, even though in-game I can't tell the difference between env. damage previews between regular and shrapnel Claymores. 

However, the weirdest part is that both regular and shrapnel Homing Mines detonate cars in just one go!

I have a hunch that Homing Mines apply their environmental damage twice. 

Pending further investigation.

**Comment by Iridar** [comment]
On a semi-related note, `X2AbilityMultiTarget_ClaymoreRadius` has a `ClaymoreEnvironmentalDamage` variable. It appears to be set as `10` for both regular and shrapnel Claymores, and it's hard to tell if it's even used for anything since the class is native'd.

**Comment by Iridar** [comment]
I tested and the value returned by `GetEnvironmentDamagePreview()` is actually important and used to highlight environmental objects if the damage is high enough to, well, damage them.

**Comment by Mitzruti** [comment]
homing mine has two damage effects - the second one should only be applied if the user has shrapnel and only does environmental damage.

unless the abilityproperty condition isn't failing properly because the car isn't a unit? (woo native functions)

**Comment by Iridar** [comment]
I put some logs into `X2Effect_ApplyWeaponDamage::ApplyEffectToWorld()`, and the "applying 10 env damage to world" log messages appear twice for both regular and shrapnel Homing Mine. One effect is `X2Effect_HomingMineDamage`, and one is `X2Effect_ApplyWeaponDamage`, which shouldn't even appear if the soldier doesn't have Shrapnel, yet it does. It appears the `X2Condition_AbilityProperty` indeed does not work as expected in this case.

**Comment by Iridar** [comment]
Made some logged tests with a custom condition, and the outcome confirms what should've been obvious without any testing: a `TargetCondition` on `X2Effect` cannot be used to determine whether the environmental damage should be applied or not, because world damage is applied without any particular target, so there's nothing to run a Target Condition against. This is a firaxis bug, and the whole logic regarding Homing Mine's environmental damage needs to be redone.
