### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by Yayabtw** [X2CommunityCore/X2WOTCCommunityHighlander#1137]
Hello Highlander devs ! I have an issue with this mod. My game crashes on the first loading screen before going to the main menu. My game is working without any mods and also when I have all my mods activated except Highlander.  

I did all the steps in the troubleshooting : 
- I reinstalled the game 
- I have the last version of the game (I have the same message as mentionned in the troubleshooting)
- I also refreshed all my INI files 
- I installed the Alien Hunters plugin because I have the DLC

Can you help me with that ?

**Comment by Iridar** [comment]
You did everything right and we let you down by not reaching out. I'm gonna be closing this issue, since it's obviously no longer relevant. The github is not as active as it could be, if somebody else experiences the similar problem, come by the discord.

https://discord.gg/ZytsZ93
