### ISSUE TITLE
Compatibility with Epic Games version of XCOM 2

### ISSUE THREAD

**Issue by hobbitmoore** [X2CommunityCore/X2WOTCCommunityHighlander#1142]
im trying to get into modding and a lot of the mods im using requires xcomcommunityhighlander along with dlc2communityhighlander but enabling those mods causes the game to crash on startup 
i attempted the Cookedpackage fix but i still ran into some problems as a error occurs with detected attempting load of package online subsystem Epic Store

**Comment by Iridar** [comment]
Currently Highlander is not compatible with the game version distributed through Epic Games Store.

**Comment by hobbitmoore** [comment]
Thanks for the info. I feel so dumb buying the epic store verison
