### ISSUE TITLE
DLCAppendSockets cannot add sockets to enemy pawns

### ISSUE THREAD

**Issue by radioparadice** [X2CommunityCore/X2WOTCCommunityHighlander#1144]
When the DLCAppendSockets() function is called for enemy pawns, whether newly spawned or on a loaded save game, they have not yet been assigned an ObjectID. Because of this, ``UnitState = XComGameState_Unit(`XCOMHISTORY.GetGameStateForObjectID(Pawn.ObjectID));`` is called with an ObjectID of 0 and returns None. It works for player units. Temporarily worked around by adding a CHEventListener with OnUnitBeginPlay and ELD_OnVisualizationBlockStarted and adding the socket creation to the event function, but this doesn't work on loaded saves.

 ```
[0020.44] ScriptLog: Script call stack:
	Function XComGame.XComAlienPawn:PostBeginPlay
	Function XComGame.XComUnitPawn:PostBeginPlay
	Function XComGame.XComUnitPawn:CreateDefaultAttachments
	Function XComGame.XComUnitPawn:DLCAppendSockets
	Function ExampleModName.X2DownloadableContentInfo_ExampleModName:DLCAppendSockets

**Comment by Iridar** [comment]
I can confirm the issue when loading saves. When starting a mission it seems `DLCAppendSockets()` doesn't get called for enemy pawns at all. The call is already located at the end of `PostBeginPlay()`, so I don't know where else would be a good place to put additional calls.

As a workaround, you can manually call `Pawn.Mesh.AppendSockets()` from `UpdateAnimations()` DLC hook, which also gives you the Unit State. I've confirmed it works both when starting a mission and when loading a save.

You could say the good place to call `DLCAppendSockets()` would be whenever `UpdateAnimations()` is called, or potentially from within `UpdateAnimations()`, but I don't really feel like making this change without a good reason. So I'm closing this for now.
