### ISSUE TITLE
Start up crash

### ISSUE THREAD

**Issue by TSOShadow** [X2CommunityCore/X2WOTCCommunityHighlander#1146]
To start fresh keep deleting Xcom2 and AML and all related material but even fresh. Launching just highlander is still crashing.

[Launch-backup-2022.06.11-21.53.30.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/8885045/Launch-backup-2022.06.11-21.53.30.log)
[Launch-backup-2022.06.11-21.46.53.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/8885046/Launch-backup-2022.06.11-21.46.53.log)
[Launch.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/8885047/Launch.log)

**Comment by Iridar** [comment]
Have you seen this? 
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting

**Comment by Iridar** [comment]
Author AWOL, closing.
