### ISSUE TITLE
Crash on startup; "WOTC not responding".

### ISSUE THREAD

**Issue by Quaraexen** [X2CommunityCore/X2WOTCCommunityHighlander#1147]
Hi all. This issue has been persistent, and all the fixes I have tried have yielded nothing, so I hope there's a fix for this.

WOTC Highlander always crashes on startup; giving me a "WOTC not responding" error. I just reinstalled XCOM 2 and decided to give LWOTC a shot (I typically play vanilla LW2,) and after checking three times my mods do not clash with WOTC, the game still crashes. Running ONLY LWOTC highlander + alien hunters highlander, the game still does not start, so I know it's a problem with the Highlander.

I have tried every fix I could find, including on the Highlander troubleshooting page - deleting .ini's (which simply stopped me from launching WOTC at all, I could launch vanilla, but I had to verify my cache to get the .ini's back so I could launch WOTC at all again even without any mods), copying CookedPCConsole files from Highlander to WOTC's CookedPCConsole (which brought up that there were already six files in it with the same name, so I chose 'replace', no dice,) unsubscribing/re-subscribing several times, and then I also do not have a Mods or Logs folder at all- why, I have no idea, but I simply lack those folders entirely in both vanilla XCOM 2 and WOTC's directories, so fixes with these involved have not been applicable.

Still, it simply does not launch. Highlander's the only thing causing problems. I use AML (even tried running as admin) and again, checked to make sure all my mods are WOTC compatible and should work with LWOTC. I have also tried using the BETA versions of the Highlander after unsubscribing from the regular one; still crashes as the regular one does. I'm at a loss as to what to do.

**Comment by Dragon-32** [comment]
The fact the game doesn't re-create your user configs on start-up (it's supposed to) implies there's something stopping it like overzealous AV or maybe permissions on that directory. Have you tried creating an exception in your AV for either the XCOM2 executable or that directory?

If that doesn't work then post a copy of your launch.log and I'll have a look. 90% of the time it doesn't have anything useful in, mind.

**Comment by Iridar** [comment]
Author AWOL, closing.
