### ISSUE TITLE
Create new event listener for overriding LocalPlayerState in XComTacticalSoundManager#EvaluateTacticalMusicState()

### ISSUE THREAD

**Issue by FearTheBunnies** [X2CommunityCore/X2WOTCCommunityHighlander#1153]
Steam discussion that spawned this:  https://steamcommunity.com/workshop/filedetails/discussion/2862951793/3473986888164155935/#c6382186451027812961

A new override event needs to be created for assignment of the LocalPlayerState in XComTacticalSoundManager#EvaluateTacticalMusicState() so that Direct Control can be made compatible with soundtrack reworks.

**Comment by Iridar** [comment]
#1154 does not close this issue, as it turns out. Since EventData isn't an `out` argument, it can't be replaced with a reference to a different object. To address this, EventData must be replaced with an XComLWTuple to hold the reference to the object instead.

**Comment by Iridar** [comment]
This was fixed in #1263, closing.
