### ISSUE TITLE
Quality of life improvements

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1164]
CHL could be used to add alternatives to some of the more annoying functions, such as `EventManager.RegisterForEvent()` and `PersistentEffect.SetDisplayInfo()`, so that instead of a function with a huge number of arguments, they would take a struct, for example:

```cs
Listener = EmptyListener;
Listener.Owner = EffectState;
Listener.Event = 'UnitGroupTurnBegun';
EventManager.RegisterForEvent(Listener);
```

and add some more shortcuts, such as ``XCOMHQ.GetSquad()`.

**Comment by Xymanek** [comment]
One issue I have with adding such helpers to CHL is that they don't need to be there (each mod can implement them itself) and adding them to CHL forces the BC requirements. And CHL is already a project with high maintenance overhead (especially compared to available/active effort on it).

Also, `SetDisplayInfo` is just a shortcut, you can write to the underlying fields directly (none of them are private/protected):
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/d39a2d4f1a6a420a9c55a1d5d0e420966ec2840a/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2Effect_Persistent.uc#L106-L115

**Comment by Iridar** [comment]
Fair enough, closing.
