### ISSUE TITLE
Add additional inventory slot types and facilitate implementing them

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#118]
Currently, Inventory Slots are limited to this list:

```
enum EInventorySlot
{
	eInvSlot_Unknown,
	eInvSlot_Armor,
	eInvSlot_PrimaryWeapon,
	eInvSlot_SecondaryWeapon,
	eInvSlot_HeavyWeapon,
	eInvSlot_Utility,
	eInvSlot_Mission,
	eInvSlot_Backpack,
	eInvSlot_Loot,
	eInvSlot_GrenadePocket,
	eInvSlot_CombatSim,
	eInvSlot_AmmoPocket,
        eInvSlot_TertiaryWeapon,
        // ...
	eInvSlot_SeptenaryWeapon,
};
```

Where Mission, Backpack, Loot, Tertiary-Septernary are not available to the user. Adding a mechanism that allows mods to add more slots would certainly add to the moddability, but would also be a rather tricky effort.

### 1. This Enum

Enums are bytes (0-255), where 255 is the implicit `longestCommonPrefix_MAX` value. They are compiled directly into the byte code as constant tokens, and not sensitive to any changes.

Because of the way the Game State and Template system works, it is necessary that any given item type NEVER changes its corresponding slot byte value, be it over the course of the campaign, across different save files, across different machines, independent of other mods being present or not, ...

As such, adding a new slot requires adding a new enum value that does not conflict with any other mods. 
Unfortunately (as far as I know) Byte Properties linked to an enum are serialized using their Enum-Name, setting it to None when saving and _MAX when loading if the entry doesn't exist. This requires us to add new entries to the Highlander.

We have 256 - 1 - 17 = 238 free slots, so that should not be a problem if we are minimally considerate about what types of slots we add.

#### Native Code

This enum is exported to native code, which, in theory, enables native code to use it (It certainly is used in `GetPrimaryWeapon()` and `GetSecondaryWeapon()` in XComGameState_Unit). This exported enum is synchronized with the Script enum, but they are not linked in any way. A major assumption of our strategy to add new slots is that native code DOES NOT iterate over the slots enum (the implicit `_MAX` is also exported). In the base game UnrealScript, only debug code does this, and it will pick up our changes. Generally, there isn't a reason native code might do that, since most of the Item access code iterates over the actual equipped items, but adding it here as a potential pitfall warning. A definitive answer can only be obtained by looking at native code (or asking someone who can do that).

### 2. Implementation

When we have more slots, we definitely don't want to add implementations for all of them. Instead, we should create a special type of template that provides the implementation for those. This template would provide information on whether a unit has this slot (TBD: allow multi-item slots?), what its name is, and any special behavior when equipping and unequipping, custom rules for those functions, whether this slot can take items from other slots (akin to Ammo & Grenade Pockets), and so on. We would also need an interface that facilitates implementing the UI code required to make more slots work.

**Comment by Drglord52** [comment]
I would like if possible a slot to be added for my armor i made for the doom soldier class of my mod. I have already setup the code and tried it with other enum slots. The name could be Praetorslot.
Thank you
