### ISSUE TITLE
Port `GetItemRange` Event from X2CommunityHighlander

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#119]
Straight port of [Issue #90 ](https://github.com/X2CommunityCore/X2CommunityHighlander/issues/90)of the X2CommunityHighlander.

`Allow mods to override range returned, otherwise perform native behaviour, which has been extracted out of native method.`

**Comment by MalucoMarinero** [comment]
@Musashi1584 , @robojumper - are we certain the native function we're overwriting hasn't changed from X2 -> WOTC, given it was probably informed by the LW teams correspondence during development.

**Comment by Musashi1584** [comment]
We cant be sure, but i havent noticed any changes to the wotc behavior.
