### ISSUE TITLE
UIArmory.uc does not stop sounds or remove cosmetic units when removing pawns.

### ISSUE THREAD

**Issue by Tedster59** [X2CommunityCore/X2WOTCCommunityHighlander#1192]
Pulling this conversation out of DMs and Iridar's discord.

Line 331 of UIArmory.uc:

```
simulated function ReleasePawn(optional bool bForce)
{
    Movie.Pres.GetUIPawnMgr().ReleasePawn(self, UnitReference.ObjectID, bForce);
    ActorPawn = none;
}
```

This function does not remove sounds, leading to persistent sounds being left behind, that are only removed by a save and reload.  This is most annoying when using something such as Kiruka's Playable Aliens for LWoTC, where the Archon's jet sound effect will be stuck in your squad select screen until you save/reload.

@RustyDios suggests updating the function to the below:

```
simulated function ReleasePawn(optional bool bForce)
{
    local XComUnitPawn CosmeticPawn;
    
    //destroy any gremlins
    CosmeticPawn = Movie.Pres.GetUIPawnMgr().GetCosmeticPawn(eInvSlot_SecondaryWeapon, UnitReference.ObjectID);
    if (CosmeticPawn != none)
    {    
        CosmeticPawn.StopSounds();
        Movie.Pres.GetUIPawnMgr().ReleasePawn(self, CosmeticPawn.ObjectID, bForce);
        CosmeticPawn = none;
    }

    ActorPawn.StopSounds();
    Movie.Pres.GetUIPawnMgr().ReleasePawn(self, UnitReference.ObjectID, bForce);
    ActorPawn = none;
}
```

**Comment by RustyDios** [comment]
This should also fix persistent Gremlins/Bits (cosmetic units) from remaining too. The suggested fix code is adapted from working code in the UFOPedia and Bestiary mod, that was experiencing extremely similar issues.

**Comment by Iridar** [comment]
I think the better solution here would be adding `Pawn.StopSounds();` into `ReleasePawn()` itself and other neighboring functions, or further down the line.

**Comment by Tedster59** [comment]
I want to say this is exactly what Rusty is proposing, update `ReleasePawn()` to contain `Pawn.StopSounds()` as well as going beyond by adding additional code to properly remove associated cosmetic units, to fix a related bug, unless I'm misreading your solution.

**Comment by Iridar** [comment]
Sorry, I meant the `ReleasePawn()` in the UIPawnMgr, the one that gets called here: `Movie.Pres.GetUIPawnMgr().ReleasePawn(self, CosmeticPawn.ObjectID, bForce);`.

**Comment by Iridar** [comment]
#1108 Somewhat related
