### ISSUE TITLE
Ranger's Slash action point cost does not use bMoveCost

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1221]
As the result, if Slash is made non-turn-ending by any effect or ability (which normally cannot happen in vanilla), it will always cost only one action point, regardless of travel distance.

**Comment by faanlez** [comment]
Relatedly, changing that would affect Skirmishers as well. It may or may not be intentional balance.

**Comment by Iridar** [comment]
On second thought, since this behavior isn't possible in vanilla, better leave fixing this to whatever mod that enables it. AddSwordSlice() is used a lot, including by mods, wouldn't want to cause collateral damage.
