### ISSUE TITLE
CHL Hook for UI 'Number of Kills'

### ISSUE THREAD

**Issue by BlackDog86** [X2CommunityCore/X2WOTCCommunityHighlander#1231]
Issue #562 includes a hook for Over-riding the total number of kills on a unit in XCGS_Unit GetTotalNumKills. 

However, various places in the UI (e.g. UIPersonnel) use the function GetNumKills in XCGS_Unit (Which returns KilledUnits.length) instead. 

It may be useful to modders to be able to over-ride both the number of kills for the purposes of XP gain and/or the number of kills displayed in the UI. Propose to add an additional hook to GetNumKills which works in a similar way.

**Comment by Iridar** [comment]
Do you have an actual use case for it?

**Comment by Iridar** [comment]
Closed with OP's blessing due to lack of relevancy.
