### ISSUE TITLE
Missing alien ability icons

### ISSUE THREAD

**Issue by BlackDog86** [X2CommunityCore/X2WOTCCommunityHighlander#1255]
The Lost melee attack is set to use this icon:

```
static function X2DataTemplate CreateLostAttack()
{
    local X2AbilityTemplate Template;
    local X2AbilityCost_ActionPoints ActionPointCost;
    local X2Effect_ApplyWeaponDamage PhysicalDamageEffect;

    `CREATE_X2ABILITY_TEMPLATE(Template, 'LostAttack');
    Template.IconImage = "img:///UILibrary_PerkIcons.UIPerk_escape";
```

Which doesn't exist. Similarly the Viper King frost blast and all alien ruler 'escape' abilities don't have icons either. Not strictly a gameplay issue but the abilities show up as "?" in YAF1 and other similar mods which show the abilities on a unit. I think there are a couple of these on the Chosen which can be seen in the bestiary mod as well.

Debatable whether these should be fixed in CHL or not but there are surely existing base-game icons that could be used in most cases (img:///UILibrary_PerkIcons.UIPerk_muton_punch for lost melee, img:///UILibrary_PerkIcons.UIPerk_psychic / img:///ILibrary_PerkIcons.UIPerk_adventpsiwitch_dimensionrift for escape, some kind of explosion for frost blast, maybe biggestbooms or something?

**Comment by Iridar** [comment]
It's a low priority, but valid for a CHL fix.

**Comment by BlackDog86** [comment]
Berserker king 'quake' and hunter 'farsight' also have the same problem

**Comment by Dragon-32** [comment]
Not sure if this really helps but I saw this page on Reddit that mentions some unused perk icons in the game
[Everything that can be verified for Fourth Chosen](https://old.reddit.com/r/Xcom/comments/ajlcp1/everything_that_can_be_verified_for_fourth_chosen/)

Like _maybe_ UIPerk_squadsightprotocol.tga could work for Farsight?

**Comment by Iridar** [comment]
I'd welcome PR with some screenshots on suggested icons. It doesn't have to cover all icons in one go.

**Comment by BlackDog86** [comment]
Will do!

**Comment by BlackDog86** [comment]
I did_ some more investigation on this today - It turns out that aside from the "Ruler Escape" and "Lost Melee" abilities, all of the other abilities had proper icons anyway, but the game was either referenceing the wrong path, or had a duplicated template.iconimage on the ability template. Commit & images will follow in a few minutes :)

**Comment by BlackDog86** [comment]
![image](https://github.com/user-attachments/assets/d6d7236d-cca3-4a45-89a6-48ac50cfb9cd)
![image](https://github.com/user-attachments/assets/b0f18e96-6c7b-44fc-a9c0-201027325d4c)
![image](https://github.com/user-attachments/assets/b0055555-f2e3-4a3d-a044-2c885ed8233c)

**Comment by BlackDog86** [comment]
![image](https://github.com/user-attachments/assets/8a5e2966-54ff-46c7-95cf-253840d66bb0)
