### ISSUE TITLE
Inconsistency between bIgnoreArmor and high Pierce values

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1281]
# The Problem

`X2Effect_ApplyWeaponDamage` has `var bool bIgnoreArmor;`, which allows that effect to ignore all armor on the target.

However, damage preview on the unit flag does not respect that, as determined by `UIUnitFlagManager::SetAbilityDamagePreview()`:

```cs
simulated function SetAbilityDamagePreview(UIUnitFlag kFlag, XComGameState_Ability AbilityState, StateObjectReference TargetObject)
{
[...]
	AbilityState.GetDamagePreview(TargetObject, MinDamageValue, MaxDamageValue, AllowedShield);
[...]
	kFlag.SetArmorPointsPreview(MaxDamageValue.Shred, MaxDamageValue.Pierce);
}
```
Some abilities that are meant to ignore armor instead just set `Pierce = 999` on their damage value, and that does visualize on the flag's damage preview correctly.

# Solution?

Abilities can potentially apply multiple effects, some of which might ignore armor, some might not, so that's a bit problematic. This means this has to be fixed at the effect level. 

A good place seems `X2Effect_ApplyWeaponDamage::GetDamagePreview()`, where we can do:
```cs
if (bIgnoreArmor)
{
    MinDamagePreview.Pierce = MaxInt;
    MaxDamagePreview.Pierce = MaxInt;
}
```

However, that can become problematic if some mod decides later to actually display the exact pierce number somewhere. We could potentially gate this fix behind a bool that's off by default.

**Comment by Iridar** [comment]
I decided not to gate this behind any bool checks. I count this as a genuine bug that needs to be fixed universally, because there are abilities - for example, Soul Fire and Insanity w/ Schism - that have damage that ignores armor, but it doesn't show on the damage preview, confusing the player.

If this actually becomes problematic for some mod later, they can always compare `Pierce` to `MaxInt` and act accordingly.

**Comment by RustyDios** [comment]
Unit Flag Extended has a config option to display pierce from the main weapon. I think I'll need to check how I actually set it up (pretty sure I was directly getting the WeaponDamageValue) just to see if this conflicts. I'll fix it on my end if it does, but I'm just noting this here as a mod that may already "display the exact pierce number somewhere"

**Comment by Iridar** [comment]
The way I set up the PR, it shouldn't have any effect on it, because the PR changes damage preview reported by an effect on an ability you're targeting with, while you presumably look at the weapon template.

**Comment by RustyDios** [comment]
Yes. I'm checking weapon templates. All good here then :)
