### ISSUE TITLE
Add hook to allow adjusting UFO interception time

### ISSUE THREAD

**Issue by Tedster59** [X2CommunityCore/X2WOTCCommunityHighlander#1316]
the LW2 highlander and X2CommunityHighlander featured a `PostUFOSetInterceptionTime` event that allowed LW2 to adjust the UFO interception time since LW2 doesn't use the calendar system.  It's line 115 in [XComGameState_UFO](https://github.com/X2CommunityCore/X2CommunityHighlander/blob/1d3a290f9f38d610dcc7bb1bef95f78df335a0d8/X2CommunityHighlander/Src/XComGame/Classes/XComGameState_UFO.uc#L115C27-L115C53) in the original Highlander.  Somehow this was missed in the WOTC Highlander, and it will be useful for LWoTC.

**Comment by Iridar** [comment]
Closing as this was fixed by #1317

@Tedster59 in the future, please start PR description with `Fixes #<issuenumber>`, that will allow the Issue to close automatically when the PR is merged.
