### ISSUE TITLE
Abilities missing ShotHUDPriority 

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1324]
Almost all Templar abilities don't have a ShotHUDPriority set. Haven't checked other faction heroes and vanilla classes yet, worth investigating.

**Comment by RustyDios** [comment]
worth noting that in XCGS_Ability UpdateAbilityAvailability function:
```
// since we can't put class constants in default properties, catch < 0 (invalid) shot hud priorities here and stick them in
// the default sort location
Action.ShotHUDPriority = m_Template.ShotHUDPriority >= 0 ? m_Template.ShotHUDPriority : class'UIUtilities_Tactical'.const.UNSPECIFIED_PRIORITY;
```
and the defaultproperties of X2AbilityTemplate set the SHOTHUDPriority as -1

**Comment by Iridar** [comment]
> I'm not sure how many people have a mental model of the abilities being in rank order. imo it would be unnecessarily disruptive to rearrange icons that people may be very accustomed to

(c) SwfDelicious
