### ISSUE TITLE
Proxymity mines throw and launch damage on impact

### ISSUE THREAD

**Issue by Johnny0exe** [X2CommunityCore/X2WOTCCommunityHighlander#1328]
I wonder is it only me who have this problem:
Under some circumstances throwing and launching proximity mines (and their upgrades from Superior explosives mk2 and mk3)  dealing damage and applying various effects from perks and weapon upgrades, i.e. damage from "Boosted cores", "VolatileMix", "NeedleGrenades", "HeatWarheads", shred, armor ignore and other effects from weapon upgrades from TeslaRage loot mod and Grimy's loot mod. Not on mine detonation but on first impact.
Is there a way to fully exclude throwing and lauching proxymity mines from this effects application?

**Comment by Iridar** [comment]
Proximity Mine does not apply extra damage from Volatile Mix when using just the Highlander. Other items/abilities are added by other mods and have nothing to do with Highlander. You're once again asking in the wrong place.
