### ISSUE TITLE
2nd tier alien hunter weapons not showing up on the trophy wall

### ISSUE THREAD

**Issue by Larryturbo** [X2CommunityCore/X2WOTCCommunityHighlander#1358]
At script XComGameState_HuntersLodgeManager.uc.
The second and third tier versions of the alien hunter weapons show up independently. Meaning that if you skip the second tier and make the beam versions you only get the 1st and 3rd tiers on the wall.

**Comment by Dragon-32** [comment]
This bugs me every time

**Comment by Iridar** [comment]
Closing, see associated issue for reasoning.
