### ISSUE TITLE
ChosenBrutal restores will

### ISSUE THREAD

**Issue by boundir** [X2CommunityCore/X2WOTCCommunityHighlander#1389]
Brutal uses `GetBaseStat()` instead of `GetCurrentStat()`. The result in most occasions is a will gain.

Affected methods:
`X2Effect_Brutal::OnEffectAdded`
`X2Effect_Brutal::AddX2ActionsForVisualization`

**Comment by BlackDog86** [comment]
Will need to split the commit in two if adding new files - one adding the file and the other documenting the changes.
