### ISSUE TITLE
Update XComPerkContent and X2Action_AbilityPerkDurationEnd to support removing more than one perk effect per effectstate

### ISSUE THREAD

**Issue by shiremct** [X2CommunityCore/X2WOTCCommunityHighlander#142]
Currently X2Action_AbilityPerkDurationEnd will only remove one perk effect per effectstate when the duration expires (calls GetAssociatedDurationPerkInstance() from XComPerkContent which returns only the first instance it finds).

Needed for effects that have multiple associated passives with visual perk effects.

**Comment by Iridar** [comment]
@shiremct is this issue still relevant?

**Comment by Xymanek** [comment]
Looks like the change was implemented but not PRd 🤔

**Comment by shiremct** [comment]
I don't see the change implemented in the workshop stable or CI beta highlander? The issue is still there, but guess it hasn't come up as an issue for 2 years, so dunno if it's still needed or not.

It originated from attempting to put different associated passive effects on the LW2 Holotargeter's holotarget effects to indicate if it had extra crit, extra damage, and/or extra duration enhancements active.

I think this can also come up if multiple instances of an effect that allows duplication are applied, but I'm not an expert on the visual/effects realm by any stretch.

**Comment by Xymanek** [comment]
When I said "implemented" i meant the commit seen above (abb29d0) but that commit never ended up in a PR opened against this repo

**Comment by shiremct** [comment]
Ah, sorry, my Git lingo is obviously not strong. I never pushed a PR, because the code itself was never tested. Running uncooked was broken when I did this. Was that ever fixed, btw? Been a long time since I worked on a HL issue.

**Comment by Iridar** [comment]
Given that nothing has happened with this Issue for six years, I think it's safe to close. Free to reopen if necessary.
