### ISSUE TITLE
Add hook to modify strategy start state

### ISSUE THREAD

**Issue by rcd47** [X2CommunityCore/X2WOTCCommunityHighlander#1425]
X2DLC provides hooks to modify the start state when transitioning strategy -> tactical (OnPreMission) and tactical -> tactical (ModifyTacticalTransferStartState) but not tactical -> strategy. This hook should be added.

**Comment by Iridar** [comment]
Normally we just use OnPostMission() or OnExitPostMissionSequence() for this. Is this hook meaningfully different enough to be actually necessary?

**Comment by rcd47** [comment]
Yes. My goal is to dump the history before each transition. OnPostMission() and OnExitPostMissionSequence() are too late, since they occur after the transition back to strategy, and therefore the history has already been truncated.

The eventual goal is to be able to automatically build something like https://xcom-databank.games/ by analyzing the entire history of a campaign. I've been working on this sporadically for five years, and there's still a long way to go. But I have successfully reverse engineered the relevant file formats, and I'm about to make the first release of the file analysis tool I built: https://github.com/rcd47/xcom-2-data.

**Comment by Iridar** [comment]
That's pretty cool. Alright.

**Comment by Tedster59** [comment]
Oh wow.  I wonder if that kind of parsing can help us analyze saves that won't load or other related issues.

**Comment by rcd47** [comment]
It very well might. I've never had such issues, but I know DerAva and Christopher Odd have both been having problems in their current campaigns with bloated strategy saves that don't load. Assuming that the problem is something to do with _loading_ the save, and not something wrong with _creating_ the save, X2DE should be able to parse it.

**Comment by Tedster59** [comment]
The current hunch is that the save file overflows a "max size" for a section of data and then fails on fully importing it.  This behavior was confirmed with the "crashes with too large modlist" issue is related to a metadata section of the save file becoming longer than 65535 characters, so it likely affects other things.  I'd want to see more details and see if there's a better way to "compress" history somehow, especially in tactical
