### ISSUE TITLE
X2Effect_Blind does not have a Damage Type

### ISSUE THREAD

**Issue by VAqS444** [X2CommunityCore/X2WOTCCommunityHighlander#1428]
Damage Types are used by X2Effect_DamageImmunity to easily grant immunities based on the damage type assigned to the effect.
For example: X2Effect_Burning uses "Fire' damage type, whereas X2Effect_Stunned uses "stun" damage type.

However, X2Effect_Blind (used e.g. by the Assassin's grenade) does not have any kind of Damage Type assigned.

Adding the new damage type to the blind effect would likely allow other mods to convieniently implement abilities with that effect, along with the **abilities that grant immunity to blindness.**

Based on testing, adding the new Damage Type to the DefaultProperties in X2Effect_Blind is enough for X2Effect_DamageImmunity to grant immunities:
```
DefaultProperties
{
	DamageTypes(0) = "Blind" //Issue #1428
	bIsImpairing=true
	DuplicateResponse=eDupe_Refresh
}
```

**Comment by VAqS444** [comment]
I apologize if it's a mess, I'm still learning GitHub/Sourcetree.

**Comment by Iridar** [comment]
To make a Highlander submission the proper way, here's what you need to do: 

1) Add the main Highlander repository as "upstream" remote for your local repository. 

To do so, do Repository -> Add Remote -> Add, then set "remote name" to `upstream` and "URL / Path" to `https://github.com/X2CommunityCore/X2WOTCCommunityHighlander.git`

Then click "Ok". 

You should see it appear in the list of Remotes in the lower left part of the UI. Right click it and select "Fetch", and you should see a list of branches. 

2) Checkout the "master" branch by doubleclicking on it.

This will switch your active local "master" branch to active. 

3) Click "Pull" to update your local master branch to the latest version of the remote repository.

4) Create a feature branch. Click the "branch" button an enter the new branch name. Traditionally, it is formed as "issue_number-brief_description", e.g. `1428-blind-effect-damage-type`

5) Now you can work with the mod project. Make the necessary changes. If the submission requires adding new files, then you must do it the following way:

1. Add new files to the repository via Modbuddy.
2. Exit modbuddy, saving the project. This will update the .x2proj file that controls which files are the part of the mod project, kinda.
3. Make a commit in source tree, where you mention which files are being added. E.g. `Add X2Effect_Blind to source`
4. Then you can resume work with the mod project, but make sure that all your following changes are in one commit. So you have two commits, one where new files are being added, and one where changes to them are being made. 

If the submission doesn't require adding new files, then it doesn't matter, you can go crazy with commits, they can all be squashed to one commit during the merging process, if your submission is approved.

6) Once you're done with all your changes, push your changes to your repository, and then via GitHub interface here make a Pull Request from your feature branch to main repository's master branch, and wait for it to be reviewed by maintainers like myself.

Feel free to ask if you require additional help.
