### ISSUE TITLE
Provide additional event hooks to X2TacticalGameRuleset to allow for modders to modify how turns are executed

### ISSUE THREAD

**Issue by MalucoMarinero** [X2CommunityCore/X2WOTCCommunityHighlander#144]
Using InitiativeOrder as a concept it seems possible to create something like RecoveryTurnSystem without the dramatic ClassOverrides of the original X2 Mod.

Likely required hooks are one at the start of `NextInitiativeGroup`, and one timed for stripping action points at the start of conventional turns, however this will mature in a branch until a pull request is ready.

**Comment by Iridar** [comment]
Closing the issue due to lack follow up, feel free to reopen if necessary.
