### ISSUE TITLE
Every weapon appearing for each soldier, causes hangup when selecting weapon.

### ISSUE THREAD

**Issue by kjlevitz** [X2CommunityCore/X2WOTCCommunityHighlander#147]
Environment:
This happened after the 25th on a save game that was working with the community manager and further tested with a new game started only with community highlander enabled. Please note that the fresh save was also done with a fresh install and all DLC.

Problem:
Every time you select a soldier's loadout you are presented with weapons from every class. The class restriction text has also been removed and no longer says, "Reaper Only." If you select an invalid weapon for your class it will cause the selection to freeze and it will not allow you to select other weapons. You have to back out and try again.

**Comment by robojumper** [comment]
This is caused by a bugfix in the latest update that causes unexpected behavior when used with the "Psi Overhaul" mod. That mod will need to be updated, we have notified the author.

**Comment by kjlevitz** [comment]
Thank you for the lightning fast reply. It appears that disabling the Psi Overhaul wasn't enough. I had to unsubscribe from it completely. Everything is working as intended now, thanks.
