### ISSUE TITLE
Highlander build doesn't work

### ISSUE THREAD

**Issue by Danice123** [X2CommunityCore/X2WOTCCommunityHighlander#151]
[Launch.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/1628107/Launch.log)

From a Cooked build of HL

[Launch-backup-2018.01.13-00.36.53.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/1628108/Launch-backup-2018.01.13-00.36.53.log)

Running -nofreeseekloading

**Comment by robojumper** [comment]
The log files make it obvious that the cooking process didn't work correctly ("data corruption" indicates that the cooked highlander isn't in sync with what the cooked game has), but without any additional info, we can't help more than directing you to the instructions in the readme.

**Comment by Danice123** [comment]
I have done everything twice over now
Unsubscribed from all mods'
The key thing is that I can't run noseekfreeloading even without mods. Obviously I am missing something. But there isn't anything to miss?
I have the game freshly installed. I have the dev kit freshly installed
I have full content
symlinks are correct

**Comment by Musashi1584** [comment]
`-noseekfreeloading` seem indeed be broken. Possibly since the latest patch.

**Comment by Danice123** [comment]
Cooking without -tfcsuffix parameter fixes the cook
