### ISSUE TITLE
Let part pack sliders in UIOptionsPCScreen be scrollable

### ISSUE THREAD

**Issue by RealityMachina** [X2CommunityCore/X2WOTCCommunityHighlander#160]
Currently, the game just renders the first 11 valid part packs it can find with the recent highlander additions.

Fine for relatively small time mod users, but depending on mod pack (some may include "multiple" DLC packs) and # of mods installed, this may be very insufficient to fully customizing one's experience.

Hopefully one of the people actually competent with UI related things will be able to fix this for the rest of us. :v

**Comment by MalucoMarinero** [comment]
UIList actually has scrolling behaviour built in so it may very well be as easy as updating line number 211 
```
const NUM_LISTITEMS = 16;
```
to something higher. That's what they use to limit the number of possible options on a given tab to 16. Whether or not something in the flash disables the scrolling remains to be seen but it could work out pretty simply.
