### ISSUE TITLE
Unprotect SoldierRanks in X2SoldierClassTemplate

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#161]
So mods can change the ability ranks OnPostTemplatesCreated.

**Comment by LeaderEnemyBoss** [comment]
This should actually be possible already, also its a bit fiddly. See my LW2 Psi mod http://steamcommunity.com/sharedfiles/filedetails/?id=888340114

**Comment by Musashi1584** [comment]
It was brough to my attention that you already can access protected members by static methods in subclasses (which is makes no sense but whatever) so i am closing this.
