### ISSUE TITLE
The "surgical" SitRep is supposed to recude podsizes to two, but it doesnt work. Should the HL fix this

### ISSUE THREAD

**Issue by LeaderEnemyBoss** [X2CommunityCore/X2WOTCCommunityHighlander#162]
I open this issue to hear the opinion of other contributors. The "surgical" Sitrep reduces Squad size to 3 but in turn is supposed to recude alert level and pod sizes. At least the pod size reduction does not seem to work at all. Since the newest HL-Version supports Encounter modification I propose we include a fix for this, but as a new contributor I'm unsure if this is still considered to be in the scope of the HL (its a fix, but one that alters game balance in a relevant way).

I've heard arguments that state "its fine the way it is now, the game gets to easy anyway". With a good squad and some luck (e.g. getting an additional unit through orders) surgical is doable in its current state, but sometimes its just unwinnable or only the main objective is achievable with some reload cheese (since vanilla has no robust stealth system). We could ofcourse also make the fix optional.

**Comment by MrNiceUK** [comment]
Huh, always felt like "surgical" SitRep didn't actually reduce Advent forces, numbers or "force level" etc., like the description claimed! To me the fact that is isn't following the UI description makes it different to just finding out some commented out code or whatever. Is the details of how it's supposed to affect Advent in the code, but broken in some way, or would the details have to be hade up from whole cloth?

**Comment by LeaderEnemyBoss** [comment]
Sry for the late reply. The details how it should work is "known" as the effect that is supposed to weaken enemies is literally called "PodSizeDecreaseToTwoEffect". The Code of that Effect also indicates that this is exactly what it should do: reduce podsizes to two. The "Podsize reduction code" itself is hidden from modders, so we dont know exactly why its not working. However a Highlander fix should be very possible to achieve.

I'm currently busy with my own mod, but I will probably conjure up a fix next week or so.

**Comment by robojumper** [comment]
This was mentioned as a use-case for the hook in #136, can that be used?

**Comment by LeaderEnemyBoss** [comment]
Oh yeah, that was my intended way to do it. Simple Check, if the sitrep is present, then shrink all pods down to 2. No new hooks needed.

**Comment by LeaderEnemyBoss** [comment]
This issue can be closed, I released a seperate mod with the fix. As I understand only fixes that are awkward to implement in seperate mods should go into the highlander (like gamestate overrides).
