### ISSUE TITLE
Add hooks to X2TargetingMethod_EvacZone

### ISSUE THREAD

**Issue by Danice123** [X2CommunityCore/X2WOTCCommunityHighlander#165]
Two changes:

Change class variables to protected to allow some hooks

Add some LW2 validation code for evac area choice to avoid evac areas outside of map boundaries

**Comment by Iridar** [comment]
> Change class variables to protected to allow some hooks

This was addressed by #574.

> Add some LW2 validation code for evac area choice to avoid evac areas outside of map boundaries

Is this actually an issue? I don't think I've ever experienced evac being placed out of bounds.
