### ISSUE TITLE
Massive framerate hit

### ISSUE THREAD

**Issue by CrazyOatmeal** [X2CommunityCore/X2WOTCCommunityHighlander#166]
With only X2CH WOTC enabled and no other mods, my framerate drops from 40 to 10, during missions and in the geoscape.

**Comment by LeaderEnemyBoss** [comment]
What do you mean with "no other mods enabled", if you mean just disabling them in the launcher (not aml): the launcher is bugged atm, deactivating mods sometimes does nothing. Open your DefaultModOptions.ini in steamapps\common\XCOM 2\XComGame\Config and delete all entries except for the com,munity highlander. Also delete XComModOptions.ini in Documents\My Games\XCOM2\XComGame\Config. Than you can be sure that nothing else is running.
