### ISSUE TITLE
Allow more customization to armory loadout screen for mods.

### ISSUE THREAD

**Issue by bountygiver** [X2CommunityCore/X2WOTCCommunityHighlander#171]
This is to roll in features from TONS of Utility Items to community highlander that allows wider customization of armory loadout screen for mods. The main difference of the highlander version and the standalone mods will be highlander will be configured through X2DLCInfo instead of an ini config to allow an even wider customization.

Changes already implemented in highlander:
- Custom restriction on specific items

Changes that needs to be implemented:
- Customization of number of utility item slots (#64 )
- Overriding images of items conditionally
- Overriding whether items should be equipped automatically for base game item slots (particularly 1st utility item and grenade slots, probably still use ini for this)
- Allow multiple heavy weapons
- Handling of ammo pockets in ValidateLoadout

**Comment by Danice123** [comment]
+1 <3
