### ISSUE TITLE
Convert the MP teams into usable teams for modders

### ISSUE THREAD

**Issue by RealityMachina** [X2CommunityCore/X2WOTCCommunityHighlander#188]
So, one of the fun things Firaxis never fixed in War of the Chosen is the silliness of how teams are implemented in XCOM 2, specifically as enums used as bitfields in the native end of the game:

```
// FIRAXIS begin -tsmith
// NOTE: need the eTeam_DONT_USE_X because the enum values are used as bitfields in C++ -tsmith 
enum ETeam
{
	eTeam_None,		// = 0
	eTeam_Neutral,	// = 1
	eTeam_One,		// = 2
	eTeam_DONT_USE_3,
	eTeam_Two,		// = 4
	eTeam_DONT_USE_5,
	eTeam_DONT_USE_6,
	eTeam_DONT_USE_7,
	eTeam_XCom,		// = 8
	eTeam_DONT_USE_9,
	eTeam_DONT_USE_10,
	eTeam_DONT_USE_11,
	eTeam_DONT_USE_12,
	eTeam_DONT_USE_13,
	eTeam_DONT_USE_14,
	eTeam_DONT_USE_15,
	eTeam_Alien,		// = 16
	eTeam_DONT_USE_17,
	eTeam_DONT_USE_18,
	eTeam_DONT_USE_19,
	eTeam_DONT_USE_20,
	eTeam_DONT_USE_21,
	eTeam_DONT_USE_22,
	eTeam_DONT_USE_23,
	eTeam_DONT_USE_24,
	eTeam_DONT_USE_25,
	eTeam_DONT_USE_26,
	eTeam_DONT_USE_27,
	eTeam_DONT_USE_28,
	eTeam_DONT_USE_29,
	eTeam_DONT_USE_30,
	eTeam_DONT_USE_31,
	eTeam_TheLost,		// = 32
	eTeam_DONT_USE_33,
	eTeam_DONT_USE_34,
	eTeam_DONT_USE_35,
	eTeam_DONT_USE_36,
	eTeam_DONT_USE_37,
	eTeam_DONT_USE_38,
	eTeam_DONT_USE_39,
	eTeam_DONT_USE_40,
	eTeam_DONT_USE_41,
	eTeam_DONT_USE_42,
	eTeam_DONT_USE_43,
	eTeam_DONT_USE_44,
	eTeam_DONT_USE_45,
	eTeam_DONT_USE_46,
	eTeam_DONT_USE_47,
	eTeam_DONT_USE_48,
	eTeam_DONT_USE_49,
	eTeam_DONT_USE_50,
	eTeam_DONT_USE_51,
	eTeam_DONT_USE_52,
	eTeam_DONT_USE_53,
	eTeam_DONT_USE_54,
	eTeam_DONT_USE_55,
	eTeam_DONT_USE_56,
	eTeam_DONT_USE_57,
	eTeam_DONT_USE_58,
	eTeam_DONT_USE_59,
	eTeam_DONT_USE_60,
	eTeam_DONT_USE_61,
	eTeam_DONT_USE_62,
	eTeam_DONT_USE_63,
	eTeam_Resistance, 		// = 64
	[yeah it gets really long after this part]
	eTeam_All,  // = 127
};

```

This means that mods adding their own separate teams is a complete non-starter. However, there are two separate teams added by Firaxis for the game's multiplayer functionality. My idea is to look into the potential of fixing the backend of the game so it's possible for mods to use eTeam_One and eTeam_Two for their own purposes. (Ideally, also include a way for mods to avoid stepping on each other's toes in case multiple mods want to use the same team for different purposes.)

The looks I've had so far seems to indicate this isn't technically impossible without Firaxis assistance, although I may be wrong. As far as I can tell, the following classes need to be looked at for changes that would be needed:

`XGBattle_SP` - the `SwapTeams` function is hardcoded to refer to the singleplayer teams only. Expansion of this to handle the MP teams would be necessary for abilities like Mind Control to function.

`X2Effect_MindControl` - `UpdateAIData` has a hardcoded check for the vanilla singleplayer teams, excluding eTeam_Neutral. Honestly we could probably just ditch the check entirely without causing any problems.

`XGPlayer` - `OnBeginTurnVisualized` should be altered so eTurnOverlay_Remote can be fired when eTeam_One or eTeam_two are the teams in use.

`XComPresentationLayer` - `UIEndTurn` should be altered so `case eTurnOverlay_Remote` can function more like a singleplayer turn in the single player part of the game.

The above two classes should have CH hooks to enable modularity of what the game can show when these teams are in play.

`XComGameStateContext_TacticalGameRule` - `CreateDefaultTacticalStartState_Singleplayer` only bothers creating the singleplayer only teams. The multiplayer teams should be inserted in here as well.

`UIMissionSummary` - currently only pulls total enemies killed from The Lost and Alien players in `GetNumEnemiesKilled`

`X2Condition_UnitProperty` - similar question to the mystery of the `IsEnemyUnit` check: the civilian handling is special and checks a template setting instead of the team they're on: does this mean it does not use the same kind of check as what it's in `XComGameState_Player`?

`XComGameState_Player` - ` CreatePlayer` handles only singleplayer teams, fix this to include the multiplayer teams. This is required to fix the SwapTeams issue above.

Due to the nature of what this function does (it assigns them a XGAIPlayer to look for), this should have a CH hook to let mods handle what eTeam_Two or eTeam_One will represent.

In addition, testing of what exactly `IsEnemyUnit` in `XComGameState_Unit` would be appreciated, since while it seems like it replicates the check in `XComGameState_Player` for enemy teams (ie being able to heal wounded resistance soldiers), official confirmation would be appreciated.

EDIT: Further additions

`XGUnitNativeBase` - `GetMyHUDIconColor` should be updated so it can show intended colours. Should probably be hooked into what `UITurnOverlay` has if it's modified per robojumper's suggestion.

`UITacticalQuicklaunch`  - `InitWithChallengeHistory` should be modified with the new teams also inited.

`XComGameState_Unit` - `OnUnitDied` has a big chunk of code that only runs on units from eTeam_Alien and eTeam_TheLost, which governs things like kills credited to a unit and whether they should drop their loot. This should be fixed by a highlander hook.

`XComGameState_Unit` - `PostCreateInit` has a problem where when trying to update the AI of a unit that has been newly created, whether through reinforcements, console commands, etc does this:

```	
        if( PerformAIUpdate )
	{
		XGAIPlayer(XGBattle_SP(`BATTLE).GetAIPlayer()).AddNewSpawnAIData(NewGameState);
	}
```

This should be altered so it grabs the AI Player of the player it's for.

`UnitAGainsKnowledgeOfUnitB` needs an alteration in its alert logic: it should consult with CHHelpers for a list of factions that we don't need to fully verify an alert is possible for, instead of just not fully verifying it for encounters with eTeam_TheLost. 

(This may also fix a small issue with using eTeam_Resistance units on other missions: they experience a similar issue with not properly activating when enemies spot them.)

`X2TacticalGameRuleset` - `StartStateSpawnAliens` does not properly init AI unit data for other teams. Remove the break; in the for loop, and add in checks for our eTeam_Two and eTeam_One teams to fix this.

`

**Comment by robojumper** [comment]
`UITurnOverlay` should be modularized to handle custom team overlays. Existing team overlays (xcom, alien, mp, lost, chosen) should be wrapped in an interface that uses the same mechanisms as any mod-added overlay would.

**Comment by RealityMachina** [comment]
Initial test report: eTeam_Two successfully used as new team in singleplayer mission that the game could switch to and from as if it was a regular team.

Enemies on eTeam_Two could be fired upon (and were) by eTeam_Alien enemies, and eTeam_XCOM.

However, enemies on eTeam_Two did not perform any action when it was their turn after scampering, causing the game to have to wait until their allowed time expired.

From checking the logs, the team was registered as having available actions for its unit, with the last report before the game switched control back to XCOM being in this part of `X2TacticalGameRuleSet`:

```
			//Wait for new states created by the player / AI / remote player. Manipulated by the SubmitGameStateXXX methods
			while( (bWaitingForNewStates && !HasTimeExpired()) || BuildingLatentGameState)
			{
				`SETLOC("Available Actions");
				sleep(0.0);
			}

```

**Comment by RealityMachina** [comment]
Further testing reports:

Enemies on eTeam_Two will be activated by enemies, and start performing actions, as long as a Resistance or Lost unit is on the field. Once all Resistance or Lost units have been defeated, previously activated eTeam_Two enemies will still function, but new ones added to the field will not, until new Resistance or Lost units have been added.

(Game set to not check for more XGAIPlayers unless members of those teams are active?)

They still do not patrol in green alert.

eTeam_Two enemies can and will target civilians as valid targets.

eTeam_Two enemies may sometimes pick areas where they will be flanked or will not have cover to move to.

**Comment by RealityMachina** [comment]
Report No. 3:

eTeam_Two enemies can be red alerted through console commands or other direct means; they will act normally from then on. Following from this, it seems like the failure point for enemies that aren't on eTeam_TheLost, in regards to activating eTeam_Two enemies on sight, is this part of `UnitAGainsKnowledgeOfUnitB` in `XComGameState_Unit`:

```		// no knowledge updates for The Lost
		if( UnitATeam != eTeam_TheLost && UnitBTeam != eTeam_TheLost )
		{
			bAlertDataSuccessfullyAdded = UnitA.UpdateAlertData(AlertCause, AlertInfo);
		}
		else
		{
			bAlertDataSuccessfullyAdded = true; // the lost still need to process alert level changes
		}

```
If bAlertDataSuccesfullyAdded is set to false, then the alert is not processed by the unit, though the scamper may still proceed on its own.

`UpdateAlertData` calls upon `AddAlertData` in the unit's `XComGameState_AIUnitData`. Whether because it does not exist or some particular check is failing, remains to be investigated.

**Comment by RealityMachina** [comment]
Report No. 4

Found critical issue that may have been source of many issues: `X2TacticalGameRuleset`, in `StartStateSpawnAliens` had a major flaw:

```
		// After spawning, the AI player still needs to sync the data
		foreach StartState.IterateByClassType(class'XComGameState_Player', IteratePlayerState)
		{
			if( IteratePlayerState.TeamFlag == eTeam_Alien || IteratePlayerState.TeamFlag == eTeam_TheLost )
			{				
				XGAIPlayer( CachedHistory.GetVisualizer(IteratePlayerState.ObjectID) ).UpdateDataToAIGameState(true);
				break;
			}
		}
```

This meant that after creating eTeam_Alien's ai unit data, it stopped trying to init ai unit data for other teams.

After fixing this in my test mod, eTeam_Two units could properly patrol in the fog of war. Hopefully further testing will indicate eTeam_Resistance units better cooperate with units from that team if they're near each other in the fog of war, and I can perhaps start working on a proper pull request for at least the baseline functionality in the near future.


Addendum: kismet logic for vanilla retaliations cause a bit of a funny issue: they check that a unit rescuing a civilian wasn't a unit from eTeam_Alien or eTeam_TheLost instead of checking if a unit is from eTeam_XCOM: this means that hostile eTeam_Two units can rescue them.

**Comment by RealityMachina** [comment]
Report No. 5:

eTeam_Two units no longer seem to interfere with eTeam_Resistance units with the functional changes I've made. eTeam_Two units are effectively acting as normal units.

As a basic summary:

`X2TacticalGameRuleset` - changed `StartStateSpawnAliens` so it would go through all players, initializing AI unit data as required. A highlander hook would be appreciated so teams can be initialized as needed.

`XComGameState_Player` - changed `CreatePlayer` so it would properly assign a `XGAIPlayer` class for that player. A highlander hook is needed for multiple mods to avoid stepping on each other's toes here.

`XComGameState_Unit` - `UnitAGainsKnowledgeOfUnitB` does not *need* to be changed, but if someone wishes to implement a team to be more akin to the Lost, it would be helpful to have a highlander hook to identify which teams should not require a full verification of processing an AI alert for.

`XComGameStateContext_TacticalGameRule` - `CreateDefaultTacticalStartState_Singleplayer` should be altered so it inits eTeam_Two and eTeam_One into matches if applicable via a highlander hook. Without any corresponding units to use, the game should just skip these teams over.

`XComPresentationLayer` - `UIEndTurn` altered so turns would properly transfer to eTeam_Two or eTeam_One on the UI end when eTurnOverlay_Remote was used.

`XGPlayer` - `OnBeginTurnVisualized` altered so eTeam_Two would sent out an overlay type when its turn was over.


All this, plus a custom XGAIPlayer class for the team (this should be done by mods utilizing the highlander) was necessary to have a working fourth/fifth party on maps.

**Comment by RealityMachina** [comment]
Alright, back here again because it turns out the gamestate `XComGameState_AIPlayerData` breaks a lot of things when it's allowed to be spawned in multiple times.

Right now the latest unstable version has hotfixed problems with the Chosen and the Rulers, but as it turns out mind control is also broken from changes we made there. I think I know how to hotfix that since I did have mind control working with the initial release and none of the changes we made to have Chosen and Rulers work again would be impacted, but I feel like we're at the point where constantly hotfixing issues as they crop up is going be seen as miserable.

So alternative approachl: try to keep everything to one, global AIPlayerData.

The specific things that could need to be changed to accomdate this are:

In `XGAIPlayer`:

`UpdateDataToAIGameState` needs to be altered so it checks and grabs AIPlayerData if it already exists, instead of always making a new one.

In `XGAIPlayerNavigator` 

`RefreshGameState` should be altered so it grabs the only existing AIPlayerData that should be there, instead of trying to filter it. This should let eteam_one/eTeam_Two pods continue to patrol.

In `XComGameState_AIUnitData`

`AddGroupAlertData` should be altered similarly: grab the only existing AIPlayerData that should be there instead of trying to filter it. This will let eTeam_One/eTeam_Two pods properly inform their members of any alerts they have received, if they're told to pass on the alert like that. 

(This is preliminary and may be updated with additional changes we need to make)

**Comment by TyrantProd** [comment]
Hi, I know this post hasn't been touched in forever, but I'm here to ask if it's possible to use the eTeam_DONT_USE_X to assign various factions. 

If possible this would allow to have battles involving several raider factions instead of having all raiders on the same side when multiple faction spawn as sitrep.

I don't know enough about coding to be of much help, but I'm mostly just asking to see if someone knows if it's possible.

**Comment by robojumper** [comment]
Copying what I posted a while ago on the Discord (TL;DR No):

> robojumper: For performance reasons, native code doesn't store arbitrarily large lists of teams to control visibility towards other teams and ally/enemy status, instead it stores these as individual bits in a byte. A byte has 8 bits, and the teams in increasing bit index order are Neutral, MP One, MP Two, XCom, Alien, Lost, Resistance (7, so maybe there would have been space for one more team) 
> robojumper: So if you tell native code "this unit is visible towards team 73", in binary that's 1001001 = Resistance | XCom | Neutral
> robojumper: It's only powers of two (2^x) that have exactly one bit set, so only those enum entries are valid teams. If we renamed the DontUse entries and tried to turn those into teams, native code would think a unit is on multiple teams at the same time for some purposes (when doing flag membership tests), but not on any of these teams for other purposes (when directly comparing the team enum) and it'd all fall apart in probably very amusing ways
> Kazuma Yu (Losu): Hypothetical question: If someone was to expand the list to 256 (Or 257) Entries (And possibly 512), and add a named team at said entry, would it be valid or no?
> robojumper: UnrealScript enums are limited to 255 entries since internally they're bytes, so the most we could have is one more team. But even then, there's an eTeam_All pseudo-flag at index 127 (01111111) covering all teams, and that's almost certainly used by both native code and mod code. This code would have to be recompiled to gain the additional 1 needed for the last added team 
> robojumper: So even though there would have been space for Firaxis to add exactly one more team, we can't do it

**Comment by TyrantProd** [comment]
Thanks for the answer, i was afraid of something like that when I noticed the //= being powers of 2, but I had to hope.
