### ISSUE TITLE
Crash after cooking Highlander

### ISSUE THREAD

**Issue by KongMD-Steam** [X2CommunityCore/X2WOTCCommunityHighlander#191]
I'm attempting to build the highlander and cook it, in preparation to test a change I'd like to submit. I've spent a couple days trying to get the cook to work, but the game always crashes on startup. I'm out of ideas.

## Steps Taken:
1) Downloaded highlander src .zip from Github
2) Ran this in Powershell to unblock all the source files: `ls -r | Unblock-File`
3) Deleted SDK\Development\Src
3) Opened Highlander .sln and built the 'Release' build target successfully
4) Went through all cooking steps manually, as listed on the Readme.md page
5) Ran game with from Alternative Mod Launcher with arguments `-noRedScreens -nostartupmovies -allowconsole -log`. Selected only the highlander mod.
6) Game crashes. [Here's my Launch.log file](https://pastebin.com/enBFCbqt). Relevant lines:
```
[0016.37] ScriptLog: X2CH SCREEN LISTENER ON SPLASH X2WOTCCommunityHighlander v1.8.1
[0016.70] Log: UOnlineSubsystem OnlineSubsystemSteamworks_0

[0017.28] Warning: Warning, Detected data corruption [header] trying to read 131072 bytes at offset 31098983 from '..\..\XComGame\CookedPCConsole\Textures-a_XPACK_.tfc'. Please delete file and recook.
[0017.28] Critical: appError called: Assertion failed: appErrorf [File:G:\BuildAgent\work\ce3b64a62966ccd1\branches\ShippingOzzy\XCOM2\Development\Src\Core\Src\UnVcWin32.cpp] [Line: 150]
I/O failure operating on '..\..\XComGame\CookedPCConsole\Textures-a_XPACK_.tfc'
Stack: Address = 0x7c38a3dc (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\Binaries\Win64\XCom2.exe]
```

I read Abe Clancy's post, and he mentioned that errors of this type are caused by not having the correct .upk, .bin, and .tfc files from the vanilla game in the 'SDK\XComGame\Published\CookedPCConsole' directory. I am 100% sure that those files are there. I've checked this multiple times.

## Troubleshooting Performed:
1) Deleted 'My Games\WOTC\XComGame\Config' folder
2) Tried -noseekfreeloading as a workaround, but the vanilla game crashes, even with the correct junctions
3) Tried various highlander build targets (Debug, Release)
4) Went through the whole process multiple times

**What am I missing?**

**Comment by robojumper** [comment]
@KongMD-Steam Whoops, sounds like we didn't update the instructions + script for the December patch. Firaxis cooked the update in a weird way. I'm going to update those later today.

`-noseekfreeloading` is broken, no one has been able to get it to work since the latest patch.  
In order to cook a Highlander now, the `-tfsuffix=_XPACK_` parameter must be omitted from the CookPackages commandlet.

**Comment by KongMD-Steam** [comment]
SUCCESS! Thank you so much for the quick reply. I made a few changes to the CookCommunityHighlander.bat script that could benefit the project. I'll PR them today with the -tfsuffix parameter removed.
