### ISSUE TITLE
Add a PreBodyPartTemplatesCreated hook

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#220]
It can be desirable to create body part template config dynamically instead of adding them all in `XComContent.ini`, often tedious and verbose. A DLC hook would make adding/removing body part templates much easier.

**Comment by Iridar** [comment]
I'm closing this until someone is actually willing to implement and has a use case for it. I'll also note that it should be possible to use OnPreCreateTemplates() to do arbitrary things to BodyPartTemplates config, so individual mods can implement their own implementations without stepping on each other's toes, and other than convenience / avoidance of code duplication, there's little reason to implement this in Highlander.
