### ISSUE TITLE
Let enemy units track kills they make

### ISSUE THREAD

**Issue by RealityMachina** [X2CommunityCore/X2WOTCCommunityHighlander#221]
Basically just an enhancement I want so the MOCX posters that track the kills an operative has made work properly.

**Comment by robojumper** [comment]
I think we merged something that fixed this.

**Comment by pledbrook** [comment]
Would this issue be adversely affected if I put the kill count increment behind a "CanAwardKillXp" event? The idea would be to allow mods to prevent the accumulation of kill XP based on any critiera they choose. I would like it to implement a cap on the total kill XP that can be gained in a mission.

The code would look something like:
```
if (TriggerCanAwardKillXp(Killer))
{
	Killer.KillCount += GetMyTemplate().KillContribution;
}
```

**Comment by pledbrook** [comment]
@RealityMachina Do you know whether the above change I mentioned breaks the behaviour you want or not?

**Comment by RealityMachina** [comment]
It's good, I only need KilledUnits itself, not the KillCount variable used for levelling up.
