### ISSUE TITLE
Community Highlander being odd

### ISSUE THREAD

**Issue by NeilOsiris** [X2CommunityCore/X2WOTCCommunityHighlander#228]
Hey, so I've been using XCOM 2/WOTC mods for the past few weeks and for some reason a lot of the mods didn't seem to work. I thought it was an issue with the mods individually but then noticed that all of these malfunctioning mods used the Community Highlander. I saw more or less the same issue in #79 and thought I'd find my fix there, but since that's half an year old + You folks have updated a lot more now, wasn't sure if the older version would fix (It didn't.). I've done a clean reinstall of the game, deleted all my mods and went the whole nine yards to figure out if I did something wrong in my installation but I can't tell for sure since even after reinstalling, I've no proper confirmation of the mod working. I see it in the ModLauncher, but if I'm supposed to see some sort of version string, I'm not, and from that I've assumed that it's not working.

Any aid would be useful, thanks.

**Comment by abatewongc** [comment]
In my experience, mods not loading is a config issue. I would try deleting the contents of `%USER%\Documents\My Games\XCOM2 War of the Chosen\XComGame\Config` or using the [Alternate Mod Launcher](https://github.com/X2CommunityCore/xcom2-launcher/releases/tag/v1.2.1) before progressing further.

**Comment by NeilOsiris** [comment]
I deleted the contents of Config, didn't seem like it did anything. As for the Alternate Mod Launcher, it kept giving me a bug about 'Please start Steam first!' even though Steam was active. So I'm not at all sure how to figure this out. By the way, how would I for sure know that the Highlander is working? I saw the post about version strings on the lower right side but I haven't seen that.
I'm at a loss at this point.

**Comment by bountygiver** [comment]
you also want to delete the contents of `DefaultModOptions.ini` in the config folder in your game installation folder

**Comment by NeilOsiris** [comment]
I've tried out both of these paths and I haven't had luck with either. Not only that, for some reason now, my game cannot start a new campaign without a CTD during loading. No crash-logs or anything, just the screen turns black for a split second and then I'm on the desktop. This has happened both with and without mods on, so I'm guessing one of these steps may have messed with my game files.

I might reinstall XCOM later on, but I'll keep an eye out for any possible info on how to solve this.

**Comment by danolsee** [comment]
I've been having the same issue. Has anyone found a way to fix this yet?

**Comment by Xymanek** [comment]
I had a similar problem with completely inconsistent and basically undefined game behaviour when launching wotc for first time after playing vanilla just fine.

This fix for me was to go to steam and tell it to verify game's files. It downloaded a couple of files and that fixed it

**Comment by Musashi1584** [comment]
Someone states you can't use the Highlander on a steam account with shared access to XCOM 2
https://www.reddit.com/r/Xcom/comments/7t9x3d/normal_to_have_these_messages_with_community

His solution is to copy the Highlanders CookedPCConsole folder to the games CookedPCConsole folder.

**Comment by Evilopoly90** [comment]
No idea what I am doing wrong. I did everything that has been suggested here and other places. Put the highlander into a mod folder in Xcomgame, copied and pasted folders, used alternate mod launcher. Nothing is working. In the log it isn't saying wether highlander is active or not. I can not launch the game with any mod that uses the highlander. On the log it simply crashes after trying to load [0019.21] Log: FiraxisLive: UX2FiraxisLiveClient::Init - Using SHIPPING_PC_GAME
[0019.21] Log: FiraxisLive: UX2FiraxisLiveClient::Init - Using USING_OZZY_PROJECT
[0023.29] Log: Crash Detected: Dumping C:\Users\God Emperor Jamie\Documents\My Games\XCOM2 War of the Chosen\Binaries\Win64\..\..\XComGame\Logs\XCom-DESKTOP-AVED14I-CL326249-2018.09.18-00.45.47-Crash\XCom-DESKTOP-AVED14I-CL326249-2018.09.18-00.45.47_Minidump.dmp
[0023.29] Log: 	Crash: GettingNameData
[0023.30] Log: Suspending Threads
[0023.34] Log: Writing Minidmp
[0023.77] Log: 	Crash: Saving Names Array
[0023.77] Log: 	Crash: Saving Names Array Data
[0023.78] Log: Dumping name table: (2125768)
[0023.78] Log: Dumping name table: 0x25290000 (2125768)
[0023.78] Log: 	Crash: Saving Names Array Blocks
[0023.78] Log: 	Crash: Saving Objects Array
[0023.78] Log: 	Crash: Saving Objects Array Data
[0023.78] Log: 	Crash: Saving Objects
[0025.13] Log: Waking Threads
[0028.42] Log: Crash: appSendCrashTelemetry
[0028.42] Log: CRASH: Copying Log

**Comment by bountygiver** [comment]
xcom 2 has a weird behaviour that it doesn't load highlanders if it does not connect to steam properly, so one workaround is to copy the `XComGame.upk` from the `CookedPCConsole` to the folder of the same name in your my documents/my games/xcom 2 folder.

**Comment by Iridar** [comment]
Closing issue, because A) Haven't heard of anyone having similar issues in a while, B) potential solutions are listed, and C) there doesn't seem anything to be done on Highlander's end about this.
