### ISSUE TITLE
New release 1.11 causing game to freeze (and die) after completing Covert Op

### ISSUE THREAD

**Issue by Smilodonka** [X2CommunityCore/X2WOTCCommunityHighlander#243]
Noticed this with today's update. Covert Op "Hunt the Chosen: Part 1" was in progress when the update came out (started an Op, quit the game, then the update came out with the Op still in progress). Game dies when I click "Continue" at the Covert Op report screen. Reverted to previous 1.10, everything works fine now. I'm running 180+ mods, so far this is the very first issue I've encountered. Mods I run that affect Covert Ops are:

Multiple Covert Actions - https://steamcommunity.com/sharedfiles/filedetails/?id=1130967851

WotC: "Increase Combat Intelligence" for everyone - https://steamcommunity.com/sharedfiles/filedetails/?id=1134537412

Expose Chosen Weakness - https://steamcommunity.com/sharedfiles/filedetails/?id=1132573074

I'll gladly provide more info if needed, just tell me what to look for.

**Comment by RealityMachina** [comment]
Does switching to 1.11.0 *after* the in-progress covert action completes still results in crashes down the line?

**Comment by RealityMachina** [comment]
@GingerAvalanche has identified the issue, we'll try to fix this as soon as we can.

**Comment by Smilodonka** [comment]
@Musashi1584 
Tested the fresh workshop version on the same save that was crashing before. Everything is nice and clean now, no freezes, no crashes. Seems like you got the issue just right. Keep up the great work team, and thank you for a quick fix!
