### ISSUE TITLE
Add ini helper to X2Photobooth when determining when SPARK poses can be used

### ISSUE THREAD

**Issue by RealityMachina** [X2CommunityCore/X2WOTCCommunityHighlander#248]
Currently it's a hard check for the SPARK soldier class, so anything that's on the same template (or uses a similar style of base pawn) but otherwise different class will not be able to use those specific poses, or otherwise be able to use the workarounds Firaxis made for SPARKs when it came to certain parts of the photobooth.

An .ini entry in the CHHelpers class detailing what other classes also need to fall under that check, along with a helper function that checked that list (alongside greenlighting SPARKs) would be helpful.

**Comment by robojumper** [comment]
I think this one is covered under #316
