### ISSUE TITLE
Should we report base game issue ?

### ISSUE THREAD

**Issue by ProZeratul** [X2CommunityCore/X2WOTCCommunityHighlander#25]
Hello,

If I understand correctly this mod provides an easier way to mod the base game AND will provide unofficial bugfix ?

If the bugfix part is correct should we report base game bug here ?

**Comment by MalucoMarinero** [comment]
if it's clearly a bug and requires a base game class override then it will probably find a home here. Ideally the bug should be FIXED by an isolated mod first rather than being suggested directly, and then we can use that mod bugfix as a template for what we end up doing.
