### ISSUE TITLE
Spawn a larger squad.

### ISSUE THREAD

**Issue by solongzzz** [X2CommunityCore/X2WOTCCommunityHighlander#255]
I can't get the extra spawn tiles to work with 10 or more unit, all my soldiers spawned in 1 tile in the middle of the map (sometime underground).

I try reinstall the game, mods (robojumper's squad select, community highlander and allow for larger squad). Delete XCom2WOTC folder in 'My games'.
Change
";SPAWN_EXTRA_TILE=0 ; Uncomment this to increase default spawn size for XCOM"
to 
"SPAWN_EXTRA_TILE=1"
in both highlander and 'Allow for larger squad'. But nothing change.

**Comment by Iridar** [comment]
Closing due to our apparent indifference to this poor soul's problems.
