### ISSUE TITLE
Intermittant Highlander and net connectivity.

### ISSUE THREAD

**Issue by SabinStargem** [X2CommunityCore/X2WOTCCommunityHighlander#256]
I was using the Highlander mod, but features vanished whenever my internet connection went down. The mod itself was registering - MCM still showed options, but the mods relying on Highlander had no actual effect on the game. After trying many methods, I ultimately resorted to overwriting the vanilla "CookedPCConsole" folder's contents. That last resorted works fabulously.

**Comment by Iridar** [comment]
Closing, because it seems like a weird one-off problem, and there doesn't seem anything to be done about this on Highlander's end.
