### ISSUE TITLE
Broken translucent effects

### ISSUE THREAD

**Issue by DJ4ddi** [X2CommunityCore/X2WOTCCommunityHighlander#265]
Hi there,
I am having issues related to certain effects, so I tried older versions and tracked the problem to the 1.8.1 patch. Every later version has the same problem.

This is what the gremlin looks like in 1.8.1: 
![gremlin_bugged](https://user-images.githubusercontent.com/1696102/43670558-5c54c156-978d-11e8-8af2-676eac3a7f00.png)

And in 1.8.0:
![gremlin_regular](https://user-images.githubusercontent.com/1696102/43670559-5c6c89b2-978d-11e8-9c79-10769f157fe0.png)

Similar results can be seen for almost every particle (smoke, fire, lightning) and some other things (advent overlays on doors, a sidewalk texture - probably grass?).

I'd post a log, but the output between the two versions is virtually identical (save for timestamps and some timings). No errors or warnings anywhere. Various changes to graphics settings also made no difference.

Any idea what would cause this? The only relevant commit (difference between working and non-working versions) is 632aed4d48b85b6fe7d90aba3abf0a2a7a754c74.

**Comment by robojumper** [comment]
That's... weird. I don't think we've ever seen anything like this. Can you give us more info about your setup (OS Version, CPU, GPU, ...)?

Some troubleshooting steps:

* Verify game files via Steam
* Delete your config directory (Documents/My Games/XCOM 2 WotC/XComGame/Config)
* Run the game without any mods, with `1.8.0`, and with the latest version to see if it's still behaving the same way

If that doesn't help, you could try building your own Highlander to see if that works, but SDK is 70GB, so I can understand if that's not an option.

**Comment by DJ4ddi** [comment]
Alright, easy things first: The screenshots were taken with a clean (newly created) config directory and no other mods enabled.

CPU block (Intel i5-4670K):
```
[0000.07] Init: CPU Page size=4096, Processors=4
[0000.07] Init: High frequency timer resolution =3.312643 MHz
[0000.07] Init: Memory total: Physical=12.0GB (12GB approx) Pagefile=24.0GB Virtual=131072.0GB
```

GPU block (NVidia GTX 1060):
```
[0000.89] Log: resX=2560, resY=1440
[0000.95] Log: Found D3D11 adapter 0: NVIDIA GeForce GTX 1060 6GB
[0000.95] Log: Adapter has 6052MB of dedicated video memory, 0MB of dedicated system memory, and 6120MB of shared system memory
[0000.96] Log: Found D3D11 adapter 1: Microsoft Basic Render Driver
[0000.96] Log: Adapter has 0MB of dedicated video memory, 0MB of dedicated system memory, and 6120MB of shared system memory
[0000.97] Log: Shader platform (RHI): PC-D3D-SM4
[0000.98] Log: PhysX GPU Support: DISABLED
[0000.98] Log: FaceFX 2015.2 (2152) initialized.
```

Verifying actually is a problem since XCOM 2 is installed on a machine that currently has no internet access. This also means that it's always running in offline mode (something I should have mentioned earlier). I can take the drive out again, but not before next week.

**Comment by DJ4ddi** [comment]
Alright, finally got to verifying the files, issue persists.

**Comment by robojumper** [comment]
@DJ4ddi Can you please check if the TLP update fixed this?

**Comment by DJ4ddi** [comment]
I can not reproduce the issue with TLP and Highlander 1.15.0.
