### ISSUE TITLE
Animations for Samurai, Ballistic Shields, and Dual Wield Melee not working.

### ISSUE THREAD

**Issue by Beefi** [X2CommunityCore/X2WOTCCommunityHighlander#267]
I've been told that this highlander deals with the animations for these mods and they're not working for some reason.

**Comment by Xymanek** [comment]
Do you see "Community highlander" text at the bottom of screen when you launch the game?

**Comment by Musashi1584** [comment]
Most likely highlander not running. Closing the issue.
