### ISSUE TITLE
Don't have a X2WOTCCommunityHighlander mod that is compatible with the MacOS

### ISSUE THREAD

**Issue by fox15draco** [X2CommunityCore/X2WOTCCommunityHighlander#268]
game keeps crashing when using the normal mod that on steam. Could someone make it so it can work on the Mac because a lot of mods are unavailable to me because this doesn't work on my computer.

**Comment by robojumper** [comment]
Essentially a duplicate of #167. We haven't found a way to make it work since the latest patch (December 2017), so we're out of luck until Feral Interactive makes a move.
