### ISSUE TITLE
XComGameState_Item weapon upgrade UI does not support damage weaponupgrades

### ISSUE THREAD

**Issue by Charmed4321** [X2CommunityCore/X2WOTCCommunityHighlander#29]
GetWeaponStatsForUI() does not check for damage modifying weapon upgrades

GetUpgradeModifiersForUI(X2WeaponUpgradeTemplate UpgradeTemplate) uses UpgradeTemplate.BonusDamage.Damage > 0 to solely identify MissDamage, rather than damage and UpgradeTemplate.BonusDamage.Tag=="Miss" so that an upgrade improving normal damage can get a UI stat markup.

**Comment by Iridar** [comment]
I'm reasonably sure this is addressed by #237. Or at least I don't see any explicit references to `"Miss"` damage tag in XCGS_Item. Either way this issue no longer appears to be relevant, closing.
