### ISSUE TITLE
Game won't load since update

### ISSUE THREAD

**Issue by luxmanifestus** [X2CommunityCore/X2WOTCCommunityHighlander#291]
Since the update, the game won't load with mods. It becomes unresponsive and just hangs.

**Comment by robojumper** [comment]
Since you said in the workshop comments:

> Version 1.13.0 doesn't work either now. :(

it probably doesn't have anything to do with the update. However, we *might* be able to help if you can share your log file via [pastebin](https://pastebin.com). You can find it as

    %USERPROFILE%\Documents\My Games\XCOM2 War of the Chosen\XComGame\Logs\Launch.log

**Comment by luxmanifestus** [comment]
Thanks so much. I have a large mod list as I'm trying out mods. I appreciate any help you can give. I love your mods, btw.

https://pastebin.com/4jn5EDrR

**Comment by robojumper** [comment]
Your paste is private so the only one who can view it is you.

**Comment by luxmanifestus** [comment]
Sorry, I assumed you had an account. How about this one:

https://pastebin.com/num3YZTk

**Comment by robojumper** [comment]
Not seeing anything extraordinary. The next steps would probably be

* Making a backup of the mod list
* Confirming that the game launches without mods
* Confirming that it doesn't launch with the Highlander
* Trying to clear your config (as described [here](https://steamcommunity.com/workshop/filedetails/discussion/1126623381/1474222595301114193/)), and verifying your game files via Steam

**Comment by luxmanifestus** [comment]
The game launches with only the highlander installed but clearing the config and verifying the steam files didn't work. I'm guessing that it's a mod conflict but it's a complex one involving more than one because I haven't been able to narrow it down with a single process of elimination. Do you have any advice on how to determine which mods would not be working with it? Thanks for all your help.

**Comment by robojumper** [comment]
@luxmanifestus Have you been able to get it to work since the TLP update?
