### ISSUE TITLE
Incompatible with Tactical Legacy Pack DLC

### ISSUE THREAD

**Issue by PlatinumKit** [X2CommunityCore/X2WOTCCommunityHighlander#294]
Game Crashes on Startup When I Try to load this mod With the DLC. It Seems that other people are Experiencing the same problems.

**Comment by GingerAvalanche** [comment]
Known issue. We have determined the problem and are working on a fix.

**Comment by robojumper** [comment]
@PlatinumKit We just published v1.15.0 to [GitHub](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/releases/tag/v1.15.0) and the [Steam Workshop](https://steamcommunity.com/workshop/filedetails/?id=1134256495), please check if it's working now.

**Comment by PlatinumKit** [comment]
It Is Working Now. Thanks;)
