### ISSUE TITLE
New Attitudes and Photobooth options not working/showing

### ISSUE THREAD

**Issue by BlackRose39** [X2CommunityCore/X2WOTCCommunityHighlander#296]
Greetings.

Since the TLC expansion and the new update to the highlander, there are two issues I wanted to report.

The only mod that I have enabled is the highlander. The first issue goes away without it enabled, not sure about the second.

The first issue is that the new attitudes do not work.

![20181011143249_1](https://user-images.githubusercontent.com/44072125/46832610-bc55dc00-cd63-11e8-9199-3080a45e0547.jpg)
![20181011143245_1](https://user-images.githubusercontent.com/44072125/46832618-c11a9000-cd63-11e8-8997-80e2616f2945.jpg)

The animation seems to revert to when a soldier is on the field. (Not the intense personality despite similar looking). When the highlander is not active, this issue does not occur. Also, when selecting the new attitude, then reverting to the default ones, their torso and legs do not reset.

The second issue is that I also do not see the new photo booth options (unless they were not available from the start and have to be unlocked like with the attitudes, which I'm not sure about.) I do not see the ones shown in the dev videos, etc. with interaction with aliens, use of the rope, etc. (Again, only the highlander is enabled).

The version is v1.15.0.

Thanks everyone for your hard work, you are all very talented.
-Black Rose

**Comment by robojumper** [comment]
Closing this as there's been no further response. Feel free to re-open if this is still relevant.
