### ISSUE TITLE
Add DLC hook to X2StrategyElement_DefaultMissionSources:SpawnPointOfInterest

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#298]
This function is responsible for spawning the Black Market (or a standard POI). DLC_2 and DLC_3 hijack the standard POI code, but there's no way for mods to spawn a Black Market equivalent. A DLC hook would improve this situation for mods.

**Comment by pledbrook** [comment]
LW2 does this via `XComGameState_BlackMarket.ShowBlackMarket()` on campaign start. Is this issue about a different scenario?

**Comment by robojumper** [comment]
@pledbrook This is about showing something *like* the black market later in the campaign. The function is a convenient place to do it.

**Comment by Iridar** [comment]
> there's no way for mods to spawn a Black Market equivalent. 

I'm confused. It seems to me it would require merely creating a new state object and then "activating" it to show it on the Geoscape. What am I missing?

**Comment by robojumper** [comment]
I believe the idea was that the Black Market spawns in place of an existing POI after a mission even though it's not a POI, and some mod code might want to do that too (in order to counteract strategy dialogue spam from various events all happening after a mission). I have no use for this right now, so closing.
