### ISSUE TITLE
Highlander Bug - Controller Interface Issue - Character Customization Screen

### ISSUE THREAD

**Issue by ricardofloresRJF** [X2CommunityCore/X2WOTCCommunityHighlander#301]
Hello!  First off thank you for such a wonderful achievement and generous gesture for a game and community we all love.

I ran into an issue with using a game controller and trying to change my characters appearance.  With the ability to edit the article of Body clothing, the controller does not allow a way to differentiate between selecting the piece or editing the piece itself.  It defaults to editing the piece so you are never able to actually change/select the item you want.  

The button in the game functions as a dual button where the larger, row button changes the piece and the smaller "edit' button brings up the attributes screen for the item.  The controller defaults to selecting the edit button. 

Being there is no quick way to switch back to keyboard and mouse control, this becomes potentially feature breaking when it comes to the sitting on the couch, playing the best game of all time experience.

I recently just discovered that controller interface was added, so if I have to go back to k&m that's cool.  I just wanted to make the community aware of the issue.

Thanks!

**Comment by robojumper** [comment]
@ricardofloresRJF I have trouble understanding what issue you're having, or how it is relevant to the Highlander. Can you make sure that the screen / UI you mention is in fact provided by the base game (or Highlander), and not by a third party mod? If so, please include a screenshot.

**Comment by ricardofloresRJF** [comment]
My sincerest apologies.  My troubleshooting was screwed up somewhere.  It wasn't the highlander, of course not.  It was indeed the unlimited customization mod.  

My bad, man!  Sorry for the confusion.  Thanks for leading me to reopen my troubleshooting and find the true root cause.

Thanks!
