### ISSUE TITLE
Make "Legacy Operations" respect Squad/Soldier/Class changes

### ISSUE THREAD

**Issue by MrNiceUK** [X2CommunityCore/X2WOTCCommunityHighlander#307]
Except for a new random Operation, where the squad must be generated from scratch, for the first mission in a Legacy Ops soldiers are used directly from the save for the first mission, without referencing the relevant squad/soldier progressions and soldier class templates. For later missions, changes to squad progression made by mods is respected. To open this design space for mods, I propose that the CHL should recreate the squad (similar to what happens when you create a new random operation), and so pick up changes to relevant  configs, soldier classes, etc.

**Comment by Xymanek** [comment]
> To open this design space for mods

Do you mean making new legacy ops? Or changing the existing

**Comment by MrNiceUK** [comment]
@Xymanek I mean changing existing. Basically, although it appears you can change some aspects of existing Legacy Ops through ini edits and similar, most changes will be ignored for the first mission, while taking effect in later missions.

**Comment by MrNiceUK** [comment]
Ok, changed the Issue Title, since changing the soldier class and/or soldier class templates doesn't work for any missions, it's not just a "first mission" issue. Same for CharacterTemplate and changing squad size, which are related issues.
