### ISSUE TITLE
Make changes to the Photobooth to be more accessible by mods

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#309]
Dont have a solid plan right now. Ideas are welcome.

**Comment by Iridar** [comment]
This issue doesn't seem to serve any purpose at the moment, so I'm closing it.

**Comment by Iridar** [comment]
Apparently, this issue was implemented after all? 

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/c9d5aba32cb4fcbf119807bd20a714e9c51f8361/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2PhotoboothHelpers.uc
