### ISSUE TITLE
Suggestion: Add an ini config option to disable the minimum 1 dmg through armor

### ISSUE THREAD

**Issue by Hannibalian** [X2CommunityCore/X2WOTCCommunityHighlander#321]
I inquired about this on the subreddit awhile back and was told that the Highlander is probably the safest way to make adjustments to `X2Effect_ApplyWeaponDamage.uc`. The code to reference:

```
if (ArmorMitigation >= WeaponDamage)
ArmorMitigation = WeaponDamage - 1;
```

Ideally we could set this to 0 from the config, or to any value we wished.

/u/septichem proposed a potential solution [here](https://www.reddit.com/r/xcom2mods/comments/9iebo3/anybody_have_information_on_how_the_minimum_1/e6nk6il/).

```
// somewhere at the top of the file (probably next to the other config values)
// can config values have a default value in code?
var config bool ALWAYS_APPLY_MINIMUM_DAMAGE;

// ...

if ((ArmorMitigation >= WeaponDamage) && ALWAYS_APPLY_MINIMUM_DAMAGE)
  ArmorMitigation = WeaponDamage - 1;
```

**Comment by Iridar** [comment]
Closing this because it was implemented in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/747
