### ISSUE TITLE
Allow Torsos, Arms, Legs to have localized names

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#328]
X2BodyPartTemplateManager has this code:

		// HAX: Load 'Torso', 'Arms' and 'Legs' templates the old way to prevent template name collisions:
		// TODO: @rmcfall - make all body part template names unique so they can be individually localized
		switch(PartInfo.PartType)
		{
		case "Torso":
		case "Arms":
		case "Legs":
			Template = new class'X2BodyPartTemplate';
			break;
		default:
			// This is the "new", proper way of instantiating a template (requires unique TemplateName)
			Template = new(None, string(PartInfo.TemplateName)) class'X2BodyPartTemplate';
		}

While a mod [exists on the Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=878158600) to work around the problem, it's still a dependency, is awkward to set up, and has some sort of race condition with Unrestricted Customization[1]. Some fix in here shouldn't cause too many problems.

--------------------
[1] I still have no idea what the hell that mod is doing and why it breaks Add Part Names, but I'm like 50% sure that an HL fix wins over Unrestricted Customization.

**Comment by MrNiceUK** [comment]
The "plan" for the enhancement is to concatenate the template name and part type to create the unique instance name. Probably also requires changes to the Armoury code to actually check for the DisplayName of the 3 body types. On a related note, apparently Shin decos don't show the display name for equipped parts, only for the selection list. Other less used deco slots may also have that issue.

**Comment by MrNiceUK** [comment]
Do we take it upon ourselves to give reasonable display names to vanilla/WotC/Anarchy's Children parts?

**Comment by robojumper** [comment]
> Do we take it upon ourselves to give reasonable display names to vanilla/WotC/Anarchy's Children parts?

Some people already did, but I'm not sure whether we want to ship it with the HL.

https://steamcommunity.com/workshop/filedetails/discussion/878158600/135511455870610385/

**Comment by Dragon-32** [comment]
Well I prefer mine ;)

I'd say not to include names in the HL, chances are people will release mods making use of this just like Vortex Pixalation and Musashi have released mods changing a value or two in the HL .ini files.

**Comment by PinkysBrain** [comment]
Unrestricted Customization seems to build display names for the menus on the fly from the template names even when it doesn't have localization.

For instance when I have Anarchys Children Extra Options installed there's a template without localization called Additional_CnvMed_Std_E_MCnvMed_Std_F_M, with Unrestricted Customization that becomes "Additional Padded Medium EPadded Medium F (M)".  Ugly, but that's because of the ugly template name.

**Comment by MrNiceUK** [comment]
Ok, just discovered that the AC parts have localization in their files, you just don't see them! AC parts have the part type named in their template, hence unique template names (unlike vanilla parts) so presumably the devs on AC assumed the `TODO:` would replace the `HAX:`. So a tweak to the workaround would be to check the template name, if it contains the parttype, then just use as is. If not, tag with the part type.

**Comment by sebastiantjfisher** [comment]
This is something I wrote to not deal with Added Part Names.  Let's me name any body part and doesn't require universally unique template names.. only unique within the body part type. 

In the localization file.. the line is this. So there is no dual arrays that need to line up.

+BodyPartNameConfig=(PartType="Helmets", TemplateName="DressGray_M", DisplayName="Tactical Fedora")
+BodyPartNameConfig=(PartType="Helmets", TemplateName="DressGray_F", DisplayName="Tactical Fedora")

Code is simple:

struct BodyPartInfo
{
	var string PartType;
	var name TemplateName;
	var string DisplayName;
};

var localized array<BodyPartInfo> BodyPartNameConfig;

static function Execute()
{
	local X2BodyPartTemplateManager templateManager;
	local X2BodyPartTemplate bodyPartTemplate;
	local BodyPartInfo info;
	templateManager = class'X2BodyPartTemplateManager'.static.GetBodyPartTemplateManager();
	
	foreach default.BodyPartNameConfig(info)
	{
		bodyPartTemplate = templateManager.FindUberTemplate(info.PartType, info.TemplateName);
		if(bodyPartTemplate != none)
		{
			bodyPartTemplate.DisplayName = info.DisplayName;
			continue;
		}
	}
}
