### ISSUE TITLE
Burn and acid damage configuration

### ISSUE THREAD

**Issue by ADVENTAvenger** [X2CommunityCore/X2WOTCCommunityHighlander#338]
Hello,

I would need a core override of the function CreateBurningStatusEffect and CreateAcidBurningStatusEffect in X2StatusEffects to allow exposing the complete value set (Burn per tick, Tick spread and Duration). Currently both functions cannot be overloaded, and some are even called directly by code like:

TileEnteredEffectsUncached.AddItem(class'X2StatusEffects'.static.CreateBurningStatusEffect(2, 1));

I need something that would completely ignore the function received values and use specified unified values in an INI file. Currently, only the duration is properly exposed.

My goal is to make fire damage less violent per tick (sometimes as high as 4-5 damage) and make it last longer (Tick for 1 over many turns).

**Comment by Iridar** [comment]
@ADVENTAvenger Hello. Is this issue still relevant to you? If not, please close it. In general, this seems a bit too specific for a highlander addition, and something that could be addressed relatively harmlessly via ModClassOverride.

**Comment by Iridar** [comment]
Closed due to author being MIA.
