### ISSUE TITLE
Permanent Crashes on avatars in the last mission

### ISSUE THREAD

**Issue by NorDogroth** [X2CommunityCore/X2WOTCCommunityHighlander#348]
I don't know if anyone knows why this happens nor if it makes sense to post it here …
When I'm playing the final mission of WOTC the game crashes every time an avatar takes damage, sometimes even when I tell a soldier to attack one. I'm playing on macOS with the updated Highlander. The game usually runs very constant without many bugs or crashes. 

This issue happened in earlier versions as well so it doesn't rely to the last updates. However, it's absolutly unplayable now. Do you guys have any idea about possible reasons or workarounds?

**Comment by Iridar** [comment]
Closing due to our apparent lack of interest in this poor soul woes.
