### ISSUE TITLE
Parts Validation on Torso Change

### ISSUE THREAD

**Issue by MrNiceUK** [X2CommunityCore/X2WOTCCommunityHighlander#350]
As well as updating based on the specific body part selection changed, `XComCharacterCustomization::OnCategoryValueChange()` validates related body parts, and switches them to valid parts. However, the validation on Torso changes is stuck in an Anarchy's Children release world, without the proliferation of other deco slots considered, most of which use FilterByTorsoAndArmorMatch so should be checked for validity on torso changes. Even for arm selection, it makes assumptions about validity which may be true with just the base game + AC, but may not hold for customized setups and mods. Specifically, it implicitly assumes that all  separate left/right arm part are valid for all Torsos, and also that if the current joint arms part is invalid, then all other joint arms parts must also be invalid, so immediately swaps to using separate left/right arms, which compounds the previous assumption that since left/right arms are always valid, there will be valid left/right arms to switch to.
In the worst case, where a new torso only has one set of valid arms which are not currently selected, changing to this torso won't automatically switch to them, because the above assumptions don't hold, yet you can't switch to them manually either, since slot selection is disabled for slots which only have one valid option (which the game implicitly assumes are already selected).
Also, there is inconsistent behaviour with forearm parts in general. Joint arms and left/right arms use the same Archetype, and both have a flag to hide forearm parts. In line with this, changing the currently selected forearm decos is also disabled if this flag is set (but the current setting is remembered for when switch to arms without this flag set). However, changing the selection of this slot is also disabled if join arms parts are selected at all. Any currently selected forearm decos are still shown though, if the flag is not set. In the base game, the Soldier character type has no forearm decos available, so this inconsistency doesn't show up without mods.

**Comment by Iridar** [comment]
@MrNiceUK is this issue still open only because it needs docs? If so, could you add some, please?
