### ISSUE TITLE
Add Sockets From Code for cosmetic armor

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#353]
Basically same thing as DLCAppendWeaponSockets() hook, but for cosmetic armor.

Would be used by Jet Packs mod to add sockets to cosmetic armor that looks like it has a Jet Pack on it.

It has to be usable on at least Torso and Torso Gear items, since that's where most of the jet pack-looking like things are equipped.

**Comment by Iridar** [comment]
Correction: for pawns, not the armor they wear.

**Comment by Iridar** [comment]
As I figured out later, it's already possible to use the existing `DLCAppendSockets()` hook to conditionally add sockets through code without the need to actually load the skeletal mesh with sockets. Example:
```
static function string DLCAppendSockets(XComUnitPawn Pawn)
{
    local XComGameState_Unit    UnitState;
    local SkeletalMeshSocket    NewSocket;
    local array<SkeletalMeshSocket> NewSockets;
    
    UnitState = XComGameState_Unit(`XCOMHISTORY.GetGameStateForObjectID(Pawn.ObjectID));
    
    // Maybe do something with UnitState
    
    NewSocket = new class'SkeletalMeshSocket';
    NewSocket.SocketName = 'AT4_Sling';
    NewSocket.BoneName = 'GrenadeLauncherSling';
    NewSocket.RelativeLocation.X = -12.553877f;
    NewSocket.RelativeLocation.Y = 7.512947f;
    NewSocket.RelativeLocation.Z = 20.879244f;
    NewSocket.RelativeRotation.Roll = -15.0f * DegToUnrRot;
    NewSocket.RelativeRotation.Pitch = 182.0f * DegToUnrRot;
    NewSocket.RelativeRotation.Yaw = -1.50f * DegToUnrRot;

    NewSockets.AddItem(NewSocket);
    
    Pawn.Mesh.AppendSockets(NewSockets, true);
}
```

**Comment by Xymanek** [comment]
The above snippet is missing a `return /**/;`

**Comment by Iridar** [comment]
> The above snippet is missing a `return /**/;`

Fixed, thanks.
