### ISSUE TITLE
Pawn is not updated correctly when some part changes only differ by override material

### ISSUE THREAD

**Issue by MrNiceUK** [X2CommunityCore/X2WOTCCommunityHighlander#354]
For helmets, this was broken by PR #272, which replaced a content comparison with a skeletal mesh comparison only, and did not include a material override comparison . For several arm related parts, they do not actually compare against the correct override, most likely from the code not being correctly updated from copypasta when Anarchy's Children introduced separate left/right arm parts and arm decos.

**Comment by MrNiceUK** [comment]
Sorry, the CHL appeared to have changed that ages ago! Someone please delete :P

**Comment by robojumper** [comment]
I believe this was fixed in #351 =)
