### ISSUE TITLE
UIAvengerHUD::UpdateResources doesn't account for MCOs

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#361]
In similar vain to #290 the resource bar doesn't consider subclasses and thus doesn't show up for MCO'd screens

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/50d24a1fe39bf32492ff28f82296dfb91b4adaaa/X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAvengerHUD.uc#L125-L133

**Comment by Iridar** [comment]
I'd handle this, if I knew how. Something tells me doing a mountain of `if( UIFacilityGrid(CurrentScreen.Class) != none) ... else if ()` is not the preferred solution.

**Comment by Xymanek** [comment]
> Something tells me doing a mountain of `if( UIFacilityGrid(CurrentScreen.Class) != none) ... else if ()` is not the preferred solution.

Indeed, the proper formatting is `if (UIFacilityGrid(...` (space before the parenthesis) 😝

Seriously though, personally I do not see a better solution. UC unfortunately doesn't support pattern matching
