### ISSUE TITLE
High use of BaseGameClass XComPathingPawn

### ISSUE THREAD

**Issue by ghost** [X2CommunityCore/X2WOTCCommunityHighlander#37]
Peek From Concealment and Gotcha Again require a really hacky patch to be compatible with one another that also requires an ini edit if they're not loading in the right order.

http://steamcommunity.com/sharedfiles/filedetails/?id=1136981000

Furthermore, Perfect Information, another popular mod, conflicts with this fix as well as Gotcha Again.

Would be cool if Highlander could help sort out this compatibility clusterfuck, specifically with XComPathingPawn.

**Comment by yoshimo** [comment]
I am looking forward to a fix for these two addons and similiar ones. It is the last conflict in my mod list that needs to be sorted out.

**Comment by robojumper** [comment]
The Highlander can't apply some magic fix -- in order to sort this out, the authors of the mods need to come forward, implement some changes in the Highlander, and then update their mods to make use of the new feature while removing the override.

**Comment by Iridar** [comment]
> The Highlander can't apply some magic fix -- in order to sort this out, the authors of the mods need to come forward, implement some changes in the Highlander, and then update their mods to make use of the new feature while removing the override.

Seeing as this doesn't seem to be a likely possibility, I'm gonna go ahead and close this issue. For what it's worth, the [Core Collection Meta Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2166295671) reliably resolves the MCO conflict between Gotcha Again and Peek From Concealment programmatically, and Perfect Information has been superseded by [Extended Information](https://steamcommunity.com/sharedfiles/filedetails/?id=1183444470), which doesn't have this compatibility issue.
