### ISSUE TITLE
Breakthrough bonus damage isn't shown

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#371]
Fallout from PR #262 (for Issue #237)

This code uses the new full weapon damage field in the struct:

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/50d24a1fe39bf32492ff28f82296dfb91b4adaaa/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc#L1396-L1403

While some code uses the scalar field

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/50d24a1fe39bf32492ff28f82296dfb91b4adaaa/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc#L1296

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/50d24a1fe39bf32492ff28f82296dfb91b4adaaa/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Item.uc#L1614-L1619

We should fix this to use the full struct field.

**Comment by MrNiceUK** [comment]
Wouldn't it be "safer" to consistently use the original field?
