### ISSUE TITLE
Add a flag to X2GrenadeTemplate to make some grenades not Launchable

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#372]
Would be used by my Rocket Launchers mod (in development) and Molotovs mod (released). 

It would require a change to **X2GrenadeTemplate** to add a bool var _CanBeLaunched_, which would be _true_ by default, and then add a piece of code to **GatherUnitAbilitiesForInit()** in **XComGameState_Unit** that would check if that flag is _false_ before adding the "Launch That Grenade ability" to the unit.

Normally it just checks if the ability is using _bUseLaunchedGrenadeEffects_ and if the item can be cast to _X2GrenadeTemplate_. Relevant code can be found at line number 4356 of **XComGameState_Unit**.

**Comment by RealityMachina** [comment]
My understanding of how the vanilla template classes are handled in native code is that this would be impossible with the method described.

A more doable method would probably be to add an event trigger around the given line number so a mod could manually stop Launch Grenade being added for a given item, if you don't want to try messing around with the `FinalizeUnitAbilitiesForInit` DLC hook to try removing the erroneous Launch Grenade ability that way.

**Comment by Iridar** [comment]
Ah, pardon. I don't have understanding of any kind. I'd be happy with any implementation that works.
