### ISSUE TITLE
Weapon swap bug when ambushed on covert mission

### ISSUE THREAD

**Issue by ghost** [X2CommunityCore/X2WOTCCommunityHighlander#38]
This was discovered just recently, I am posting it here because I think a Highlander mod might be able to fix it more elegantly than the hacky workarounds currently proposed.

Details here: http://steamcommunity.com/workshop/filedetails/discussion/1132835147/1474222595306563689/?tscn=1506142512#c1496741765133336770

**Comment by robojumper** [comment]
Would require an exensive rewrite of how unequipping items and applying class loadouts works.

Currently, it unequips all items, then equips the best available infinite loadout. This makes it always fall back to the same item type, and also makes it harder to check what kind of weapon was equipped previously.

**Comment by bountygiver** [comment]
so this happens because entering a squad select that does not allow wounded soldiers deployment strips all wounded/training/covert soldier's equipments, even if their covert can get ambushed. Fixed in newest update.

**Comment by Iridar** [comment]
> so this happens because entering a squad select that does not allow wounded soldiers deployment strips all wounded/training/covert soldier's equipments, even if their covert can get ambushed. Fixed in newest update.

Sorry, can you confirm the issue explained in the original post is no longer relevant? If so, please close this issue.

**Comment by Iridar** [comment]
Closing this issue, as it was fixed by an official patch.
