### ISSUE TITLE
Forced Appearance Issues

### ISSUE THREAD

**Issue by MrNiceUK** [X2CommunityCore/X2WOTCCommunityHighlander#384]
The `bForcedAppearance` Character Template flag relies on `XComHumanPawn::UpdateAppearance()`, which only updates the non-blank elements from the forced appearance. There's two issues however - one it was never updated to account for the new AC and WotC deco slots. Two, since it can't make a slot empty, means that Central for example may pick up deco slots in the generator! My solution would be for XGCharacterGenerator to leave the deco slots empty if bForcedAppearance is set.

**Comment by Iridar** [comment]
The PR that was supposed to close this issue has been merged to the live version of the Highlander. It remains open because it needs docs. Or somebody should make a decision that it doesn't need docs and close it.
