### ISSUE TITLE
Document technically breaking changes and their workarounds

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#385]
Adding new features or changing the behavior of existing ones is tricky because we're never 100% sure about the guarantees the existing feature made before. For example, there has been one case where the base game would accept some body part configuration, but we decided to make this configuration invalid and an error. When this caused issues in the wild, we provided an opt-out in #181. We already don't document our features very well, but this is something we definitely should document somewhere, especially since it caused issues [very recently again](https://steamcommunity.com/sharedfiles/filedetails/?id=1619292810).

```
// In the base game, XComGameState_Unit doesn't care about sliders all that much. However, the fix to
// handle sliders correctly has one problem -- mods may add part types for a specific armor and assign
// it a DLC Name. If those parts are the only valid ones, but the roll fails, we have invisible parts.
// Hence, we allow DLCNames to be specified here that are excluded by the chance roll and are always
// valid, effectively making them "vanilla" parts (parts without a DLCName)
```

**Comment by Iridar** [comment]
Could you please clarify what is the purpose of this issue? I believe great advances have been made in documenting Highlander features over the past year, majorly thanks to your efforts. Unless this issue has a purpose I'm not seeing, perhaps it can be closed?

**Comment by robojumper** [comment]
I think this can be closed with our documentation, especially the https://x2communitycore.github.io/X2WOTCCommunityHighlander/compatibility/ page.
