### ISSUE TITLE
Weapon attachment screen (basegame - cosmetic)

### ISSUE THREAD

**Issue by ProZeratul** [X2CommunityCore/X2WOTCCommunityHighlander#39]
I don't know if you noticed, but in base game the weapons used to move when you were in the attachment menu, this doesn't work anymore.

Every weapon seems to be affected by that (Spark also, but since there were not allowed to use attachment I suppose that Firaxis didn't code any movement for them.

To be more specific https://youtu.be/ISTbsrqpzgg?t=168 (this is just a random video on YouTube with attachment) so you can see what i mean when "weapon don't move"

**Comment by robojumper** [comment]
Can reproduce. The game now re-creates the weapon pawn for preview which immediately overrides the target PointInSpace tag.
