### ISSUE TITLE
Support dynamic colours for tactical HUD ability icons?

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#400]
The LW2 highlander modifies `UITacticalHUD_Ability.UpdateData()` (if I remember correctly — I don't have access to the source right now) so that it handles ability colours of "Variable". When it encounters a colour with that value, it triggers an event with an `XComLWTuple`. This allows the mod to use different colours for the same ability depending on various factors.

I'm wondering whether it makes sense to add the same or a similar feature to X2WOTCCommunityHighlander, or whether this should be handled in a completely different way.

**Comment by robojumper** [comment]
This is definitely something we'd accept in the Highlander.

**Comment by Iridar** [comment]
The PR that was supposed to close this issue has been merged to the live version of the Highlander. It remains open because it needs docs. Please add some :)

**Comment by Iridar** [comment]
@pledbrook I wanted to make docs for this issue, but while I was testing it I noticed the event only ever triggers for abilities that 
`if (IsObjectiveAbility || AbilityTemplate.AbilityIconColor != "")`

Can you please explain what is the reason for this restriction?

**Comment by robojumper** [comment]
Also see #750 for an attempt to rework this.

**Comment by Iridar** [comment]
> Also see #750 for an attempt to rework this.

Ok, thanks, I'll take that over.
