### ISSUE TITLE
Manual workaround for family-sharing crashes game

### ISSUE THREAD

**Issue by FreddyPeddy103** [X2CommunityCore/X2WOTCCommunityHighlander#403]
Im trying to get "Dual Wielded Pistols"  to work but animations do not work. i tracked this problem down to highlander not working(duh) because im playing using someone elses library through familyshare. However using the manual workaround listed on the troubleshooting page crashes the game and prevents me from reaching the main menu.

Steps Taken:
1. Clear .ini files and confirm that game works without highlander enabled
2. download highlander off of steam workshop
3. Manually install highlander by copying every file from \1134256495\CookedPCConsole\ and inserting them here \XCOM2 War of the Chosen\XComGame\CookedPCConsole\
4. Boot game and check ONLY highlander in the mod manager(s)
5. Crashes before start-cutscenes

i have tried both with vanilla and the alternative mod manager and also by manually changing what mods are active in config files.
Other mods work just fine aslong as they are not highlander dependencies.

**Comment by robojumper** [comment]
Can you check your log file to see if the companion package is loaded and prints information about the installed components? It should say something like:

    [0018.84] X2WOTCCommunityHighlander: Companion script package loaded
    [0018.84] X2WOTCCommunityHighlander: Components:
    [0018.85] X2WOTCCommunityHighlander:   X2WOTCCommunityHighlander -- v1.17.0
    [0018.85] X2WOTCCommunityHighlander:   Engine -- v1.17.0
    [0018.85] X2WOTCCommunityHighlander:   XComGame -- v1.17.0

(or no versions and the appropriate errors).

**Comment by FreddyPeddy103** [comment]
I can not see any resemblance of what you posted in my log files and but it clearly is providing me with some problem but im unable to completely understand the log file. [Launch.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/2809726/Launch.log)

I've had a previous problem with the game, where one of my game files (XComGame.exe) has been deleted either by some kind of bug or mistake, verifing does not replace this file and neither does reinstalling(Anti-virus disabled). To fix this problem i had to create symbiotic link between \XCOM 2 War of the Chosen\Binaries\Win64 and \XCOM 2 War of the Chosen\XCom2-WarOfTheChosen\Binaries\Win64 Could this in anyway mess with highlander starting/installing?

**Comment by FreddyPeddy103** [comment]
Not alot i can do to change it im afraid, living on a uni campus i have no control over what kind of network-wide AV they have and how opressive it is. And its not like there's someone online that just have a standalone download for XComGame.exe sitting around haha

**Comment by FreddyPeddy103** [comment]
Highlander is just a little inconsistent in reference to family-sharing it seems. 

I fixed the problem by getting access to the xcom account im sharing with and installing highlander(booting xcom2 once with the mod enabled) while im still logged into their account then just terminating the game.

I was then able to switch back to my own account and play xcom just fine(even with my previous scuffed bugfixing) and highlander and other mods functioned just fine. 

Thanks for the fast response even if it wasnt much help. 👍
