### ISSUE TITLE
Allow mods to add parallel soldier abilities, such as officer abilities, and have them displayed

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#409]
Much of XCOM 2's UI uses `XComGameState_Unit.GetEarnedSoldierAbilities()` to gain access to a soldier's current abilities, but it's hard-coded to only include class and AWC abilities. The officer ability tree is a parallel set of abilities, so soldiers' officer abilities aren't displayed in the main game.

The highlander should allow mods to add their own abilities. This would enable other systems, like allowing normal classes to also have psi powers, just as in XCOM 1.

**Comment by pledbrook** [comment]
I've realised there's a significant issue here: `XComGameState_Unit.HasSoldierAbility()` is native and appears to ignore what's in earned abilities. Long War 2 replaced the native function with an Unreal Script version to overcome the issue. Are there any other solutions? At the moment, `HasSoldierAbility()` and `GetEarnedSoldierAbilities()` are inconsistent with one another.

**Comment by Iridar** [comment]
Not sure why this was reopened, closing.
