### ISSUE TITLE
Add Greater Control for Gremlin "Ghosts" in Staffslots

### ISSUE THREAD

**Issue by VampireMonkey** [X2CommunityCore/X2WOTCCommunityHighlander#424]
I'll be working on making it possible to configure where and which slots should have ghost gremlins for [my mod here](https://steamcommunity.com/sharedfiles/filedetails/?id=1613189198)

**Comment by VampireMonkey** [comment]
Done : https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/428

**Comment by Iridar** [comment]
PR that was supposed to close this issue has been murdered, and seemingly so has the mod linked in the issue. I assume this is issue is no longer relevant, so I'm closing it. Feel free to reopen, if necessary.
