### ISSUE TITLE
crash before load any save after activate X2WOTCCommunityHighlander

### ISSUE THREAD

**Issue by oktadia** [X2CommunityCore/X2WOTCCommunityHighlander#430]
cant enter main menu, what to do pls help tyvm >< (me nob new to modding, xcom2 and wotc)

**Comment by Dragon-32** [comment]
Some great [Mod Troubleshooting](https://www.reddit.com/r/xcom2mods/wiki/mod_troubleshooting) advice.

That recommends the excellent [Community Mod Launcher](https://github.com/X2CommunityCore/xcom2-launcher), which everyone who uses mods should be using.

This guide gives some more detailed advice on using the Community Mod Launcher: [Troubleshooting: Mods not working properly / at all](http://steamcommunity.com/sharedfiles/filedetails/?id=683218526)

If you've just switched from the Firaxis Launcher, or are forced to use it, read the "Mods not activating/deactivating properly in WOTC" section of [Mod not working? Mods still have their effects after you disable them?](http://steamcommunity.com/sharedfiles/filedetails/?id=625230005)
