### ISSUE TITLE
Fresh installation + Highlander crash.

### ISSUE THREAD

**Issue by mnnglss** [X2CommunityCore/X2WOTCCommunityHighlander#433]
My specs: Ryzen 1700 + Nvidia 1070 Ti

So, I use around 90 mods and no conflicts there, wanted to add the Detailed Soldier Lists mod which needs Highlander and didn't work, simple crash after start up movies or before.

Tried many things, including 3 different mod managers, erasing documents xcom folders, REINSTALLING the whole game again in another directory/drive and all this with just this mod, 2 mods or the whole list and the problem persist:

- vanilla wotc game loads fine
- wotc + all mods except highlander loads fine
- wotc + highlander not

Also tried with version 1.16 and in that case game loads fine except I can't see the notification on the right corner and with Detailed Soldier Lists game crashes entering barracks.

Does the mod relies on Nvidia Physx or any kind of system DLL?

**Comment by robojumper** [comment]
Please try our [troubleshooting steps](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting) first. Thanks.

**Comment by Xymanek** [comment]
First of all, Detailed Soldier Lists doesn't need the highlander.

> 3 different mod managers

hmmm.... I know only 2 - stock one and AML

> wotc + highlander not

This is very weird - especially on a freshly installed game. Try unsubscribing on workshop, rebooting your pc and subscribing on workshop again

**Comment by mnnglss** [comment]
> Please try our [troubleshooting steps](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting) first. Thanks.
 
That's already done. Refreshing .ini files? Deleted the whole folder.
Other versions? Reinstalled the whole game, deleted the whole folder and tried on different directories and drive.
The text does not appear? Well, I can assure you I enabled the mod on every launcher I tried.


> First of all, Detailed Soldier Lists doesn't need the highlander.
> 
> > 3 different mod managers
> 
> hmmm.... I know only 2 - stock one and AML
> 
> > wotc + highlander not
> 
> This is very weird - especially on a freshly installed game. Try unsubscribing on workshop, rebooting your pc and subscribing on workshop again

Sorry, my bad, the mod I wanted was Extended Personnel Info.

Mod managers: vanilla, aml, nexus mod manager and vortex(beta) from nmm too.

Already tried unsubscribing and also downloading the mod from http://xcom2.smods.ru and installed it manually in case it was somehow corrupted.

**Comment by mnnglss** [comment]
Solved it applying the /src, /CookedPCConsole, /Localization, etc by myself in the corresponding folder, the script doesn't work on my system apparently. ¿? Now game is correctly working with every mod.

**Comment by CuriousLaika** [comment]
> Solved it applying the /src, /CookedPCConsole, /Localization, etc by myself in the corresponding folders, the script doesn't work on my system apparently. ¿? Now game is correctly working with every mod.

im having the same issue, tried many fixes yet still crashing. so i wonder how did u done it? what does it mean by applying the /src, /cookedpcconsole, /localization by urself?
