### ISSUE TITLE
Add Array to RawInputHandler

### ISSUE THREAD

**Issue by VampireMonkey** [X2CommunityCore/X2WOTCCommunityHighlander#442]
RawInputHandler is a great tool for listening to inputs without overriding the panel-class you'd want to listen to, the main problem with it is that it's 1 single instance per control, meaning that you'd have to do some shenanigans to not block the base game or other mods from using it.

Having an array means any number of mods can listen to the same control without blocking or overriding eachother.

I'll set this here as a reminder and will get back to actually implementing it later. 

Rawinputhandler can handle both keyboard and mouse, and controller inputs.

**Comment by Iridar** [comment]
Closing due to passage of time.
