### ISSUE TITLE
Add more inventory slots for Rocket Launchers and Pistol

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#469]
Added new inventory slots to X2TacticalGameRulesetDataStructures. Four of them are for the upcoming Rocket Launcher mod:

eInvSlot_ExtraRocket1,
eInvSlot_ExtraRocket2,
eInvSlot_ExtraRocket3,
eInvSlot_ExtraRocket4,
eInvSlot_Pistol,

And one dedicated slot for carrying a pistol without having to rely on Secondary - eInvSlot_SeptenaryWeapon weapon slots, so the Veehementia's Dedicated Pistol Slot can live without fear of conflict.

**Comment by BlackDog86** [comment]
Connected to Issue #137
