### ISSUE TITLE
XCOM2 WotC - game crashes (even when this mod is the only one)

### ISSUE THREAD

**Issue by Crusader2010** [X2CommunityCore/X2WOTCCommunityHighlander#470]
Hi,

My game always crashes after the first intro screens, right before the main menu interface should get loaded (and right before the main menu music should start). I tried loading it with many other mods, but there is no difference. If I disable this mod, all of the others work properly (haven't started a game, but can, at least, get to the main menu).

My "DefaultModOptions.ini" file looks like this:
```
[Engine.XComModOptions]
ActiveMods="X2WOTCCommunityHighlander"
```

I'm also attaching the crash log file.
[XCom-CL374751-2019.04.08-19.37.21_Logfile.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3055422/XCom-CL374751-2019.04.08-19.37.21_Logfile.log)

If you also need the minidump let me know.

Thanks

**Comment by robojumper** [comment]
Hi,

please follow our [Troubleshooting instructions](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting). I will close this issue because I believe they will resolve your problem; if not, ping me to reopen.

**Comment by Crusader2010** [comment]
I seem to have missed the last step from that. This fixes the problem!!
Thank you very much and sorry for being blind :(
I'll leave this here for many other people that I saw having the same issue:

```
The latter problem has been reported to be circumvented by copying all files from

<Steam>\SteamApps\workshop\content\268500\1134256495\CookedPCConsole\

or your respective installation location to

%USERPROFILE%\Documents\My Games\XCOM2 War of the Chosen\XComGame\CookedPCConsole\
```
