### ISSUE TITLE
Make AbilityRequiresTargetingActivation()/IsTargetingMethodActivated() use a configurable list

### ISSUE THREAD

**Issue by MrNiceUK** [X2CommunityCore/X2WOTCCommunityHighlander#476]
(Controller Support)

UITacticalHUD_AbilityContainer.AbilityRequiresTargetingActivation does this:
```
if (ClassIsChildOf(AbilityState.GetMyTemplate().TargetingMethod, class'X2TargetingMethod_Grenade') ||
	ClassIsChildOf(AbilityState.GetMyTemplate().TargetingMethod, class'X2TargetingMethod_Cone') ||
	ClassIsChildOf(AbilityState.GetMyTemplate().TargetingMethod, class'X2TargetingMethod_Line') ||
	ClassIsChildOf(AbilityState.GetMyTemplate().TargetingMethod, class'X2TargetingMethod_BlasterLauncher'))
{
	return true;
}
```
`IsTargetingMethodActivated()` does similar. These functions indicates that after selecting the ability, you have to press A again to aim the ability, which allows the user to rotate the camera with the buttons that would normally cycle the ability selection.
However, this skips some TargetingMethods -- RocketLauncher, for example is a Grenade, but grappling and BlazingPinions are not covered by the list. Making this list configurable would allow a more consistent behaviour.

**Comment by mburbea** [comment]
I think it makes sense to fold the useful missing ones Grappling, Blazing Pinions, and Pathtarget into the highlander.
