### ISSUE TITLE
Linux Crash

### ISSUE THREAD

**Issue by notfood** [X2CommunityCore/X2WOTCCommunityHighlander#48]
If I enable only this mod, XCom2 will crash with a segmentation fault. No log produced, only a few Config files created. There is a dump file.

[2f9b2726-120d-fc4a-7c5f7b7b-1fad17b5.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/1336286/2f9b2726-120d-fc4a-7c5f7b7b-1fad17b5.zip)

**Comment by robojumper** [comment]
Hi notfood,

thanks for your report. We are aware of a similar issue on MacOS (#40) and are currently investigating. Over at #40, we have a "blank" highlander that is the vanilla highlander without changes, just that we cooked it ourselves. Can you help us by trying the steps there?

**Comment by MalucoMarinero** [comment]
[X2WOTCCommunityHighlanderLinux.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/1387137/X2WOTCCommunityHighlanderLinux.zip)

So I have this working if I unzip the file inside to SteamLibrary/steamapps/common/XCOM 2/share/data/xcomgame/mods

I tried it with one of my dependant mods and works without crashing with correct behaviour if you want to try it out on your install. If I get some confirmation I'll work towards cutting a Workshop release.
