### ISSUE TITLE
New Patch broke my game (apparently is a mod conflict)

### ISSUE THREAD

**Issue by HarnischtheTrue** [X2CommunityCore/X2WOTCCommunityHighlander#49]
Since the new patch i cannot use the mod i figured out only today after a week of testing what mod was crashing my game every time i was going in battle (WIn 10)

**Comment by Musashi1584** [comment]
So you ran the game with just the highlander and no other mods and it crashed?

**Comment by HarnischtheTrue** [comment]
Hi Musashi, (i'm a great fan of your mods), sorry my previous statement was wrong i probably find a conflict tho, i will search what it is but i need some time to check the other 199 mods... (i'll change the title of the post)

**Comment by HarnischtheTrue** [comment]
For my first check it seems to be HQ Animations, even if it works in the customization screen and on the avenger it seems when you go to battle and use highlander it crashes (without highlander it works even in battle). I hope it is only this i will test more mods tomorrow.

**Comment by Musashi1584** [comment]
HQ Animation is not updated for WotC and should not be used with WotC or the WotC Highlander.

**Comment by MalucoMarinero** [comment]
closing
