### ISSUE TITLE
Port CanAddItemToInventory hook from base game highlander + add UI support for it

### ISSUE THREAD

**Issue by RealityMachina** [X2CommunityCore/X2WOTCCommunityHighlander#50]
This was a useful function added in `X2DownloadableContentInfo` to allow mods to define their own rules for certain items, as to let them be equipped by certain types of units if the standard rules couldn't cover the intended usage.

That said, a weakness of it was that there was no way to _tell_ the user why they couldn't equip an item, and this could cause misidentifications of a bug.

This could be resolved by expanding on `GetDisabledReason()` in `UIArmory_Loadout` to include another DLC hook, something like `HaveDisabledReasonForItem()`, where a mod could send back a string if it's disabling the current item being checked from being equipped for that unit.

**Comment by robojumper** [comment]
This makes me wonder why the code that returns the DisabledReason is in the UI class and not in XComGameState_Unit. Maybe create an expanded function CanAddItemToInventory_CH that optionally returns the reason it fails (out param) and keep the old one as a wrapper? We could then do with one DLC hook that overrides the "can equip" result as well as providing a fail reason.
