### ISSUE TITLE
Improve custom keybinds usability

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#501]
#198 introduced a hook for custom keybinds, but using it relies on an UISL switching the input function on/off in all 4 events. This is a lot of boilerplate, especially when the input function is not required for every instance of the screen (afaik lwotc project had something like that).

I propose adding `SCREENSTACK.RegisterOnInputForScreen(Screen, Delegate)`. The delegate would be evaluated before the screen itself is given an option to handle the input, right after

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/b9bd25d416760648b572c3f6e095531ac0ff48b6/X2WOTCCommunityHighlander/Src/XComGame/Classes/UIScreenStack.uc#L86-L95

When the screen is removed, all associated callbacks would be removed

**Comment by MrNiceUK** [comment]
Could put it *before* the `Screen.AcceptsInput()` check really?

**Comment by Xymanek** [comment]
Hmmm... I actually had it before it that initially but then moved under *cuz it seemed important™️*. I guess it makes sense to trigger the callbacks before that and let the mods handle that check if they care.

Also I think it makes sense to add `Screen` argument to the delegate - usually you end up pulling it from stack anyway

**Comment by MrNiceUK** [comment]
Ah right, didn't get the significance of it being the loop where it finds the top most screen which is taking inputs... ok guess that makes sense then... (if a mod wants to be esoteric and "listen in" on screens which *don't* themselves accept input, can just do it with the existing UISL approach)

**Comment by Xymanek** [comment]
> loop where it finds the top most screen which is taking inputs

If the top screen didn't handle the input (and does not block input from propagating down the stack) the screen stack will attempt to handle the input by lower-level screens. the proposed hook will also be called if a screen is up for evaluating input even if it's not the top one.

> if a mod wants to be esoteric and "listen in" on screens which don't themselves accept input, can just do it with the existing UISL approach

yeah, this is just a shortcut for common functionality to reduce boilerplate. We are not adding a new feature/locking mods out of some possibility

**Comment by Xymanek** [comment]
cc @robojumper any input?
