### ISSUE TITLE
Allow mods to override patrol behaviour

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#507]
`XComGameState_AIGroup.ShouldMoveToIntercept()` controls patrol behaviour for pods, but some mods (read LW2) may want to manage patrol routes and behaviour themselves. There should be an event that allows mods to disable/bypass the default patrolling logic.

**Comment by Xymanek** [comment]
How this will work with `BattleData.bKismetDisabledInterceptMovement`?

**Comment by pledbrook** [comment]
I trigger the event after the condition that checks `BattleData.bKismetDisabledInterceptMovement`. So if that boolean is false *and* XCOM has passed a pod, then the intercept behaviour operates as normal and there is no patrolling for that pod. Otherwise, this event triggers and allows mods to bypass the normal pod patrol logic.

**Comment by Xymanek** [comment]
> if that boolean is false 

I'm mostly interested in the reverse

**Comment by pledbrook** [comment]
That's covered by the "otherwise". If the boolean is true, then intercept behaviour is disabled and the code goes through the normal patrol logic. In that case, the override event is triggered and mods can say "no, please don't patrol, I'll handle it."
