### ISSUE TITLE
Create a DLCInfo loadorder system

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#511]
By adding 
```
function array<string> GetRunBeforeDLCIdentifiers();
function array<string> GetRunAfterDLCIdentifiers();
```
we create directed acyclic graph (dag) of mod dependencies.

Implement in a mod it would look like

```
[ModPackage.X2DownloadableContentInfo_MyMod]

DLCIdentifier="MyMod"
+RunBefore="OtherMod"
+RunAfter="AnotherMod"
```
```
class X2DownloadableContentInfo_MyMod extends X2DownloadableContentInfo config(ModConfig);
var config array<string> RunBefore;
var config array<string> RunAfter;

function array<string> GetRunBeforeDLCIdentifiers()
{
	return default.RunBefore;
}

function array<string> GetRunAfterDLCIdentifiers()
{
	return default.RunAfter;
}

```
With subclassing `XComOnlineEventMgr` and intercepting `GetDLCInfos` it is possible to reorder the dag of DLCInfo classes using topological sorting.

This results effectively in a order control for dlcinfo hooks like `OnPostTemplatesCreated`.

**Comment by Xymanek** [comment]
> With subclassing `XComOnlineEventMgr`

This is effectively an MCO, which CHL is supposed to avoid. Is this something we are willing to break in this case?

**Comment by Musashi1584** [comment]
not really, its implemented by

XComEngine
```
defaultproperties
{
	OnlineEventMgrClassName = "XComGame.CHOnlineEventMgr"
}
```

**Comment by Xymanek** [comment]
This is still a class-level replacement, effectively an MCO, regadless of how it's implemented. If there is another mod out there that MCOs `XComOnlineEventMgr`, it will break

**Comment by robojumper** [comment]
> This results effectively in a order control for dlcinfo hooks like OnPostTemplatesCreated.

Native to native function calls cannot be intercepted by script. This would work for all non-native hooks, but we can change the order there without creating a new OnlineEventMgr already. Maybe investigate whether the OnlineEventManager maintains an array of X2DownloadableContentInfo objects you can sort, and whether we have a good place to do it (after bootstrapping the OnlineEventMgr, before creating templates)?

**Comment by Musashi1584** [comment]
Lets take this to the discord guys.

**Comment by Xymanek** [comment]
Relevant note: I've tried to MCO `RedScreenManager` but it wouldn't work, suggesting that MCOs may not work during engine init. If we confirm that it's the case indeed (for online event manager at least) then this concern can be rescinded

**Comment by Xymanek** [comment]
Why is this still open?
