### ISSUE TITLE
Powershell build script appends `PropertyGroup PropertyGroup` to mod name in `.XComMod` file

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#513]
~~Removed it manually for 1.18~~ [EDIT: The reupload now contains it again >.>], but I'd like this fixed. cc @Aleosiss you said you fixed this somewhere in one of your projects?

**Comment by abatewongc** [comment]
propertyGroup is a powershell property. There must be some invalid variable interpolation going on, I'll compare the scripts for the Highlander and The Program and submit something in a bit.

**Comment by robojumper** [comment]
This was fixed in #514 (which was filed against master but merged into beta)
