### ISSUE TITLE
v1.18.0 skips Skyranger and other cutscenes

### ISSUE THREAD

**Issue by gitTon1** [X2CommunityCore/X2WOTCCommunityHighlander#516]
Hi all,

First of all thanks for making this mod.

Apparently, v1.18.0 of the Highlander skips the Skyranger drop-in cutscenes and also skips the story-related cutscenes (like in the Lost & Abandoned mission).

Tested with a clean a install running only the Highlander. Attached is my launch.log:
[log.txt](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3170489/log.txt)

Downgraded to v1.17.0 and did not experience this behavior.

Going off a hunch I think it's related to #395, but I ain't no expert.

Hope you will resolve this soon!

**Comment by robojumper** [comment]
Ah Christ, that looks like a missing return value that the the compiler doesn't warn about because it doesn't do any control flow analysis for returns. Opened #517 with the fix, will merge, build and upload shortly.

**Comment by gitTon1** [comment]
Thanks for the quick response and fix! You can close this issue whenever you feel it's resolved.

**Comment by robojumper** [comment]
The fix was merged and released as v1.18.1 on GitHub and the Steam workshop. Thanks for the report and for identifying the PR with the bug; Sorry about the issue. We are having a discussion about finding ways to improve our test coverage for future changes.
