### ISSUE TITLE
Allow mods to enable "no ca" nag in event queue month 0

### ISSUE THREAD

**Issue by statusNone** [X2CommunityCore/X2WOTCCommunityHighlander#518]
need to bypass `if (!bActionFound && (ResHQ.NumMonths >= 1 || bRingBuilt))` in XComGameState_HeadquartersXCom::GetCovertActionEvents

**Comment by pledbrook** [comment]
What's the intent behind this change? As it stands, setting the number of months to more than 1 causes issues if a player skips assigning the once-per-supply-drop covert action during the end-of-month processing, as the link to assign a covert action disappears.

**Comment by Xymanek** [comment]
> What's the intent behind this change?

Exactly what it says in the title - Allow mods to enable "no ca" nag in event queue month 0

> setting the number of months to more than 1 causes issues [...]

I think nobody considered what would happen if that was done when implementing this feature
