### ISSUE TITLE
Allow mods to define required and incompatible mod dependencies

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#524]
I suggest adding two new functions to the DLCInfo

```
function array<string> GetIncompatibleDLCIdentifiers();
function array<string> GetRequiredDLCIdentifiers();
```

These can be overriden by mods DLCInfo classes to define dependencies and incompatiblities.
The would be then checked in a shell screen listener that displays the results to the player-

**Comment by Xymanek** [comment]
Why is this still open?
