### ISSUE TITLE
Make sure civilians run from XCOM on unconcealed missions

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#548]
If XCOM starts a mission unconcealed with hostile civilians on it, those civilians will just walk away from XCOM soldiers when they come near rather than run. Not only does that slow down the action, but it also seems really weird and breaks immersion hard.

**Comment by pledbrook** [comment]
This was implemented in LWOTC itself.

**Comment by Xymanek** [comment]
How did you implement it?

**Comment by pledbrook** [comment]
A [template modification](https://github.com/long-war-2/lwotc/commit/ecef266f1f3ce16d0220e10f2812302765b4fea1) of the 'CivilianPanicked' template.

**Comment by pledbrook** [comment]
I think the current implementation doesn't handle the approach of red alert enemy units though. Probably need to add that as a trigger.
