### ISSUE TITLE
Crashing on Mission Start

### ISSUE THREAD

**Issue by DoctorSlamtasm** [X2CommunityCore/X2WOTCCommunityHighlander#56]
I've got quite a few mods however using the Highlander and Fulton Extraction Mods seem to be crashing it every time I start a mission. if this has already been resolved please show me.

**Comment by MalucoMarinero** [comment]
we'll need some logs to properly follow this up, ideally coupled with a minimum set of mods required to pull out the crash

**Comment by DoctorSlamtasm** [comment]
I have a lot of mods so I don't know what might be causing it however I'll send the crash log and anything else you may need

[XCom-CL302202-2017.10.05-23.18.26_Logfile.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/1361460/XCom-CL302202-2017.10.05-23.18.26_Logfile.log)

**Comment by DoctorSlamtasm** [comment]
also the mods I use are WOTC and are Unblockable Flamethrowers Brutal Fix Restored Sit-Reps non-skirmisher Advent Hybrids Fulton Rewards Extract Corpses your highlander Additional Icons Gotcha Again Cinematic Rapid-Fire Turrets are Cover Reliable volunteer army and double agents better double agents Birthdates Even more backstories insider knowledge fix Peek from concealment UI peek from concealment Destroyer's Female Hair Pack always recruit and rescue defense matrix sabotage fix additional dark actions restored chosen traits buildable hunter weapons chosen dark events fix Fair lost targeting Lost World Fix Tracking Shot Defense Recruit multiple heroes from all factions Skirmisher re-balance Rend the Lost More Resistance Ops Covert action missions Scientist staff slots Revival protocol fix More Traits cutcontentammo avatar buff DLC breakthrough Supports Additional mission types redux supply extraction fix blademaster momentum Gravely wounded Scars Increased Cover bonus Recruits conserve character pool lost autofire Expose chosen weakness The MocX initiative Missing Packages fix Limitless armor options aditional invisible parts empty deco slots for XCOM Unrestricted Customization Overflow Ability Points Not enough Skirmishing Mod Everything reloaded Edited Ragdoll Physics and Effects SWR full crew avenger More Cities Resistance firearms Assets and Module High Ground gives defense Assassin's swordsmanship improved camera rotation config loot mind control Robojumper's Squad Select mod config menu Darkclaw ammo fix Invisible psi amps color coded bonds Metal over Flesh redux show health values katana pack Maps by Vozati and Stop wasting my time

**Comment by DoctorSlamtasm** [comment]
Nevermind I found the problem it was a few outdated and conflicted mods like robojumper's squad menu

**Comment by DoctorSlamtasm** [comment]
I lied it started working earlier only to do it again

**Comment by ukarjohn** [comment]
I have been having the same issue - Crash on mission start.  It seemed it was related to Squaddie Skills - I started 6 games with this mod and all crashed in the first few missions.  I removed it and am now on mission 43, but I am now crashing on this mission.

Also, I just started having a bug where all armors and weapons show up in the loadout screen for every character. I wonder if this is related to the highlander update.  I think characters can only equip their allowed gear, but the list is now very confusing.

Please help.

**Comment by ukarjohn** [comment]
Here is the most recent crash log:

[Launch.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/1586417/Launch.log)

**Comment by robojumper** [comment]
@ukarjohn 

`Also, I just started having a bug where all armors and weapons show up in the loadout screen for every character.` 

Generally, all equipment should be shown, but the items the character can't equip should be disabled. I am guessing this is not working and all items are shown as available.

I believe this is an unforeseen consequence of a change in the 1.6 release that causes interference with outdated mods. It would help if you could do an in-file search in your workshop mod directory for `CanAddItemToInventory_CH` and list the mods that contain it -- they will need updating to work properly.

**Comment by ukarjohn** [comment]
@robojumper  I'm working on this now

**Comment by ukarjohn** [comment]
@robojumper  I think I don't know how to do the search.  I went to D:\SteamLibrary\SteamApps\workshop\content\268500 on my computer and searched "in file" for the string you gave, but I got no hits. Can you advise a test to confirm the search was performed correctly? Thanks.

**Comment by RealityMachina** [comment]
You want to edit Windows Search so it considers .uc files valid text files.

[This is a guide for how to do so in Windows 7](https://www.wikihow.com/Make-Windows-7-Search-File-Contents), though it only needs minimal modification for Windows 10.

**Comment by ukarjohn** [comment]
@RealityMachina @robojumper  Thanks - I got three hits in Highlander, and one each in MetalOverFleshRedux, SPARKLaunchersRedux and LatentPsionicsUnlock.

**Comment by ukarjohn** [comment]
@robojumper  I just tested some - I can still get into the Geoscape; it crashes if I launch a mission.  But in terms of equipping, if I try to change equipment in the armory, I still see all armors and weapons (none marked unequippable as they used to be), but it only lets me equip allowed gear.

Is there a way to roll back my Highlander till other mods are fixed? It was working up until 4:20 pm yesterday, and not since.  Thank you!

**Comment by MalucoMarinero** [comment]
@ukarjohn if you're looking to roll back the highlander, unsubscribe to the workshop version and replace it with your desired version: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/releases

We keep all past build versions of Highlanders there, although the much older ones won't play nice with the recent WOTC patches.

**Comment by Iridar** [comment]
Does this issue serve any purpose at this point? Doesn't seem like it belonged here in the first place. Probably should be closed.
