### ISSUE TITLE
Allow mods to show min damage previews rather than max

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#579]
Although mods like Extended Information can hack the behaviour of the damage preview, they can't do it for all scenarios. For example, right-click Fleche attacks in LW2. Plus, it seems clear that a simple hook in `UIUnitFlagManager` to allow mods to display minimum damage preview is the cleanest solution all round and the obvious place to override the default behaviour.

**Comment by Iridar** [comment]
A hook? If this is meant to be a global switch that affects damage preview on unit flag of all abilities at the same time, a var config bool switch would probably be more appropriate.

**Comment by pledbrook** [comment]
But if you have two mods with differing opinions on whether to show minimum or maximum (or even average) damage, then config var has an inconsistent result based on load order.

**Comment by Iridar** [comment]
> But if you have two mods with differing opinions on whether to show minimum or maximum (or even average) damage, then config var has an inconsistent result based on load order.

Sure, although I'd blame the mod user at that point.
