### ISSUE TITLE
Add more data types to `XComLWTuple`

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#590]
Add the following data types to `XComLWTuple`:

* `Vector`
* `Rotator`
* `TTile`
* Array of `Object`
* Array of `int`
* Array of `float`
* Array of `string`

**Comment by Musashi1584** [comment]
Might also be useful:

Arrays of rotator, vector, ttile, name

**Comment by pledbrook** [comment]
Is it sensible to simply dump a load of variables into `XComLWTValue`? I assume these are all taking space when not being used. If folks think it's fine, happy to add as many as makes sense.

**Comment by Musashi1584** [comment]
Dont think that it would have any significant memory or perfomance impact to have a few variable declared that dont get used.

**Comment by Iridar** [comment]
@robojumper are we sure this issue needs docs? It seems XComLWTuple is already well documented.
