### ISSUE TITLE
Allow PCS granting PsiOffense to be equiped by other classes than PsiOperative

### ISSUE THREAD

**Issue by boundir** [X2CommunityCore/X2WOTCCommunityHighlander#602]
`CanEquipImplant()` specifies if units is allowed to equip PCS. So far it forbid units to equip PCS granting PsiOffense on any other class than PsiOperative.
I would like to change this to allow units with PsiOffense to be able to equip it.

Class: UIInventory_Implants

**Comment by Xymanek** [comment]
Please note that despite the rather extensive mentions spam above this comment, this issue is **not** implemented - there were several candidate PRs, some were even merged, but then they were reverted in #721 due to outstanding issues with the implementation
