### ISSUE TITLE
`XCGS_Unit:EquipOldItems` does not apply color and pattern to unmodified items

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#609]
See https://github.com/long-war-2/lwotc/issues/420

Sending a soldier to a covert action without ambush risks unequips a colored weapon, stacks it with the existing stack in HQ. Re-equipping decides that a new copy needs to be made from the infinite stack, but doesn't apply customization to it.

**Comment by MrNiceUK** [comment]
With both the unit and the weapon themselves having weapon customizations stored, I saw some of the messiness with the logic for keeping them in sync (or not!) when addressing Gremlin customizations, but at that point didn't want to touch it! Possibly means the gremlin may be inconsistent about whether it's using the *weapon* stored customization colours or the units (if they are different) too...

**Comment by Iridar** [comment]
Note that at the end of EquipOldItems there's ApplyBestGearLoadout() which does apply weapon customization from soldier appearance.

**Comment by Iridar** [comment]
This could be fixed in `EquipOldItems()`, but it could also be fixed for good in `AddItemToInventory()`, where it arguably should have been all this time. What's the point of even storing weapon customization on Unit State if you're not gonna apply it to all weapons you equip?

**Comment by Iridar** [comment]
With one exception of modified items, e.g. nicknamed/upgraded.
