### ISSUE TITLE
Change private functions and variables inside XComPathingPawn to protected

### ISSUE THREAD

**Issue by CGNick** [X2CommunityCore/X2WOTCCommunityHighlander#615]
The class itself is already all over the place when it comes to making variables and functions public/protected/private. If it's too much of a hassle to unprivatize everything, I would specifically like to see the following vars and function become protected, if not public:

Vars:
- VisualPath (protectedwrite)
- PathTiles (protectedwrite)
- PathTileData

Functions:
- UpdateBorderHideHeights
- UpdatePath
- UpdatePuckFlyovers
- UpdatePuckAudio

**Comment by Iridar** [comment]
Closing for the same reason as #811. If you need to unprivate things for your personal use, you should do it locally.
