### ISSUE TITLE
Allow abilities to be added to the "XCOM" pool when they exist in the soldiers randomized ability pool

### ISSUE THREAD

**Issue by Brood** [X2CommunityCore/X2WOTCCommunityHighlander#62]
Note: This should only add those abilities that hasn't been populated in the ability tree.

**Comment by Iridar** [comment]
I'm confused. `ExtraCrossClassAbilities` is the base game functionality for WOTC. So what does this issue address? Allows abilities to be selected as random cross class perks if the ability template has `bCrossClassEligible`, and it is listed in a RandomAbilityDeck for some class, even if it is not listed in `ExtraCrossClassAbilities`?

**Comment by Iridar** [comment]
Looks like this issue is already implemented and commentated, the comments just need to be updated to be recognized as HLDocs.
