### ISSUE TITLE
Shaken soldiers can recover in 1 day

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#637]
To understand why this is happening, one has to look at the two algorithms used to determine whether a soldier is Shaken or not.

Consider a soldier with a max will of 56 and a current will of 19 at the end of a mission. `XCGS_Unit.UpdateMentalState()` first determines the percentage of max will that the soldier currently has:
```
WillPercent = int(100 * (CurrWill / MaxWill))
```
It then compares that to the max will percentage that corresponds to Shaken: 33%. So, 19 ÷ 56 = 0.3393, which when multiplied by 100 and truncated becomes 33. As that matches the max will percentage for Shaken, the solider is Shaken.

Then the game sets up the will project. This time, the calculation is different:
```
MaxWillForShaken = int(0.33 * MaxWill)
BlocksRemaining = MaxWillForShaken - CurrWill
```
Plugging the same numbers in, we get 0.33 * 56 = 18.48, which truncated becomes 18. So the will project doesn't think the soldier is Shaken since 19 > 18.

The second calculation uses `XCGS_Unit.GetMaxWillForMentalState()`, which is inconsistent with `XCGS_Unit.UpdateMentalState()`. I suggest changing `UpdateMentalState()` to _use_ `GetMaxWillForMentalState()` so that there is consistency, which will fix this bug.

**Comment by MrNiceUK** [comment]
What about when `CurrWill == MaxWillForShaken`?

**Comment by pledbrook** [comment]
If `CurrWill == MaxWillForShaken` then BlocksRemaining is 0. The will recovery project then adds 1 for non-ready mental states, so blocks remaining should always be at least 1.

But with the above example, blocks remaining is -1, which gets incremented to 0, which then leads to a division by zero. And we all know that that's a good idea.

**Comment by MrNiceUK** [comment]
Ah ok, so it already does a bit of fudging for that edge case 👍
