### ISSUE TITLE
Stun "effect" continues after mind control ends

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#643]
Here's the scenario: an enemy unit mind controls one of your squad. You then stun that squad member so that they can't do any harm during XCOM's turn. If the mind control effect then wears off before the stun effect, the stunned soldier remains in a "stunned" state (both visually and ability-wise), but can move. And the stunned state is never removed.

To reproduce, load up the following save (requires LW2 Secondaries and Skirmish+ mods), end the turn and see what happens to the mind controlled Grenadier:

[save_BUG Stun and mind control.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3685321/save_BUG.Stun.and.mind.control.zip)

The problem is that `XCGS_Effect.OnGroupTurnTicked` is tied to the player who was in control of the unit at the point that the stun was applied. When the mind control wears off, the player changes back to XCOM and the listener stops firing. On top of that, the listener uses a filter of the `XCGS_AIGroup` which also changes. So there are two reasons it doesn't fire.

**Comment by pledbrook** [comment]
Interestingly, if you flashbang the Elite Priest, the mind control is lost and the Grenadier has full actions. The bug only seems to surface if the mind control effect just comes to a natural end.

**Comment by Xymanek** [comment]
Flashbang explicitly cancels MC effect, I don't think it even touches the ticking code

**Comment by pledbrook** [comment]
It gets better: mind control abilities also add an `X2Effect_RemoveEffects`, which removes the stunned effect on `PlayerTurnBegin`. Unfortunately, it doesn't fully remove the effect, but it _does_ remove the `UnitGroupTurnBegun` listeners that end the stunned effect. Hence why the unit remains in a permanently stunned state.

**Comment by pledbrook** [comment]
OK, so the LW2 Secondaries Arc Thrower has a "fix" that is interfering with the reproducibility and my bug fix. Use the following save file to reproduce instead of the one in the description:

[save_BUG Stun & Mind Control.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3689389/save_BUG.Stun.Mind.Control.zip)

Simply end the turn and see whether the stun is removed from the Grenadier when the mind control wears off.
