### ISSUE TITLE
Add OnLoadedSavedGameToTactical() to X2DownloadableContentInfo

### ISSUE THREAD

**Issue by HoneyTheYellowBear123** [X2CommunityCore/X2WOTCCommunityHighlander#647]
We already have OnLoadedSavedGameToStrategy(), but certain changes can be bypassed by saving during and mission and loading that save. Additionally, an all inclusive OnLoadedAnySavedGame() could be useful, since the current OnLoadedSavedGame() only applies the first time when a mod is activated.

**Comment by Musashi1584** [comment]
Added changelog entry in merge commit. Please add this yourself on the next PR.
