### ISSUE TITLE
TLP Weapon Upgrades missing

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#657]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/547/ added a version of `X2ItemTemplate` that didn't have the relevant TLP changes, and is thus missing code to apply the upgrades; should be:

```diff
function XComGameState_Item CreateInstanceFromTemplate(XComGameState NewGameState)
{
    local XComGameState_Item Item;

    Item = XComGameState_Item(NewGameState.CreateNewStateObject(class'XComGameState_Item', self));

+   if (OnAcquiredFn != none && !HideInInventory)
+        OnAcquiredFn( NewGameState, Item );
+
    return Item;
}
```

Quick audit of 1.19 does not show any more errors like this.

**Comment by seventy5** [comment]
Same bug applies to Darklance, no other chosen weapons are affected, just the Darklance has no upgrades
