### ISSUE TITLE
Dual arms unconditionally hide arm deco ("shoulders")

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#659]
This is something that already existed on the UI level, bit a change was made on the pawn level in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/351 and landed in v1.19.0. It seems like this caused breakage for users of Unrestricted Customization, which bypasses UI level checks, see <https://www.reddit.com/r/xcom2mods/comments/dk2c45/please_help_character_pool_broken_my_soldiers/>.

In vanilla, this change would be entirely correct. The following picture shows dual arms on the left, and arm deco ("shoulders") on the right. All single arms basically only customize the forearm (not shown):

![grafik](https://user-images.githubusercontent.com/14299449/67147066-970e7e80-f291-11e9-96fa-53d38a1336ac.png)

This is a bad situation because the point of UC is creating setups we cannot algorithmically verify to not conflict, but UC only disables UI level checks, not pawn level checks. Tagging as HL bug because we want to investigate what to do here.

**Comment by MrNiceUK** [comment]
Ok, well simplest would be to put *back* the vanilla code which blanked out the shoulder slots when dual arms are selected in the UI, and *remove* the Pawn code which hides shoulders when dual arms are in use (ah, for a sane world where the arm archetype had a flag for hiding shoulders or not, as it does for forearms!)
