### ISSUE TITLE
Fix smoke and poison targeting

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#669]
This would port the LW2 changes to the highlander so that smoke and gas grenade targeting would match the tiles that are actually affected. It would remove the need for Reliable Smoke and its MCO.

**Comment by pledbrook** [comment]
This could also add the option to have smoke disable the flanking bonus from crit. Maybe?

**Comment by Xymanek** [comment]
How would this interact with the existing fix mod?

**Comment by pledbrook** [comment]
That MCOs the effect classes, so there shouldn't be any conflict.

**Comment by pledbrook** [comment]
OK, so LW2 added a whole `CheckForWorldEffectTileExclusion(out array<Actor> CurrentlyMarkedTargets, array<TTile>Tiles)` function to `X2TargetingMethod_Grenade` to fix another issue with painting actors that won't be affected by the smoke/poison/other world effect.

**Comment by pledbrook** [comment]
There is also an issue for smoke grenades where units are highlight but their tiles are not:

![X2 smoke targeting bug](https://user-images.githubusercontent.com/19075/103102003-fe505d00-4611-11eb-9d30-aea8c806d781.png)

Only the units that are on highlighted tiles will actually get the smoke buff, so highlighting the other units is confusing to players (and just plain wrong). LW2 fixed that as well, so will include it in the pull request for this issue.
