### ISSUE TITLE
Possible issue in chosen sarcophagus mission stage regarding reinforcements

### ISSUE THREAD

**Issue by nealbrown** [X2CommunityCore/X2WOTCCommunityHighlander#674]
I really appreciate all the work put in on this mod and how it has enabled so many other great mods.

I've played about 300 hours in the last 2.5 months.  Since the Oct 15th(?) update I have had reproducible crashes in Chosen (Assassin) sarcophagus chamber when reinforcements spawn in.  (This happens after the chosen is killed the first time).   It also happens at the codex site psionic gate cutscene (gatekeeper reinforcement).  One of the reasons I suspect the highlander is that the entire mod set worked fine prior to the this update. 

There **were** windows 10 updates pushed during this time but no driver etc changes made in months.

The steps I have taken are below

1. Remove Xcom2 from steam entirely and redownload, twice
2. Manually clean out all xcom folders such as mods and profile etc, twice, both steam and my games
3. Start three new campaigns and was able to repro on all, all legendary, current is beta strike but makes no difference
3. Disable all mods, repeatedly
4. Enable mods until I got to only the highlander disabled
5. Save at geoscape before starting mission at all, and start mission "fresh", probably did this 20+ times.
6. Conclusion was with **only** highlander disabled I can complete the mission normally

I'll try to attach the entire crash zip otherwise I'll paste in the entire log.  You will see references to primarily cosmetic mods, the only mods that are really game changing are
1. increase pod size by force level
2. metal over flesh redux

If no one else reports similar behavior by all means chalk this up to gremlins but for me it is reproducible.  I do not want to clutter your issues.
[XCom-CL374751-2019.10.27-12.02.31_Logfile.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3776465/XCom-CL374751-2019.10.27-12.02.31_Logfile.log)
![XCom-CL374751-2019 10 27-12 02 31_Screenshot](https://user-images.githubusercontent.com/59647/67642441-d7957a00-f8d9-11e9-8f87-92c650dbb580.png)

This file was appended with .zip to bypass github filters but is the raw file
[XCom-CL374751-2019.10.27-12.02.32_Save-Rename-To-Save0-For-Load.fakezip.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3776466/XCom-CL374751-2019.10.27-12.02.32_Save-Rename-To-Save0-For-Load.fakezip.zip)

**Comment by robojumper** [comment]
The log file you posted does not indicate that the Highlander is enabled or loaded. Please follow the steps on our [Troubleshooting](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting) page.

**Comment by nealbrown** [comment]
Ah ha!  During troubleshooting I must have left it unloaded.  I've left it that way and been crash free, and the dependent mods still work!  I'm sure if no one else is reporting this its just a conflict with another mod, nothing directly to do with highlander.

Thank you again!

**Comment by nealbrown** [comment]
In case others come across this, I found this older issue https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/56 that references MetalOverFleshRedux, which has NOT been updated since Highlander made some changes, so at this point I'm suspecting that mod.
