### ISSUE TITLE
CTD on 2nd start

### ISSUE THREAD

**Issue by kshots** [X2CommunityCore/X2WOTCCommunityHighlander#675]
Odd issue... One of my instances (windows 10 machine) does a crash to desktop (CTD) on the second start. I've removed the config files under "~\My Games\XCOM2 War of the Chosen\XComGame\Config\*" to let the highlander load them from defaults. The highlander is the *only* mod loaded. XCom2 intallation has been uninstalled, reinstalled, and verified to no effect. Tried versions 1.18.2, 1.19.0, and 1.19.1 (via manual install process), all show essentially the same data in the log file with the same end result. Also tried the steam workshop version (looks to be 1.19.1 at this time according to the logs). Attached is the log for the manual install of 1.19.1 (after unsubscribing from the workshop version). All DLC has been installed. Oddly, the mod appears to work fine under a linux instance with a similar config.
[Launch.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3812707/Launch.log)

**Comment by robojumper** [comment]
```
[0007.14] X2WOTCCommunityHighlander: Companion script package loaded
[0007.14] X2WOTCCommunityHighlander: Components:
[0007.14] X2WOTCCommunityHighlander:   X2WOTCCommunityHighlander -- v1.19.1
[0007.14] X2WOTCCommunityHighlander:   Engine -- NOT LOADED - REQUIRED
[0007.14] X2WOTCCommunityHighlander:   XComGame -- NOT LOADED - REQUIRED
[0007.14] X2WOTCCommunityHighlander: Required packages were not loaded. Please consult https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting for further information
```

**Comment by kshots** [comment]
Yes, I saw that... So there's no solution or path forward?

**Comment by robojumper** [comment]
The error message links to a troubleshooting page. That troubleshooting page almost certainly contains a solution that works.

**Comment by kshots** [comment]
Maybe I missed something... I looked there for a solution before coming here. I apologize for being persistent, but I didn't see anything there that helped :/

**Comment by Musashi1584** [comment]
Have you tried to move the CookedPCConsole folder to your user directory?

**Comment by kshots** [comment]
Well, I stand corrected. I had assumed because I was not doing any of the known triggers (steam family sharing / no internet connection) for that condition, it didn't apply. Applying that workaround got it running.

I'd be willing to do some poking around to find additional triggers that cause this, since I appear to be outside the two triggers with the same symptoms... but not sure where to poke first.

So, to be clear... since I applied this workaround, if I stop using the highlander, I now need to manually remove that folder (it didn't exist under the user documents folder originally)?
