### ISSUE TITLE
[Feature] Proper Weapon Skins

### ISSUE THREAD

**Issue by tunbridgep** [X2CommunityCore/X2WOTCCommunityHighlander#687]
There are many mods out there which add new variants of existing weapons and armors. These variants are effectively skins - they have no impact on gameplay - and only exist to serve as alternate visuals. However, the game doesn't really support a way to have alternate variants in the customization options, so most mod authors tend to create a new item entirely just for the ability to use a new model.

There are some problems with this approach. It is inherently incompatible for the following reasons:

- New weapons and armors are effectively clones of the old ones. If a weapon mod (like LW2) changes the stats of some weapons, the "skin" versions will only have the default stats.
- The new weapons clog up the selection menus
- New classes sometimes cannot use the skin versions of weapons if they aren't configured correctly
- Weapons that you produce in limited quantities have a separate quantity counter for each skin variant.

Obviously this isn't really a "bug" in the game per se, but I think having a better way to do this would be extremely beneficial. Instead of having to create new copies of existing items, all items should support "variants", which allow mod authors to very easily add new models, particle effect etc to them, without changing their properties. Armors sort of already have this through the customization menu, although it's admittedly clunky. These skins would always have the stats of their parent items, and wouldn't appear in the item selection menu, instead you would select a skin the same way you normally customize a weapon or armor item. I think this would increase mod compatibility (in some ways significantly), especially since there are MANY weapon and armor skin mods on the Steam workshop, and almost all of them simply duplicate the existing weapon or item and change the model. There are also many base-game or DLC items (like the Resistance Warrior armor and the TLP item/weapon variants) which do this too, further clogging up the menu, and they should probably also be moved over to this new system.

Imagine using, say, the Mercenary Plasma Rifles Mod and a handful of other weapon skin mods, but having proper compatibility with any mod that modifies weapons (like LW2), and a non-cluttered weapon menu. Obviously, these weapon skin mods would have to be updated to use the new system. This would mean that ANY skin mod made compatible with the highlander would automatically be compatible with any gameplay mod that relies on the highlander, even if it modifies item statistics.

I am not a modder myself, so I don't know the intimate details of how this works, and I fully understand that this suggestion is likely to be rejected because it's not a mission-critical issue, because of it's complexity, or it might simply be impossible within the engine. But I do think it would make things significantly easier for everyone, as mod authors wouldn't have to make special versions of their skin mods for different gameplay mods (like LWOTC), and players wouldn't have to make sure they are using weapon skin mods that are compatible with their (possibly over a hundred) gameplay mods. I know this can often be fixed by modifying weapon statistics in config files, but that's a pain and you can't change everything.

I know there are mods like XSkin System which already do this, but IIRC it's not perfect and it isn't well known about. Having this functionality in the highlander means it's more likely to be known about, and it's a base mod many people are already using.

**Comment by Musashi1584** [comment]
While all your reasoning to have a weapon skin system is perfectly valid its not something that would be part of the highlander as a feature. It can be done as a mod that maybe needs some new extensions in the highlander but the main part of the mod (which involves new ui to some degree) can be done as a separate mod. 
Its just very complex due to some technical difficulties regarding how weapons, attachements and templates are setup and so far no modder wanted to open that pandoras box again i guess.

**Comment by robojumper** [comment]
To elaborate on the challenges, almost all UI doesn't ask the item state itself, but the item's template (which also dictates stats, abilities, etc.) for images, texts and 3D models. What would get us closer to a proper skin system would be us implementing these functions on the item state and then changing almost all the UI (including whatever code UI mods have!) to instead ask the item state. Chances are we'll miss some, not all mods will be updated, and the feature will only work halfway for months and more.

That's not to say it can't be done! We made similar (though smaller in scope) changes for soldier classes to support RPG Overhaul and other mods, and it works well enough, even in combination with UI mods like my squad select. It's just that a skin system would be an even more ambitious project to implement and as @Musashi1584 said, it was not deemed worth the effort by most.

**Comment by tunbridgep** [comment]
That's fair enough. As a non-modder, I guess I don't understand the monumental scope of what I am asking for. I guess I am just sick of mods duplicating and triplicating the weapons in the weapon list.

I guess I don't understand the templates thing as a non-modder. Couldn't a feature be added where a modder can effectively say "This template is that template, but these values are overridden", and when looking up a template in the UI, it will get all the elements of the source template overwritten by the second template?

I guess I am just rambling now. I guess I need to go learn some Unreal Script. I'm a bit scared because I am on Linux and Epic has a track record of being terrible with Linux support, even if Firaxis has done a good job porting the actual game over.

**Comment by Musashi1584** [comment]
> Couldn't a feature be added where a modder can effectively say "This template is that template, but these values are overridden", and when looking up a template in the UI, it will get all the elements of the source template overwritten by the second template in the background but as far as the UI or mod is concerned, it's a normal template?

Well thats basically what [[WOTC] Iridar's Weapon Skin Replacer](https://steamcommunity.com/workshop/filedetails/?id=1517938486) does.
Its config based and you can replace the assets of templates. There a even readymade config mods for it like [[WotC] Coilguns - Beam Tier Replacer 2.0](https://steamcommunity.com/sharedfiles/filedetails/?id=1929060959).

This is relatively simple to do but it operates on template level. That means if you replace the look of the conventional assault rifle all instances are replaced.

A weapon skin system robojumper and me talked about should operate on a item gamestate level. Meaning you could have soldier Jake having a conventional assault rifle that uses the laser rifle skin and solder Julian can have one that looks like a coil rifle. And if you want you could change the look to something else with a few clicks without modyfing the look of Jakes assault rifle. 
This has, beside all the technical difficulties mentioned earlier, a wide range of gameplay implications. For example what are the real tiers and how many tiers do you have? what happens when you upgrade to a new tier.
Which mod weapons should be converted to be cosmetic and which will stay as separate weapons? etc. etc.

> I guess I am just rambling now. I guess I need to go learn some Unreal Script. I'm a bit scared because I am on Linux and Epic has a track record of being terrible with Linux support, even if Firaxis has done a good job porting the actual game over.
Afaik the modding tools only work on windows os.

**Comment by tunbridgep** [comment]
That makes a lot more sense I guess. I just wish there was a way to duplicate a template programatically so we could effectively get the same result without the gamestate level changes. Oh well.

I understand it has gameplay implications, but that's entirely the fault of the player, so it's not really a big issue. If someone really wants to make their conventional rifles look like lasers, and their laser rifles look like lasers, and they get confused, they have nobody to blame but themselves, and they made that choice for whatever reason. I can see your point about how some people might get confused though.

**Comment by Xymanek** [comment]
> I just wish there was a way to duplicate a template programatically so we could effectively get the same result without the gamestate level changes

You can duplicate them, but then you get the exact same issue - it's a different item in xcom inventory

**Comment by Tenga** [comment]
> You can duplicate them, but then you get the exact same issue - it's a different item in xcom inventory

Which, in my opinion, is the real problem. The UI for inventory management is terrible when it has to deal with more than Firaxis planned for.

A decent, tabular, searchable, filterable, compact, inventory list would do wonders instead of the narrow, single column with enormous items that barely fit a few of them on the screen.

**Comment by Xymanek** [comment]
An UI rework is definitely outside of CHL's scope

**Comment by Tenga** [comment]
> An UI rework is definitely outside of CHL's scope

Oh, not suggesting that, just commenting on the (hopefully) obvious. 😄 

It would fit much better in a standalone mod, just like robojumper's Squad Select does, and it wouldn't be too useful in a vanilla environment.

**Comment by VampireMonkey** [comment]
Considering that this would require changing the game in a fundamental way, i think the Highlander is an ideal place to put it.

If you get it to work, then it can be added to the highlander-

**Comment by Musashi1584** [comment]
> Considering that this would require changing the game in a fundamental way, i think the Highlander is an ideal place to put it.
> 
> If you get it to work, then it can be added to the highlander-

That’s not true. The scope of the highlander are changes that can’t be done (in a compatibility friendly way) in a mod cause they require changes in the basegame classes. Doesn’t matter if they are minor or fundamental in scope.
Another premise is that these changes should not change the default behavior of the game if the highlander is running standalone (except bug fixes).

**Comment by VampireMonkey** [comment]
It shouldn't be noticeable if those changes don't break other stuff

**Comment by Iridar** [comment]
[Hold my beer](https://steamcommunity.com/sharedfiles/filedetails/?id=2337161588)

Closing the issue like a champ.
