### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by lsharpshotzl** [X2CommunityCore/X2WOTCCommunityHighlander#688]
Right so I have a cracked version of XCOM 2 WOTC installed coming with Long war 2 mod.  I disabled and removed the mod from the game files before downloading community highlander.  Whenever I started up the game before, everything worked fine but now when I open the game with the highlander mod, I get past the starting intros, hear the music for the main menu and then the game crashes and brings me back to my desktop.  I have tried deleting the config file and using the mod by itself but I need this to enable other mods that I would like to use?  Can anyone please be of assistance and state anything that I may be doing wrong?

**Comment by robojumper** [comment]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting
