### ISSUE TITLE
[Bug] Full helmets make soldiers bald.

### ISSUE THREAD

**Issue by ArthurRevan** [X2CommunityCore/X2WOTCCommunityHighlander#689]
Soldiers who wear full helmets (the ones that hide the hair)
are bald when they're on the Avenger (not on a mission).
+ 
some soldiers appear to wear headpieces witch they not supposed to wear on Avenger:
such as goggles and headband.

It a minor bug, but still annoying.

**Comment by DarthDangermouse** [comment]
I am also having this issue, it seems much more pre-evelant with mods that up the number of crew.

**Comment by MrNiceUK** [comment]
I'll have a look at the code changes I did in a couple of customization related PRs, but sure I would have noticed if some of my lovely ladies were bald!
