### ISSUE TITLE
CTD With Highlander installed

### ISSUE THREAD

**Issue by Aracasodius** [X2CommunityCore/X2WOTCCommunityHighlander#691]
Hey, I ran through the troubleshooting and everything, nothing fixed it. (Yes I read it carefully, and did everything it suggests)

- I verified my files
- I reinstalled the game
- I ran the game with no mods (it works)
- I ran the game with only this mod (it crashes)
- I refreshed my Ini files 
- I moved my CookedPCConsole files to my documents

Nothing works..
Is there just some obvious step I'm missing, like setting this mod as a overhaul mod in the engine configs or something? I'm not using a mod manager as I prefer to keep track of XCOM 2 Modding manually, since it's quite messy.

**Comment by Xymanek** [comment]
Post your log

**Comment by Aracasodius** [comment]
> 
> 
> Post your log

https://pastebin.com/M1suAffn

**Comment by Xymanek** [comment]
> Can't bind to native class XComGame.XComGameState_ObjectivesList

Your game is out of date

**Comment by Xymanek** [comment]
Just a bit more info: your `FxsChangelist` is `302202`, while the latest is `374751`

**Comment by Aracasodius** [comment]
I figured this was gonna be the issue, I haven't had the funds to purchase the game yet, and I only recently introduced myself to XCOM 2, Thanks dude!
So all I should have to do is just buy the game, use the steam version and be on my way right?

**Comment by Xymanek** [comment]
Correct, the official version should work without any issues just by subscribing on workshop
