### ISSUE TITLE
Add Inverse Boolean to X2Condition

### ISSUE THREAD

**Issue by VampireMonkey** [X2CommunityCore/X2WOTCCommunityHighlander#699]
When Inverse is True any Value that would have been returned will be Inverted first.

So "AA_Success" would become "AA_AbilityUnavailable" and vice versa.

Extremely useful when working with Abilities.

Probably would have to be an intermediate for X2Condition.MeetsCondition and whatever native stuff goes between it and CallMeetsCondition

I don't know anything about the native stuff tho.

**Comment by robojumper** [comment]
`X2Condition` is native; its data layout cannot be changed. What I'd recommend is creating an `X2Condition_Inverse` with a `var X2Condition InnerCondition;`. The outer condition queries the inner and inverts the result.

**Comment by VampireMonkey** [comment]
That's a great idea, could we add it to the Highlander?

**Comment by robojumper** [comment]
If it is added, we should document why something that *can* be implemented without the HL's involvement is still in the HL.

Personal opinion: Yes, we could; there's precedence for such things (#445, specificially see justification in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/446#issuecomment-482834641). Make sure the inverse of `'AA_Success'` is configurable, as it controls UI text when the ability is unavailable.

**Comment by robojumper** [comment]
From @Xymanek via the Discord:

> One thing that I would be wary of is that the inverse mappings could be different for specific abilities/conditions and as such, maybe it's better to make a generic X2Condition_MappingDecorator which allows to map inner results with no assumptions of the process?
> Just an array of source->new values

**Comment by VampireMonkey** [comment]
Or have the X2Condition have default settings that can be changed, perhaps an array of tuples that are matched together, these can be set when creating the abilitytemplate.

**Comment by Iridar** [comment]
Per robojumper's recommendation, closing this issue as infeasible. Details are in comments to #947, [specifically here](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/947#issuecomment-758922481).
