### ISSUE TITLE
Proper organized documentation

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#700]
Currently CHL's "documentation" can be found in 4 places:

1) `CHANGELOG.md` which contains brief overview of the stuff we did and doesn't explain how to use it
2) Source code for/around changes (+ comments) - this is very difficult to search and requires initial knowledge of where is the source code that triggers the event
3) Issues/PRs - kinda hard to search (especially some of the earlier ones) + usually very little info so need to fallback to (2)
4) Source code of mods that use it and minds of modders - 😐 

There are some features that really require explanations (e.g. #605, #524, #511, #322, etc) and the `CHANGELOG.md` format doesn't really support it. I propose a new file (one file, so it's easy to ctrl+f it), `API_DOCS.md`, in the following format:

--------------------------
# General

## Mod compatibility (#524)

In `XComGame.ini` mods can specify an array of incompatible and/or required mods. This will be used to show an warning popup if they are present

```
[ModSafeName CHModDependency]
+IncompatibleMods=OtherModSafeName
+IgnoreIncompatibleMods=OtherModSafeName
+RequiredMods=OtherModSafeName
+IgnoreRequiredMods=OtherModSafeName
DisplayName="Fancy Mod"
```

## DLC Run Order (#511)

In `XComGame.ini` mods can define an array of other mods which dlc hooks should run before and/or after the mods dlc hook.
LoadPriority can be RUN_STANDARD, RUN_FIRST or RUN_LAST. RunBefore and RunAfter only work within the defined LoadPriority group. Only change load priority if you really sure that its needed for you mod
```
[ModSafeName CHDLCRunOrder]
+RunBefore=OtherModSafeName
+RunAfter=OtherModSafeName
RunPriorityGroup=RUN_STANDARD
```

# Strategy

## OverrideNextRetaliationDisplay (#667)

```
EventID: OverrideNextRetaliationDisplay
EventData: XComLWTuple {
  Data: [
    inout bool bShow,
    inout string strHeader,
    inout string strValue,
    inout string strFooter
  ]
}
EventSource: UIAdventOperations [self]
```

Allows mods to force show/hide the section (1st argument) and customize the text displayed (arguments 2-4) on the "Dark events" screen

# Tactical

....

--------------------------

This will allow us to build a resource that 

* sufficient (no need to dig into code)
* is easily searchable
* can be linked to (headers)
* easily inspect-able in PR diffs
* orientated towards explanations of how to use things, rather than just listing changes that were done to base game code

If this is agreed to, I suggesting instantly commiting this file to master (with the 3 section headings) so that PRs can add stuff to it without causing massive conflicts

cc @pledbrook @robojumper @Musashi1584

**Comment by robojumper** [comment]
I think the biggest issue here is discoverability. A single one-hundred pages long markdown document is likely not going to be easily searchable and even if it is initially, it won't stay that way.

Additionally, if our source format is also the way the documentation is intended to be consumed, this significantly limits what we can and can't put into the documentation; consider the following example:

> We want to point out whether a feature/bugfix is a compatibility hazard between mods and the HL, like the DLCName-armor interaction, the CHL custom slots feature, etc.
> * If we do add it, we want to have a really good way for people to find it (or a list of stuff they might need to pay attention to). Tagging every entry with "compat-hazard" so that a Ctrl+F can find it basically makes our docs very machine-format-like and the more metadata we add, the less readable that document becomes.
> * If we don't add it, we have no way to find these features/bugfixes. The information literally isn't there.

There's more functionality I'd like to have included, like

* Version info (when did something become stable? Is it on the workshop version of the HL?)
* Compatibility (has this been observed to cause issues in other mods? Can other mods break the HL's implementation of it)

As a result, I think we should find a better, machine-processable format to store the documentation in the repository (strawman proposals: `.ini`, `.xml`, `.yaml`, `.toml`, `.json`, `.md`) and then set up scripts that can:

* Render to a single markdown page as described in OP
* Create a full web page with a search bar, landing page and individual pages for individual documentation items (using Sphinx, MkDocs or similar)
* Deploy all of the above to GitHub pages (i.e. somewhere below https://x2communitycore.github.io/).

The Sphinx/MkDocs documentation could then, for example, tag pages with "compat-hazard" and provide a link that instructs the search page to list all pages tagged with "compat-hazard".

**Comment by robojumper** [comment]
PS: Obvious problem: "Who's gonna do it?"

I think your proposal is an easy way to move to a better documentation format (way better than we currently have) and I'm grateful for the proposal.  
Implementing something like I outlined above is a lot of work and probably about as likely to make this thing get stuck in a limbo like #560, #622, but even if we don't sort out the Sphinx/MkDocs stuff immediately, we can still tackle the "render individual files to a single MD document" somewhat easily.

**Comment by Xymanek** [comment]
> Obvious problem: "Who's gonna do it?"

Yeah, that's definitely an issue. Single md file is much easier to start working on (for feature PRs authors). Additionally, it will allow however wants to work on proper documentation system to base off something (rather than no docs that we currently have)

Another issue I would like to consider - if we have multi-page documentation, then how do we partition the pages? A page per issue/PR will result in tons of pages that are 1/3 of screen size at most. A page per section (general/strategy/tactical) will result in same problems as "single md" approach, but partitioned into 3 parts (which would make it harder to search)
