### ISSUE TITLE
Now that civilian noise alerts have been corrected, remove the broken default behavior

### ISSUE THREAD

**Issue by RedDoby** [X2CommunityCore/X2WOTCCommunityHighlander#717]
Add the option to disable the default civilian yell in class XGAIBehavior_Civilian.  This default yell behavior interferes with the modified donoisealert() in class X2AIBTDefaultActions.  This is copied from Long War.  

```
function BTRunCompletePreExecute()
{
	local AvailableAction YellAction;
	local int TargetIndex;
	super.BTRunCompletePreExecute();
    
    // LWS Add: Configurable disabling of civilian yell
    if (!class'Helpers_LW'.default.EnableCivilianYellOnPreMove)
        return;

	if( !m_kPlayer.bCiviliansTargetedByAliens )
	{
		// Yell before moving.
		YellAction = FindAbilityByName('Yell');
		if( YellAction.AbilityObjectRef.ObjectID > 0 && YellAction.AvailableCode == 'AA_Success' )
		{
			if( YellAction.AvailableTargets.Length == 0 )
			{
				TargetIndex = INDEX_NONE;
			}
			class'XComGameStateContext_Ability'.static.ActivateAbility(YellAction, TargetIndex);
		}
	}
}
```

**Comment by RedDoby** [comment]
After discussing with other modders decided this is not needed anymore.

**Comment by RedDoby** [comment]
Determined that this indeed is causing units to go into red alert from the default yell.

**Comment by Tedster59** [comment]
example: https://clips.twitch.tv/CovertSpookyFungusThisIsSparta-iiWYdFo53wiLuLfz

Civilian yell puts a pod on red alert instead of yellow alert.  current LWoTC release.

**Comment by Tedster59** [comment]
Reopening this to track additional investigation.  Previous fix didn't catch all cases, so working on a new one to fix the source of the issue, which is the MultiTargetEffect added in the Yell ability.

**Comment by Iridar** [comment]
Apparently the desired effect was achievable all this time with no Highlander changes just by neutering the Yell ability in OPTC, closing this issue, #1246 is to be reverted.
