### ISSUE TITLE
Allow mods to inject additional constraints on applying sit reps to missions

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#761]
Mods cannot easily add constraints on whether a given sit rep can be applied to a given mission without replacing the `GetSitRepsFn` on mission source templates. Even then, mods would typically end up copying the existing code in `X2StrategyElement_DefaultMissionSources.GetSitrepsGeneric()`. And, of course, doing so would make it difficult for mods to happily coexist if they both want to add some constraints.

I propose adding an event trigger to `GetSitrepsGeneric()` that allows mods to override the default behaviour for a given sit rep/mission combination, either by allowing the combination or forbidding it.

**Comment by Xymanek** [comment]
Why does https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/561 not suffice for your needs?

**Comment by pledbrook** [comment]
I didn't notice that, sorry. One weakness of it is that it doesn't allow mods to override the base game behaviour, but I think it would be sufficient for my needs. Thanks for bringing it to my attention.
