### ISSUE TITLE
Bald heads on the Avenger?

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#768]
From the Steam workshop comments:

> Can the issue with Bald soldiers be addressed? Soldiers with helmets always appear to be bald on the Avenger and this always looks weird.

>> This mod seems to make soldiers who wear helmets bald in the Avenger home screen.

> Others have reported the same problem with bald toons running around the Avenger. I don't think it's ever actually been addressed, though.

> Soldiers with helmets end up bald on the Avenger with this mod for some reason

cc @MrNiceUK

**Comment by Iridar** [comment]
I've had a lot of comments about bald heads in the comment section for my mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1707030670

Not sure if the bug is induced by my mod, or it's a vanilla bug that becomes more noticeable with my mod installed.

**Comment by Dragon-32** [comment]
See also #689 _[Bug] Full helmets make soldiers bald_

**Comment by robojumper** [comment]
Right, should have searched for an existing issue. Closing in favor of #689.
