### ISSUE TITLE
Community Highlander not working correctly

### ISSUE THREAD

**Issue by Killerbee777** [X2CommunityCore/X2WOTCCommunityHighlander#79]
Hello, I have seen this problem in the steam website, and in this forum as issue #69. The issue is that, I put the folder onto the xcomegame/mods folder at war of the chosen directory,
I see the mod when I open it in ModLauncherWPF, and I enable it for War of the Chosen, but when I open the game, the version string does not appear at the lower right corner of the screen in the main menu, meaning its nominally loaded but not recognized in game. I have tried reinstalling the game, uninstalling all mods,using an older version of the highlander, and trying to only use the highlander, but even then it does not work ,(the version does not show up on the lower right corner, and all mods I try with it as a requirement miss textures).

I need help to solve this issue.
Best regards.

**Comment by newuser42** [comment]
Hello Killerbee777

please try downloading WOTC Community highlander version 1.3.0 here: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/releases/tag/1.3.0 

This fixes it  not loading for me, apparently the uncompressed files did the trick! 
will test with mod dependencies
