### ISSUE TITLE
Change Elements in UISquadSelect_ListItem to Individual Buttons

### ISSUE THREAD

**Issue by Onidotmoe** [X2CommunityCore/X2WOTCCommunityHighlander#792]
Currently Buttons are handled with a OnMouseEvent and a Switch Case that checks input based on what the mouse is over, this prevents any changes to button inputs as those inputs are never used.

Similar to Issue #47 in UIArmory_MainMenu.

I'd try to make a pull request soon(ish).

**Comment by robojumper** [comment]
Note: My squad select does this already

https://github.com/robojumper/robojumperSquadSelect/blob/f09eb7c9f501cbb463189691d420fcfcc28ddf84/robojumperSquadSelect/Src/robojumperSquadSelect/Classes/robojumper_UISquadSelect_ListItem.uc#L180-L199

Can you outline your use case? Does whatever you're trying to do require cooperation from my squad select mod?

**Comment by Iridar** [comment]
Seeing as nothing happened here for three years, closing.
