### ISSUE TITLE
Add an Event to arbitrarily set soldier class when they are first promoted

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#801]
Adding an Event to the start of `XCGS_Unit::RankUpSoldier` would allow mods setting soldier's class based on arbitrary conditions when they are first promoted.

For example, when used alongside Not Created Equal, it would be possible to make high aim soldiers gravitate towards becoming snipers.

**Comment by Iridar** [comment]
Will `'PreUnitRankUp'` do as the name for the event? Considering it happens just a bit earlier than `''UnitRankUp'`, I think it'll be fine.

**Comment by pledbrook** [comment]
Another option is something like 'OverrideRankUpSoldierClass' since that appears to be the primary purpose of the event.

Wondering how this will impact mods like Commander's Choice. Would it make life easier for them? Is it irrelevant?

**Comment by Iridar** [comment]
> Another option is something like 'OverrideRankUpSoldierClass' since that appears to be the primary purpose of the event.
> 
> Wondering how this will impact mods like Commander's Choice. Would it make life easier for them? Is it irrelevant?

I'm not sure how commander's choice works, however only after pushing the commit I realized the mod would just be a complicated alternative to commander's choice, so idk if it's of any relevance.

**Comment by Iridar** [comment]
Closing the issue, because Commander's Choice does the same thing.

**Comment by Iridar** [comment]
Reopening because Commander's Choice does big bad voodoo.
