### ISSUE TITLE
Add event for rookie training completion

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#804]
Bond and Psi training currently have an event that is fired once the project completes, which allows me to restart the units' Will recovery projects. There is no similar event for rookie training, though. It would be good to add one (along with any other relevant HQ project).

**Comment by pledbrook** [comment]
This isn't needed for what I wanted to do, but leaving the issue because it would make for some good consistency to have all the HQ training projects, or maybe just all HQ projects, fire an event on completion.

**Comment by Iridar** [comment]
There's a `'UnitRankUp'` event, is it not good enough for your purpose?

**Comment by pledbrook** [comment]
Since there is no immediate need for this and I'm mostly keeping it around because it would make the API more consistent, that's pushing too far outside the scope of the highlander with no major benefit.
