### ISSUE TITLE
Add an event that allows Abilities to work with Overkill Damage

### ISSUE THREAD

**Issue by Grobobobo** [X2CommunityCore/X2WOTCCommunityHighlander#805]
Similiar to issue #91, But not just exclusive to the bleed out effect. Currently it can't be done because the relevant events only pass the unit states, whose DamageResults arrays don't store overkill damage, just the damage the unit has taken (so if a 3hp unit gets shot for 10 damage it will register only 3).

**Comment by pledbrook** [comment]
Use case is to have the chance for a Priest to enter Sustain reduced by the amount of overkill damage. Perhaps making that ability far less frustrating for players...
