### ISSUE TITLE
Deprivatise static helper functions in `X2StrategyElement_DefaultCovertActions`

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#811]
These functions don't modify the internal state of the class, but they can't be used from subclasses or any other class that wants to create covert actions!

**Comment by Xymanek** [comment]
So far everyone just copied them over to their code

**Comment by pledbrook** [comment]
It's the only thing to do right now, which is why I think it makes sense to deprivatise them. I recognise that it's pushing the scope of the highlander a bit, but it's also very, very low risk.

**Comment by MrNiceUK** [comment]
I'm with PaledBrook (for once!), I would *almost* support blanket removing of all private/protected modifiers in the whole sdk!

**Comment by Xymanek** [comment]
One potential issue with unprivatizing stuff is that it becomes part of public API/BC promise. While that may sound like "okay, whatever", there was at least one case where it was useful:

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/6dfae4cc8932039503dd8487465f4959958fb849/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_CovertAction.uc#L912-L943

**Comment by Iridar** [comment]
A bit of code duplication is hardly a huge concern. Seeing as nothing happened here in three years, closing.
