### ISSUE TITLE
Allow mods to modify the list of classes that can be trained in the GTS

### ISSUE THREAD

**Issue by ChrisTheThinMint** [X2CommunityCore/X2WOTCCommunityHighlander#814]
Planning to add an event in UIChooseClass:GetClasses() where any mod can return a modified list. This allows GTS training to be restricted to certain classes without overriding the UI class.

**Comment by Iridar** [comment]
Would be nice to be able to control this conditionally, like "prohibit GTS training unless you have a soldier of this class on your crew / ever had one". Similarly, to control which soldier classes you can get via rookie promotions, and which through random encounters / scanning POI.

**Comment by ChrisTheThinMint** [comment]
I think you could easily call the HQ and look up the player's current soldiers to see if a class is present with the current listener. I've been looking at promotions and soldier rewards too, I'm currently using a UIScreenListener to control those but i wouldn't mind having events there either.
