### ISSUE TITLE
Trigger an Event in `XComUnitPawn.PlayHitEffects`

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#825]
The event should allow overiding the hardcoded templar fx for `eHit_Parry`, `eHit_Reflect` and `eHit_Deflect` which play for any class using abilities that utilizing these hit results.

**Comment by Iridar** [comment]
PR closing this Issue was merged already, and it already has proper docs. Closing.
