### ISSUE TITLE
Add an event to override XCGS_Unit::HasHeightAdvantageOver

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#851]
I'd like to put an event in the mentioned function so that my Jet Shot can benefit from various abilities that trigger if the shooter has a height advantage, such as Death From Above. After all, the whole point of that ability is to provide a height advantage for the shooter, which is currently done through a hit modifier.

Does `OverrideHasHeightAdvantageOver` work as the event name?

**Comment by Xymanek** [comment]
Can't you change the z position of the unit? Like the Blazing Pinions work?

**Comment by Iridar** [comment]
> Can't you change the z position of the unit? Like the Blazing Pinions work?

Maybe I could, but I would have to redo everything about that ability from scratch, including animations. It would also make it more complicated, because I would have to split flying up and landing into separate abilities, because some perks that check height advantage fo it in post ability cost paid. It would be a massive mess. Doing this through an event has the advantage of also allowing to make a perk that denies height advantage to the shooter.
