### ISSUE TITLE
X2WOTCCommunityHighlander - CTD at startup of the Game since last WOTC update oct19

### ISSUE THREAD

**Issue by Darkteutonic** [X2CommunityCore/X2WOTCCommunityHighlander#86]
Hello,

I do not know if there is anyone else having this issue but since I downloaded the super huge WOTC update of 7.7 GB, the X2WOTCCommunityHighlander mod is making my game crash to the Desktop, before I get to the Main menu.

I have also tried multiple time, the troubleshooting step explained on Steam Mod page;
https://steamcommunity.com/sharedfiles/filedetails/?id=625230005

I have tried to unsubcribe and re-subscribe, but it doesn't seem to change anything, it always crashes at the same time. Your mod was working perfectly fine before the update, as far as I am concerned.

**Comment by bountygiver** [comment]
highlander will never work with different version of the games, it can only be used with the game patched it is made for

**Comment by MalucoMarinero** [comment]
Update out, should work with the latest version on the workshop.
