### ISSUE TITLE
Hook within UIStaffContainer --> OnReceiveFocus() which allows for its custom logic to be ignored

### ISSUE THREAD

**Issue by kdm2k6** [X2CommunityCore/X2WOTCCommunityHighlander#866]
**General** : A facility, represented by UIFacility, generally speaking, consists of a staff slot container and a room container. The staff slot container, located on the top of the screen, stores the staff slots; the room container, near the bottom of the screen, stores the room buttons. For example, the Guerilla Tactics School has 1 staff slot at the top with which to "Train Rookies", and 1 room button labelled "New Combat Tactics" whereby you can increase the squad size ... etc.

**Explanation** : The description below assumes a controller is being used, since this is the situation I am concerned with.

When a staff slot, UIStaffSlot, is clicked, a drop down menu is diplayed via a call to ShowDropDown() on the staff slot container. Now, at the end of ShowDropDown(), the variable SelectedStaffSlot is set to the staff slot which was just clicked. Basically, when you click on a staff slot, its container stores it as the selected staff slot, via the variable SelectedStaffSlot.

If the staff slot container loses focus at some point, which would happen if you navigate down to the room button, then gains focus again, focus is then automatically transferred through to the SelectedStaffSlot. This is done via UIStaffContainer --> OnReceiveFocus(), which calls the following code :

```
if(SelectedStaffSlot != none)
	SelectedStaffSlot.OnReceiveFocus();
```
	
**Problem** : Say you have 2 staff slots and 1 room button; this is the case with the Proving Ground in LWotC. 
1.] Assume you click on the 1st staff slot with the A button, a drop down menu appears, then you cancel the selection with the B button; at this point SelectedStaffSlot is set to the 1st staff slot. 
2.] Now, assume you press D-Pad right, at which point the navigator within the staff slot container points to the 2nd staff slot. 
3.] You then press D-Pad down to select the room container and room button; the staff slot container loses focus.
4.] You press D-Pad up; the room container loses focus and the staff slot container receives focus. The problem is that SelectedStaffSlot points to the 1st staff slot while the staff slot container's navigator points to the 2nd staff slot. UIStaffContainer --> OnReceiveFocus() places focus on SelectedStaffSlot (1st staff slot); however, an A button press will take into account the navigator (2nd staff slot).

**Request** : Within UIStaffContainer --> OnReceiveFocus() I would like a hook, if that's the right word for it, that allows me to exit the function before any of its custom logic is called. In other words, I would like it to call super.OnReceiveFocus(), but nothing else. This way I can write my own logic for navigation and not have to worry about the UIStaffContainer overriding some of what I have done.

**Comment by GingerAvalanche** [comment]
Where are you writing this logic? A subclass of UIStaffContainer could simply call Super.Super.OnReceiveFocus() to bypass UIStaffContainer's logic. The only reason you would need a hook directly into UIStaffContainer's logic is if you were directly editing that logic. However, that would only work for your subclass.

If you were looking to make it work for all vanilla classes, i.e. if this were a bug (which it seems to be, given your description of it), then it would be better to simply bypass it or fix it directly.

Either way, I don't think a hook is what you're looking for.

**Comment by kdm2k6** [comment]
For LWotC, I created a ScreenListener for UIFacility's (UIFacility and its subclasses) so that within OnInit() I could kill the navigation system, which has several finicky controller related issues, and create it anew. Everything works well; however, the custom logic within UIStaffContainer --> OnReceiveFocus() gets in the way; you can end up with 2 highlighted buttons when the staff slot container receives focus. It is definitely not game breaking; just a visual UI issue.

Perhaps there is a different way I can go about solving it. I'll think about it. Thanks.

**Comment by GingerAvalanche** [comment]
I think you should test the reverse of your previous test: If you select the second staff slot, press A, press B, press D-Pad left, press D-pad down, press D-pad up, does the second staff slot still receive visual focus despite the first staff slot having navigator focus? If so, this is a bug with `Navigator.GetSelected()` returning the wrong staff slot. If not, it's an issue with `Navigator.GetSelected()` not returning *anything* despite there being a "Selected"

**Comment by GingerAvalanche** [comment]
Upon further investigation, it seems like `SelectedStaffSlot` is pretty useless. It's only set during `ShowDropDown` and only used during `OnReceiveFocus`, the usage of which will preclude the call to `Navigator.GetSelected` which is a more comprehensive solution for this problem anyway. It takes longer to run, but given that it runs every time staff slots are switched without a dropdown being shown anyway (plus it's on a UIPanel on a staff slot - not exactly code that's going to be run every frame), the variable itself seems to be a solution to a problem that never existed.

I'm going to try simply removing it and having `OnReceiveFocus` call `Navigator.GetSelected` as its primary method of determining which slot should receive focus, and then we'll test and see.

**Comment by GingerAvalanche** [comment]
Testing done by @kdm2k6 indicated that everything works as intended with SelectedStaffSlot essentially removed.
