### ISSUE TITLE
Extend HasHeavyWeapon()

### ISSUE THREAD

**Issue by SentySent** [X2CommunityCore/X2WOTCCommunityHighlander#881]
Similar to Issue #735, extend the ability check in `HasHeavyWeapon()` to include item granted abilities and character template abilities.

**Comment by Iridar** [comment]
Would be nice for consistency, though I wanna reiterate that `'OverrideHasHeavyWeapon'` CHL event already exists, as well as `X2DownloadableContentInfo::GetNumHeavyWeaponSlotsOverride()` method.
