### ISSUE TITLE
Allow to change position of my2KButton

### ISSUE THREAD

**Issue by RadRussianRus** [X2CommunityCore/X2WOTCCommunityHighlander#887]
**Script:** XComGame/XComFinalShell.uc
**Reference function:** `OnInit()`

Threre is a my2K button in main menu. For some languages it's moved a little higher:

```unrealscript
m_my2KButton = Spawn(class'UIButton', self);
m_my2KButton.LibID = 'My2KButton';
m_my2KButton.InitButton('My2KButton', ,  ProcessMy2KButtonClick);
m_my2KButton.AnchorBottomRight();
m_my2KButton.SetPosition(-200,-120);

if (GetLanguage() == "FRA" || GetLanguage() == "SPA" || GetLanguage() == "DEU" || GetLanguage() == "ITA")
{
	m_my2KButton.SetPosition(-200, -170);
}
```

However, it's needed not only for these languages. On Russian, for example, it covers half of the exit button. So it would be nice to have a way to move button, since currently position values are hard-coded.

**Comment by Xymanek** [comment]
> Script: XComGame/XComFinalShell.uc

That file doesn't exist, do you mean `UIFinalShell`?

Also, can't you do this change using an `UIScreenListener`?

**Comment by RadRussianRus** [comment]
> That file doesn't exist, do you mean `UIFinalShell`?

Oh, yes, sorry, you're right.


> Also, can't you do this change using an `UIScreenListener`?

Looks like I've completely missed that. Sorry for bothering then.
