### ISSUE TITLE
Add an event to modify new Ability Context

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#890]
Currently, each ability can have its own `ModifyNewContextFn` delegate, which will run after the ability is activated. I suggest expanding this functionality by adding a CHL event right next to the place where the `ModifyNewContextFn` delegates are normally ran.

That would allow to make arbitrary modifications to Ability Context of any ability, without having to add your own `ModifyNewContextFn`  delegates to ability templates, and without having to worry about compatibility.

**Comment by Iridar** [comment]
```
AbilityTemplate = AbilityState.GetMyTemplate();
if( AbilityTemplate.ModifyNewContextFn != none )
{
	AbilityTemplate.ModifyNewContextFn(NewContext);
}
// Start Issue #890
`XEVENTMGR.TriggerEvent('PostModifyNewContext', NewContext, AbilityState);
// End Issue #890
```
I think adding a single event right after running `ModifyNewContextFn` - if it exists - is enough for most use cases. Any objections to `'PostModifyNewContext'` event name?

**Comment by Xymanek** [comment]
> Any objections to `'PostModifyNewContext'` event name?

Yes, it sounds like this can be done to any `XComGameStateContext`, not just `_Ability`. Something like `PostModifyNewAbilityContext` would be much better.

> Also, you're not gonna make me move one line event trigger into a separate private function, are you?

Yes 😏

*No, it's not needed in this case - there is no tuple boilerplate*

**Comment by Iridar** [comment]
Closing because PR was merged.

**Comment by Iridar** [comment]
@robojumper sorry to disturb you because of this, but I am again having this thing where I cannot close the issue.
