### ISSUE TITLE
Add Config option to disable Beta Strike's end tactical heal.

### ISSUE THREAD

**Issue by Mitzruti** [X2CommunityCore/X2WOTCCommunityHighlander#917]
when beta strike is enabled, soldiers are healed for half of the damage they took when tactical ends. this prevents them from ever becoming gravely wounded and reduces recovery times. It'd be good to have an option to shut this feature off.

in XComGameState_Unit, function EndTacticalHealthMod()

**Comment by BlackDog86** [comment]
Made a pull request to fix this issue using a simplified approach which doesn't not allow the user to 'specify' how much post-mission healing happens. It just adds a boolean value which can be activated by config to turn off this strange behaviour.
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/1202
