### ISSUE TITLE
Super concealment roll camera bug

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#919]
Mods that increase camera zoom out distance, like Free Camera Rotation, cause a bug with the super concealment roll animation, where the camera zooms through the floor while it displays the roll that determines whether a reaper or some other class with shadow should be revealed after a shot.

This *probably* happens in the Post Build Viz that gets inserted in XComGameState_Unit. If so, Highlander would be a great place to fix it.

This is the default config in Free Camera Rotation that allegedly causes the bug in `XComCamera.ini`:
```
[XComGame.X2Camera_LookAt]
; remove default values
!RotationInterpolationRampUpDuration
!ZoomInterpolationRampUpDuration
!MaximumInterpolationRotationPerSecond
!MaximumInterpolationZoomPerSecond
!ZoomedDistanceFromCursor
!DistanceFromCursor
; set new values
RotationInterpolationRampUpDuration=0.1     ; in seconds. Total time to go from standstill to full interpolation speed.
ZoomInterpolationRampUpDuration=0.1         ; in seconds. Total time to go from standstill to full interpolation speed.
MaximumInterpolationRotationPerSecond=180    ; in degrees per second. The fastest the game cam is allowed to rotate.
MaximumInterpolationZoomPerSecond=1.0        ; in percent, where 1.0 is 100%.
ZoomedDistanceFromCursor=5024                ; in Unreal units. Distance from lookat target at maximum/minimum zoom (+/- 1.0). (~2.0 of vanilla value, x4.0 of default zoom)
DistanceFromCursor=1256                        ; in Unreal units. Distance from lookat target at default zoom (0.0). (vanilla value)
```
And here is some config Rusty has posted that allegedly fixes the issue:

`XComTacticalInput_FreeCameraRotation.ini`
```[FreeCameraRotation.XComTacticalInput_FreeCameraRotation]
CAMERA_ROTATION_FIXED=45.0f
CAMERA_ROTATION_SPEED=180.0f
CAMERA_ZOOM_SPEED=1.0f
bAnalogMode=false

[FreeCameraRotation.X2Camera_FollowMouseCursor_FreeCameraRotation]
MIN_ZOOM_MULT=--0.375f  ; min allowed zoom multiplier is used to limit zoom in factor as ZoomedDistanceFromCursor (in XComCamera.ini) affects both zoom in and zoom out and big ZoomedDistanceFromCursor values tend to break zoom in.
```
`XComCamera.ini`
```
[XComGame.X2Camera_LookAt]
RotationInterpolationRampUpDuration=0.1 
ZoomInterpolationRampUpDuration=0.1 
MaximumInterpolationRotationPerSecond=180
MaximumInterpolationZoomPerSecond=1.0
ZoomedDistanceFromCursor=5024
DistanceFromCursor=1884
```

With the following comment:

> so from this something differs to base free camera settings (that cause the bug) ... and it either settings in the first config file or DistanceFromCursor
> -- the issue stupid as it sounds is likely caused by the reaper concealment thing not moving 'just the camera' to focus on the reaper... but moving the cursor itself to the reapers root at x,y,0 ... and then 'panning/zooming' the camera to focus on the cursor ... and as it gets to the 0z it overshoots by Min_Zoom_Mult and DistanceFromCursor

This issue needs to be investigated further. The ideal solution is to make the zoom-in animation scale automatically with whatever values specified in the configs.

**Comment by Xymanek** [comment]
This can also be observed during panic rolls, especially if multiple happen in a row

**Comment by Iridar** [comment]
I tried to look into it, but this seems beyond me for the moment. I'll probably just use Rusty's config on my end to bypass this bug. If it actually works maybe I'll publish a standalone mod that patches these configs. Maybe eventually a hero will come and fix this bug in the Highlander.

**Comment by Iridar** [comment]
This issue is a duplicate of #1157, closing this one.
