### ISSUE TITLE
Crash at main menu

### ISSUE THREAD

**Issue by Evolution0** [X2CommunityCore/X2WOTCCommunityHighlander#920]
Lastest version of X2WOTCCommunityHighlander and WOTC.

Found out Highlander was the cause of my crashing instantly right as the main menu tries to load after binary searching my mods, wiped every trace of XCOM 2 WOTC and its files from my PC twice and reinstalled, this included all configs and such, still the same issue.

I get: `Failed to find function SubscribeToOnInputForScreen in UIScreenStack XPACK_Shell_Intro.TheWorld:PersistentLevel.XComShellPresentationLayer_0.UIScreenStack_0`

I do not get this error or any issues without Highlander, and can run with mods that don't require it fine.

I've tried unsubbing and resubbing the mod, manual installation, using the default launcher and refreshing mods, using AML, regenerating inis, and trying the beta.

At this point all I can try is working my way back a release at a time.

Edit: Beta, 1.21.1, 1.20.0, 1.19.1, 1.19.0, all the same error with older revisions complaining about missing the older function SubscribeToOnInput.

Any other insight?

**Comment by Iridar** [comment]
Just to clarify, this error still happens if you try to launch the game with just the Highlander active, no other mods?

**Comment by Iridar** [comment]
This might be helpful: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting

**Comment by Evolution0** [comment]
Yeah I've gone through that and yes with Highlander as the only mod active it does this. Before testing each version I also wiped my configs.

The only thing I haven't done at this point is wipe windows and reinstall which I'm considering.

I've had various input mappers and such installed over the lifetime of this system for things like switch pro controllers and its the last variable really.

I did my best to uninstall them and make sure no services or backround utils were left but who knows.

**Comment by tjdouglas** [comment]
I had this exact problem as well two nights ago. I ended up adding exceptions to my anti-virus software (Malwarebytes) for AML and my entire steamapps folder and that seems to have fixed it. It doesn't appear to be an issue with the CHL per se, but with modded games running on Steam. I've seen reports on other gaming forums for similar experiences with third-party launchers. I'm not knowledgeable enough to comment on possible root causes but something appears to be causing false positives.

**Comment by Evolution0** [comment]
Fresh install of Windows (20H2) and same issue.

If I had the setup for it at this point I would try removing the input hook and see if it fixes it but thats a bit farther than I want to go with this.
