### ISSUE TITLE
Request : Ability to add navigation help on strategy map.

### ISSUE THREAD

**Issue by kdm2k6** [X2CommunityCore/X2WOTCCommunityHighlander#932]
Currently, there appears to be no way to add navigation help to the strategy map.

I believe a hook at the end of `UIStrategyMap.UpdateButtonHelp` would be sufficient for this issue.

Thanks.

**Comment by pledbrook** [comment]
What do you need from the hook? Is it just a notification?

**Comment by kdm2k6** [comment]
Being sent `UIStrategyMap` should be sufficient; that way I have easy access to `NavBar`.
