### ISSUE TITLE
None checks - ensure BC behaviour

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#975]
#910 has done a great effort in cleaning up the logspam left by FXS. Unfortunately, it is also technically a BC break in some cases due to how unreal VM handles missing/default values.

### Example 1

![image](https://user-images.githubusercontent.com/2865341/107873672-c1d80980-6ebc-11eb-9351-7aa7b523d14a.png)

In original case with `none`, `ParamTag.StrValue2` would be set to `""`, while now it isn't set at all

### Example 2

![image](https://user-images.githubusercontent.com/2865341/107873690-dc11e780-6ebc-11eb-813f-775cda25ac12.png)

Originally, `AS_SetFactionIcon` would be still called with a `StackedUIIconData` struct set to all default values

------

I do not see a reason to document every single case due to highly deterministic/predictable behaviour of the VM although I will be happy to answer any questions on discord

Assigning to @Iridar - the author of the PR in question

**This needs to be addressed before releasing 1.22.0** to prevent conflicting BC policy circumstances

**Comment by Iridar** [comment]
Noted, thanks.
