### ISSUE TITLE
Highlander keeps crashing

### ISSUE THREAD

**Issue by ripom4** [X2CommunityCore/X2WOTCCommunityHighlander#98]
I try loading the game with the highlander mod, but it keeps crashing at the startup. I tried different versions of the highlander but I keep getting the same result.

**Comment by MalucoMarinero** [comment]
Hi, are you on MacOS or Linux? (use this version: http://steamcommunity.com/sharedfiles/filedetails/?id=1184500704 if so). Also, are you running any mods which may conflict with class overrides or a highlander of their own?

**Comment by ripom4** [comment]
I'm using Windows and I had tried testing it without any other mods and I ran into the same problem.

**Comment by IvKir** [comment]
So same here. Win7 a lot of mods, and stil CTD. Removed Highlander  - and everything work like a charm.
Tried to disable some of mods, but to no avail. Where i can put my log files to help narrow the problem?
