### ISSUE TITLE
Add Inventory slot for MPP, Template Master.

### ISSUE THREAD

**Issue by Mitzruti** [X2CommunityCore/X2WOTCCommunityHighlander#984]
Add eInvSlot_MZAux, for a series of abilities that will allow equipping various item types in an unlocked slot.

Add eInvSlot_TemplateMaster, for a highly configurable slot in the Iridar's Template Master.

**Comment by Iridar** [comment]
This issue was resolved in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/985, closing.
