### ISSUE TITLE
Add an event to override ReactionFireSequencer

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#996]
ReactionFireSequencer is hardcoded to add cinematic slo-mo to abilities that have `bReactionFire = true` set on their ToHitCalc. This is a big inflexible, as there are legitimate cases where one would want to use cinematic slo-mo with non-reaction abilities, and don't use cinematic slo-mo with non-reaction abilities, and in general it's weird to have game state logic be tied with visualization logic like that.

As such, I propose adding an event into `X2ReactionFireSequencer::IsReactionFire()` that will allow mods to override which abilities count as valid for cinematic slo-mo.

**Comment by Iridar** [comment]
I also want to add an event to modify Reaction Fire hit modifier, should I file a new Issue for that, or can I do this in the context of this one, after renaming it and adjusting description?

**Comment by Xymanek** [comment]
> I also want to add an event to modify Reaction Fire hit modifier, should I file a new Issue for that, or can I do this in the context of this one, after renaming it and adjusting description?

Assuming you are talking about the gameplay chance-to-hit, then I would favor a separate issue since that would be a gameplay feature whereas this is a visualization one

**Comment by Iridar** [comment]
Yeah. Alrighty. I figured they might be close enough, since both events would be required to turn a reaction shot into a non-reaction shot, across both gameplay and viz, but I see your point.

**Comment by Iridar** [comment]
> Yeah. Alrighty. I figured they might be close enough, since both events would be required to turn a reaction shot into a non-reaction shot, across both gameplay and viz, but I see your point.

I changed my mind. Using a unit value to remove reaction fire aim penalties is enough for my current use case, so this event is all I need for the time being.
